### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by lisadaddy** [nymtech/nym#1000]
Dear sir，after upgrade to sandbox version(0.12.1), my node can't send any mix packets for many days, please help me  .Thankyou

Node explorer:
https://sandbox-explorer.nymtech.net/network-components/mixnodes/7AKtpicp4BnqFRZCxoKnt7rGft3Xu5XtXgbvn3DLBeWE

LInux packets SNAOSHOT As Following：
https://github.com/lisadaddy/lisadaddy.github.io/blob/main/2_20211227113357.png

https://github.com/lisadaddy/lisadaddy.github.io/blob/main/photo_2021-12-27_11-14-53.jpg

**Comment by lisadaddy** [comment]
command:  sudo lsof -i TCP:1789

https://github.com/lisadaddy/lisadaddy.github.io/blob/main/3_20211227115556.png

**Comment by lisadaddy** [comment]
Any imporovements, my friend

**Comment by tommyv1987** [comment]
Hi @lisadaddy 

Please, can you take the time to read our medium blog post about active / inactive / reward sets.

The article is [here](https://github.com/tauri-apps/tauri/issues/2732). This will explain how packets will be mixing through nodes. 

Closing the ticket, as it's not a bug.
