### ISSUE TITLE
[Feature Request] Please enable registration without need for Telegram account

### ISSUE THREAD

**Issue by virEmtUgpilUryai** [nymtech/nym#1016]
Hi,

as per my understanding it is mandatory to have a _Telegram_ account to be able to trade NYMT.

However, due to a personal rule not to take part in social networks, I am not able to set up a mix node, for instance. E-Mail, IRC, a decent, "old school" web interface, that's all fine for me. The usage of _Telegram, Signal, Line_ etc is not. 

I a sense of paying attention to anonymity and avoid leaving traces everywhere, I think I am not alone practicing this modus operandi.

Please support additional channels to register a nym mix node/trade NYMT to open _nym_ up to more potential participants.

Thanks!

**Comment by tommyv1987** [comment]
Hi @virEmtUgpilUryai 

Thanks for raising your issue, it's not a requirement to now hold a telegram account to trade NYM. If you're looking to use the nym testnet (sandbox) you can find information on the [Docs](https://nymtech.net/docs/stable/run-nym-nodes/nodes/mixnodes)

``` 
Please note that unless you ran a mixnode in the Milhon testnet, you will not be able to get NYMT tokens and bond your mixnode for the Sandbox testnet at this time.

In the future we will set up a token faucet - watch out for updates on this.

For those not able to immediately get involved, please look into delegated staking. If you do delegate your NYMT to others and shut down your node, remember to save the keys located in $HOME/.nym in case you want to run a node in the future
```
If you were not a participant in the previous test networks, you will have to wait until the faucet becomes live. 

Please keep an eye on the docs as this will provide the updates you need if you don't want to participate in social networks. The documents are regularly updated.
