### ISSUE TITLE
Using Blake3 as a hash function

### ISSUE THREAD

**Issue by aniampio** [nymtech/nym#103]
Recently, Jack O'Connor, Samuel Neves, Jean-Philippe Aumasson, and Zooko published Blake3 hash function, which can be used as PRF (pseudo-random function), MAC (message authentication code), KDF (key derivation function), and XOF (extendable-output function), as well as a regular hash: [link](https://www.vdoo.com/ja/blog/blake3-hash-function-announced)

Blake3 is supposedly much **faster** than previous Blakes or MD5, SHA-1, SHA-2, SHA-3. It's secure against length extension, unlike SHA-2 and highly parallelizable across any number of threads and SIMD lanes, because it's a Merkle tree on the inside. 

There are Rust and C implementations available. 

Since we use or will use many times various hash functions (for example in Sphinx, but also we might need it for some authentication, or in Ococnut), we might consider using Blake3 (hence swap in the existing code or add in a new one) and measure whether it indeed speeds up things.

**Comment by tommyv1987** [comment]
Closing issue, archiving for future planning session — the issues / tasks have moved to a new project board, so we can evaluate shortly.
