### ISSUE TITLE
appimage fail to load in Fedora

### ISSUE THREAD

**Issue by sven-hash** [nymtech/nym#1098]
**Describe the issue**
wallet appimage for ubuntu doesn't start

**Expected behaviour**
start the appimage

**Stack Traces**
```
Gtk-Message: 23:18:41.154: Failed to load module "xapp-gtk3-module"

** (nym-wallet:45668): ERROR **: 23:18:41.392: Unable to spawn a new child process: Failed to execute child process “/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess” (No such file or directory)
[1]    45668 trace trap (core dumped)  ./nym-wallet_1.0.0_amd64_ubuntu20.04.AppImage
```

**Steps to Reproduce**
```
chmod +x nym-wallet_1.0.0_amd64_ubuntu20.04.AppImage
./nym-wallet_1.0.0_amd64_ubuntu20.04.AppImage
```

*Solution*
With this lib webkit2gtk3-devel.x86_64 I was able to build the image from source
Install `dnf install webkit2gtk3-devel.x86_64`

**Additional context**

- `Linux fedora 5.15.18-100.fc34.x86_64 #1 SMP Sat Jan 29 13:00:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Fedora release 34 (Thirty Four)

**Comment by soul-surfer** [comment]
You can get the appimage to work with a symlink. [See this post](https://github.com/nymtech/nym/issues/1070#issuecomment-1023549234). Make sure the link points to the correct lib folder location on your system.

**Comment by sven-hash** [comment]
Unfortunatly it doesn't work with the symlink


```
Gtk-Message: 17:36:44.948: Failed to load module "xapp-gtk3-module"

** (nym-wallet:192426): ERROR **: 17:36:45.306: Unable to spawn a new child process: Failed to execute child process “/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess” (No such file or directory)
[1]    192426 trace trap (core dumped)  ./nym-wallet_1.0.0_amd64_ubuntu20.04.AppImage
```

**Comment by rb-sre** [comment]
Hi,
The referenced post suggests to create a symlink to /usr/lib. However on my Fedora 35 it is located at ```/usr/libexec/webkit2gtk-4.0/WebKitNetworkProcess```, so this symlink fixed the problem:
```bash
sudo ln -s /usr/libexec/webkit2gtk-4.0 /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0
```
If it doesn't work, this could help to find where it is located on your distribution:
```
find /usr/ -name WebKitNetworkProcess 2>/dev/null
```

**Comment by sven-hash** [comment]
This seems to work, thanks! 

https://github.com/nymtech/nym/issues/1098#issuecomment-1074456855
