### ISSUE TITLE
[Issue]cargo build --release issue

### ISSUE THREAD

**Issue by henhito** [nymtech/nym#1101]
**Describe the issue**
A clear and concise description of what the issue is...
Linux ubuntu-1cpu-2gb-uk-lon1 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

cargo build --release
warning: /root/nym/nym/clients/socks5/Cargo.toml: `rust-version` is not supported on this version of Cargo and will be ignored

consider adding `cargo-features = ["rust-version"]` to the manifest
warning: /root/nym/nym/common/client-libs/validator-client/Cargo.toml: `rust-version` is not supported on this version of Cargo and will be ignored

consider adding `cargo-features = ["rust-version"]` to the manifest
warning: /root/nym/nym/clients/native/Cargo.toml: `rust-version` is not supported on this version of Cargo and will be ignored

consider adding `cargo-features = ["rust-version"]` to the manifest
warning: /root/nym/nym/gateway/Cargo.toml: `rust-version` is not supported on this version of Cargo and will be ignored

consider adding `cargo-features = ["rust-version"]` to the manifest
warning: /root/nym/nym/clients/webassembly/Cargo.toml: `rust-version` is not supported on this version of Cargo and will be ignored

consider adding `cargo-features = ["rust-version"]` to the manifest
warning: /root/nym/nym/mixnode/Cargo.toml: `rust-version` is not supported on this version of Cargo and will be ignored

consider adding `cargo-features = ["rust-version"]` to the manifest
warning: /root/nym/nym/validator-api/Cargo.toml: `rust-version` is not supported on this version of Cargo and will be ignored

consider adding `cargo-features = ["rust-version"]` to the manifest
error: no matching package named `cosmrs` found
location searched: https://github.com/cosmos/cosmos-rust?rev=e5a1872083abb3d88fa62dda966e7f5408deba58#e5a18720
required by package `validator-client v0.1.0 (/root/nym/nym/common/client-libs/validator-client)`

**Expected behaviour**
A clear and concise description of what you expected to happen...

the build to succeed, but it does not

**Stack Traces**
If there are stack traces or logs, please provide them here...

**Steps to Reproduce**
Steps to reproduce the behaviour, if you're familiar with BDD syntax, please write it in this style:
- Given I was doing X
- And I installed Y
- When I actioned Y
- Then I expect Z

followed guide below
https://nymtech.net/docs/stable/run-nym-nodes/build-nym#download--build-nym-binaries

**Comment by sven-hash** [comment]
Be sure that you use Rust & cargo >= v1.56
It should resolve the build problem

**Comment by henhito** [comment]
thanks, I installed using the following guide, I think I just need to set the env variable to source from the updated rust version.

https://itsfoss.com/install-rust-cargo-ubuntu-linux/

**Comment by tommyv1987** [comment]
Going to close this issue as the situation looks resolved.
