### ISSUE TITLE
Make builds simpler for node operators

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#114]
Right now we've got Github defaulting to the `develop` branch. This shows our relentless activity nicely, but it's almost guaranteed to be broken and unstable most of the time. 

Adding a `git checkout master` after the `git clone` in the install docs should mostly fix this. When a new version comes out, we typically merge to master when doing the release, so `master` always basically has the latest stable code in it (per gitflow).

**Comment by ststefa** [comment]
I'd vote it is most convenient for node operators if you continued to supply releases for the most popular platforms

**Comment by futurechimp** [comment]
Yes, sorry about that @ststefa I'm building a Linux binary now and will have it up in a few moments.

**Comment by ststefa** [comment]
Hi Dave, I didn’t mean to criticise ;). I just thought your current approach with releasing the binaries here is mighty useful both as a trigger and to update the nodes quickly. And because I built some automation around it ;)

**Comment by futurechimp** [comment]
Cool, all set now Stefan 😀.
