### ISSUE TITLE
Spend coconut credential in multisig consensus

### ISSUE THREAD

**Issue by neacsu** [nymtech/nym#1173]
- [x] Include multisig and group contracts in codebase and modify where necessary
 
- [x] Coconut bandwidth claim contract to have a release function executable only by the multisig contract address

- [x] Validator-apis and gateway (credential client) to have their configurable mnemonic, that is used for executing contracts; look into validator-api nymd clients centralization

- [x] Coconut sent to gateway (cred client), gateway sends it to validator-apis, all of them do coconut checks

- [x] Gateway (cred client) creates proposal, validator-apis vote on it, gateway (cc) executes it

- [x] Deploy new contracts to QA

**Comment by neacsu** [comment]
Step-by-step guide to testing this works:
- Set up contracts:
  - Mixnet contract
  - Group contract with some validator api addresses (maybe 3 APIs) in the members field of init msg
  - Multisig contract with the above group contract address and a random coconut bandwidth contract address
  - Coconut bandwidth contract with the above multisig contract and a random pool address in the init msg
  - Migrate the multisig contract with the above coconut bandwidth contract address to break out of the circular dependency of deploying
  - Put all the addresses in a .env file that will be used throughout the rest of the setup 
- Build and run all the rest of the binaries with the coconut feature enabled
- Initialise and bond a gateway (there should also be running, bonded mixnodes, if there aren't already. but the mixnodes don't depend on these changes)
- Initialise a client (native and socks5 currently support this) that will use the above gateway
- Use the credential client to do a deposit of some amount of tokens, pointing the credential database inside the native/socks5 client’s directory
- After the deposit, the funds should now be in the coconut bandwidth contract, moved from the depositor account
- Use the credential client get-credential command to create a coconut credential inside the database
- Run the native/socks5 client in enabled-credentials-mode and see that it’s granted access to the mixnet by the gateway
- Check that the random pool address now contains the deposited funds, which are no longer in the coconut bandwidth contract

**Comment by tommyv1987** [comment]
Given the context of the behaviours listed above. This ticket is now complete. 

However, we need to discuss quite a few things regarding coconut spending and usage. Tickets have been raised for this.
