### ISSUE TITLE
Check enabling bbbc simultaneously with open access. Estimate what it would take to make this the default compilation target.

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#1175]

**Comment by neacsu** [comment]
Checked that bbbc can work at the same time with open access. The clients and the gateway need to be compiled with `--features eth` for this to happen, and the gateway needs to be run with `--testnet-mode` flag. The client can then either be `init`ed with `--testnet-mode` flag and connect in open access mode, or, if the `--testnet-mode` is not passed at `init`, the `--eth_endpoint` and `--eth_private_key` options need to be passed, and when running it, the client will connect in bbbc mode, attempting to pay for the bandwidth.
