### ISSUE TITLE
COMPILE: Could not compile project using Cargo

### ISSUE THREAD

**Issue by PawlowskiAdrian** [nymtech/nym#118]
on fresh Linux environment

- Rust 1.39, with Cargo

-  sudo apt install pkg-config build-essential libssl-dev

cargo test
    Updating crates.io index
    Updating git repository `https://github.com/nymtech/sphinx`
    Updating git repository `https://github.com/snapview/tokio-tungstenite`
  Downloaded tokio-codec v0.1.2
  Downloaded abci v0.6.5
  Downloaded bs58 v0.3.0
  Downloaded integer-encoding v1.0.7
  Downloaded protobuf v2.10.0
   Compiling bs58 v0.3.0
   Compiling bytes v0.5.4
   Compiling protobuf v2.10.0
   Compiling unicode-width v0.1.7
   Compiling vec_map v0.8.1
   Compiling ansi_term v0.11.0
   Compiling strsim v0.8.0
error: `core::slice::<impl [T]>::len` is not yet stable as a const fn
   --> /home/pc/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.5.4/src/bytes.rs:130:18
    |
130 |             len: bytes.len(),
    |                  ^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `bytes`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by jstuczyn** [comment]
Are you entirely sure you're running rust 1.39.0 - can you run `rustc --version` to make sure? 
When I run it all on 1.38.0 I did experience the same error you got, while it was all fine for 1.39.0.

**Comment by PawlowskiAdrian** [comment]
`$ rustc --version`
`rustc 1.39.0`

`git show`
commit b06b842885a05a6bd5ea7ba536c5a13d3e3a8d38 (HEAD, tag: v0.4.1)
Merge: d21a4bd 2b73aa9
Author: Jedrzej Stuczynski <jedrzej.stuczynski@gmail.com>
Date:   Wed Jan 29 10:15:30 2020 +0000

    Merge branch 'release/v0.4.1'

- changed to master:

commit b06b842885a05a6bd5ea7ba536c5a13d3e3a8d38 (HEAD -> master, tag: v0.4.1)
Merge: d21a4bd 2b73aa9
Author: Jedrzej Stuczynski <jedrzej.stuczynski@gmail.com>
Date:   Wed Jan 29 10:15:30 2020 +0000

    Merge branch 'release/v0.4.1'


- removed Cargo.lock : issues during compile

`cargo test`
error during compile:
<pre><font color="#8AE234"><b>   Compiling</b></font> assert-json-diff v1.0.2
<font color="#8AE234"><b>   Compiling</b></font> tokio-tungstenite v0.10.0 (https://github.com/snapview/tokio-tungstenite?rev=308d9680c0e59dd1e8651659a775c05df937934e#308d9680)
<font color="#8AE234"><b>   Compiling</b></font> mockito v0.22.0
<font color="#EF2929"><b>error[E0432]</b></font><b>: unresolved imports `assert_json_diff::Comparison`, `assert_json_diff::Actual`, `assert_json_diff::Expected`</b>
   <font color="#729FCF"><b>--&gt; </b></font>/home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/mockito-0.22.0/src/lib.rs:527:24
    <font color="#729FCF"><b>|</b></font>
<font color="#729FCF"><b>527</b></font> <font color="#729FCF"><b>| </b></font>use assert_json_diff::{Comparison, assert_json_no_panic, Actual, Expected};
    <font color="#729FCF"><b>| </b></font>                       <font color="#EF2929"><b>^^^^^^^^^^</b></font>                        <font color="#EF2929"><b>^^^^^^</b></font>  <font color="#EF2929"><b>^^^^^^^^</b></font> <font color="#EF2929"><b>no `Expected` in the root</b></font>
    <font color="#729FCF"><b>| </b></font>                       <font color="#EF2929"><b>|</b></font>                                 <font color="#EF2929"><b>|</b></font>
    <font color="#729FCF"><b>| </b></font>                       <font color="#EF2929"><b>|</b></font>                                 <font color="#EF2929"><b>no `Actual` in the root</b></font>
    <font color="#729FCF"><b>| </b></font>                       <font color="#EF2929"><b>no `Comparison` in the root</b></font>

<font color="#EF2929"><b>error[E0061]</b></font><b>: this function takes 3 parameters but 1 parameter was supplied</b>
   <font color="#729FCF"><b>--&gt; </b></font>/home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/mockito-0.22.0/src/lib.rs:640:17
    <font color="#729FCF"><b>|</b></font>
<font color="#729FCF"><b>640</b></font> <font color="#729FCF"><b>| </b></font>                assert_json_no_panic(Comparison::Include(actual, expected)).is_ok()
    <font color="#729FCF"><b>| </b></font>                <font color="#EF2929"><b>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</b></font> <font color="#EF2929"><b>expected 3 parameters</b></font>

<font color="#EF2929"><b>error[E0061]</b></font><b>: this function takes 3 parameters but 1 parameter was supplied</b>
   <font color="#729FCF"><b>--&gt; </b></font>/home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/mockito-0.22.0/src/lib.rs:647:17
    <font color="#729FCF"><b>|</b></font>
<font color="#729FCF"><b>647</b></font> <font color="#729FCF"><b>| </b></font>                assert_json_no_panic(Comparison::Include(actual, expected)).is_ok()
    <font color="#729FCF"><b>| </b></font>                <font color="#EF2929"><b>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</b></font> <font color="#EF2929"><b>expected 3 parameters</b></font>

<font color="#EF2929"><b>error</b></font><b>: aborting due to 3 previous errors</b>

<b>Some errors have detailed explanations: E0061, E0432.</b>
<b>For more information about an error, try `rustc --explain E0061`.</b>
<font color="#EF2929"><b>error</b></font><b>:</b> could not compile `mockito`.
<font color="#FCE94F"><b>warning</b></font><b>:</b> build failed, waiting for other jobs to finish...
<font color="#EF2929"><b>error</b></font><b>:</b> build failed
</pre>

<pre>The number of arguments passed to a function must match the number of arguments
specified in the function signature.

For example, a function like:

```
fn f(a: u16, b: &amp;str) {}
```

Must always be called with exactly two arguments, e.g., `f(2, &quot;test&quot;)`.

Note that Rust does not have a notion of optional function arguments or
variadic functions (except for its C-FFI).</pre>

- trying another cargo command with increased priv to make sure it will work
`sudo cargo build --release`

right now no errors, might have been issue 'cos of package during that day or privileges

Thank you @jstuczyn for a respond.
If it is `sudo` issue, please add it to [https://nymtech.net/docs/mixnet/installation/](https://nymtech.net/docs/mixnet/installation/). 
If not, we can easly close this issue.




Instalation log:
<pre>:<font color="#729FCF"><b>~/git/nym</b></font>$ sudo cargo build --release
[sudo] password for xxx: 
<font color="#8AE234"><b>   Compiling</b></font> futures v0.1.29
<font color="#8AE234"><b>   Compiling</b></font> regex-syntax v0.6.14
<font color="#8AE234"><b>   Compiling</b></font> maybe-uninit v2.0.0
<font color="#8AE234"><b>   Compiling</b></font> rand_core v0.4.2
<font color="#8AE234"><b>   Compiling</b></font> fake-simd v0.1.2
<font color="#8AE234"><b>   Compiling</b></font> smallvec v1.2.0
<font color="#8AE234"><b>   Compiling</b></font> quick-error v1.2.3
<font color="#8AE234"><b>   Compiling</b></font> subtle v2.2.2
<font color="#8AE234"><b>   Compiling</b></font> termcolor v1.1.0
<font color="#8AE234"><b>   Compiling</b></font> cfg-if v0.1.10
<font color="#8AE234"><b>   Compiling</b></font> percent-encoding v2.1.0
<font color="#8AE234"><b>   Compiling</b></font> keystream v1.0.0
<font color="#8AE234"><b>   Compiling</b></font> arrayref v0.3.6
<font color="#8AE234"><b>   Compiling</b></font> version_check v0.9.1
<font color="#8AE234"><b>   Compiling</b></font> bs58 v0.3.0
<font color="#8AE234"><b>   Compiling</b></font> httparse v1.3.4
<font color="#8AE234"><b>   Compiling</b></font> futures-core v0.3.4
<font color="#8AE234"><b>   Compiling</b></font> foreign-types-shared v0.1.1
<font color="#8AE234"><b>   Compiling</b></font> openssl v0.10.28
<font color="#8AE234"><b>   Compiling</b></font> native-tls v0.2.3
<font color="#8AE234"><b>   Compiling</b></font> version_check v0.1.5
<font color="#8AE234"><b>   Compiling</b></font> proc-macro-nested v0.1.3
<font color="#8AE234"><b>   Compiling</b></font> failure_derive v0.1.6
<font color="#8AE234"><b>   Compiling</b></font> futures-sink v0.3.4
<font color="#8AE234"><b>   Compiling</b></font> ryu v1.0.2
<font color="#8AE234"><b>   Compiling</b></font> percent-encoding v1.0.1
<font color="#8AE234"><b>   Compiling</b></font> openssl-probe v0.1.2
<font color="#8AE234"><b>   Compiling</b></font> futures-io v0.3.4
<font color="#8AE234"><b>   Compiling</b></font> crc32fast v1.2.0
<font color="#8AE234"><b>   Compiling</b></font> arc-swap v0.4.4
<font color="#8AE234"><b>   Compiling</b></font> futures-task v0.3.4
<font color="#8AE234"><b>   Compiling</b></font> pin-utils v0.1.0-alpha.4
<font color="#8AE234"><b>   Compiling</b></font> semver-parser v0.7.0
<font color="#8AE234"><b>   Compiling</b></font> rustc-demangle v0.1.16
<font color="#8AE234"><b>   Compiling</b></font> try-lock v0.2.2
<font color="#8AE234"><b>   Compiling</b></font> adler32 v1.0.4
<font color="#8AE234"><b>   Compiling</b></font> encoding_rs v0.8.22
<font color="#8AE234"><b>   Compiling</b></font> bytes v0.5.4
<font color="#8AE234"><b>   Compiling</b></font> pin-project-lite v0.1.4
<font color="#8AE234"><b>   Compiling</b></font> dtoa v0.4.5
<font color="#8AE234"><b>   Compiling</b></font> mime v0.3.16
<font color="#8AE234"><b>   Compiling</b></font> unicode-width v0.1.7
<font color="#8AE234"><b>   Compiling</b></font> base64 v0.11.0
<font color="#8AE234"><b>   Compiling</b></font> strsim v0.8.0
<font color="#8AE234"><b>   Compiling</b></font> vec_map v0.8.1
<font color="#8AE234"><b>   Compiling</b></font> ansi_term v0.11.0
<font color="#8AE234"><b>   Compiling</b></font> dotenv v0.15.0
<font color="#8AE234"><b>   Compiling</b></font> utf-8 v0.7.5
<font color="#8AE234"><b>   Compiling</b></font> libc v0.2.66
<font color="#8AE234"><b>   Compiling</b></font> log v0.4.8
<font color="#8AE234"><b>   Compiling</b></font> proc-macro2 v1.0.8
<font color="#8AE234"><b>   Compiling</b></font> num-traits v0.2.11
<font color="#8AE234"><b>   Compiling</b></font> num-integer v0.1.42
<font color="#8AE234"><b>   Compiling</b></font> indexmap v1.3.2
<font color="#8AE234"><b>   Compiling</b></font> try_from v0.3.2
<font color="#8AE234"><b>   Compiling</b></font> byteorder v1.3.4
<font color="#8AE234"><b>   Compiling</b></font> syn v1.0.14
<font color="#8AE234"><b>   Compiling</b></font> thread_local v1.0.1
<font color="#8AE234"><b>   Compiling</b></font> typenum v1.11.2
<font color="#8AE234"><b>   Compiling</b></font> semver v0.9.0
<font color="#8AE234"><b>   Compiling</b></font> crossbeam-utils v0.7.0
<font color="#8AE234"><b>   Compiling</b></font> crossbeam-epoch v0.8.0
<font color="#8AE234"><b>   Compiling</b></font> rand_pcg v0.1.2
<font color="#8AE234"><b>   Compiling</b></font> rand_chacha v0.1.1
<font color="#8AE234"><b>   Compiling</b></font> rand v0.6.5
<font color="#8AE234"><b>   Compiling</b></font> memchr v2.3.2
<font color="#8AE234"><b>   Compiling</b></font> serde v1.0.104
<font color="#8AE234"><b>   Compiling</b></font> bitflags v1.2.1
<font color="#8AE234"><b>   Compiling</b></font> itertools v0.8.2
<font color="#8AE234"><b>   Compiling</b></font> rand_core v0.3.1
<font color="#8AE234"><b>   Compiling</b></font> block-padding v0.1.5
<font color="#8AE234"><b>   Compiling</b></font> rand_jitter v0.1.4
<font color="#8AE234"><b>   Compiling</b></font> getrandom v0.1.14
<font color="#8AE234"><b>   Compiling</b></font> c2-chacha v0.2.3
<font color="#8AE234"><b>   Compiling</b></font> unicode-bidi v0.3.4
<font color="#8AE234"><b>   Compiling</b></font> unicode-normalization v0.1.12
<font color="#8AE234"><b>   Compiling</b></font> lock_api v0.3.3
<font color="#8AE234"><b>   Compiling</b></font> humantime v1.3.0
<font color="#8AE234"><b>   Compiling</b></font> tokio-sync v0.1.8
<font color="#8AE234"><b>   Compiling</b></font> foreign-types v0.3.2
<font color="#8AE234"><b>   Compiling</b></font> unicase v2.6.0
<font color="#8AE234"><b>   Compiling</b></font> futures-channel v0.3.4
<font color="#8AE234"><b>   Compiling</b></font> error-chain v0.12.1
<font color="#8AE234"><b>   Compiling</b></font> miniz_oxide v0.3.6
<font color="#8AE234"><b>   Compiling</b></font> textwrap v0.11.0
<font color="#8AE234"><b>   Compiling</b></font> rustc_version v0.2.3
<font color="#8AE234"><b>   Compiling</b></font> rand_hc v0.1.0
<font color="#8AE234"><b>   Compiling</b></font> rand_xorshift v0.1.1
<font color="#8AE234"><b>   Compiling</b></font> rand_isaac v0.1.1
<font color="#8AE234"><b>   Compiling</b></font> idna v0.2.0
<font color="#8AE234"><b>   Compiling</b></font> idna v0.1.5
<font color="#8AE234"><b>   Compiling</b></font> version-checker v0.1.0 (/home/xxx/git/nym/common/version-checker)
<font color="#8AE234"><b>   Compiling</b></font> iovec v0.1.4
<font color="#8AE234"><b>   Compiling</b></font> time v0.1.42
<font color="#8AE234"><b>   Compiling</b></font> num_cpus v1.12.0
<font color="#8AE234"><b>   Compiling</b></font> net2 v0.2.33
<font color="#8AE234"><b>   Compiling</b></font> atty v0.2.14
<font color="#8AE234"><b>   Compiling</b></font> rand_os v0.1.3
<font color="#8AE234"><b>   Compiling</b></font> signal-hook-registry v1.2.0
<font color="#8AE234"><b>   Compiling</b></font> dirs-sys v0.3.4
<font color="#8AE234"><b>   Compiling</b></font> want v0.2.0
<font color="#8AE234"><b>   Compiling</b></font> jobserver v0.1.21
<font color="#8AE234"><b>   Compiling</b></font> quote v1.0.2
<font color="#8AE234"><b>   Compiling</b></font> chacha v0.3.0
<font color="#8AE234"><b>   Compiling</b></font> base64 v0.10.1
<font color="#8AE234"><b>   Compiling</b></font> generic-array v0.12.3
<font color="#8AE234"><b>   Compiling</b></font> aho-corasick v0.7.8
<font color="#8AE234"><b>   Compiling</b></font> parking_lot_core v0.6.2
<font color="#8AE234"><b>   Compiling</b></font> memoffset v0.5.3
<font color="#8AE234"><b>   Compiling</b></font> parking_lot v0.9.0
<font color="#8AE234"><b>   Compiling</b></font> hyper v0.12.35
<font color="#8AE234"><b>   Compiling</b></font> url v2.1.1
<font color="#8AE234"><b>   Compiling</b></font> smallvec v0.6.13
<font color="#8AE234"><b>   Compiling</b></font> url v1.7.2
<font color="#8AE234"><b>   Compiling</b></font> flate2 v1.0.13
<font color="#8AE234"><b>   Compiling</b></font> bytes v0.4.12
<font color="#8AE234"><b>   Compiling</b></font> rand_core v0.5.1
<font color="#8AE234"><b>   Compiling</b></font> futures-cpupool v0.1.8
<font color="#8AE234"><b>   Compiling</b></font> mio v0.6.21
<font color="#8AE234"><b>   Compiling</b></font> clap v2.33.0
<font color="#8AE234"><b>   Compiling</b></font> dirs v2.0.2
<font color="#8AE234"><b>   Compiling</b></font> cc v1.0.50
<font color="#8AE234"><b>   Compiling</b></font> digest v0.8.1
<font color="#8AE234"><b>   Compiling</b></font> crypto-mac v0.7.0
<font color="#8AE234"><b>   Compiling</b></font> block-buffer v0.7.3
<font color="#8AE234"><b>   Compiling</b></font> block-cipher-trait v0.6.2
<font color="#8AE234"><b>   Compiling</b></font> stream-cipher v0.3.2
<font color="#8AE234"><b>   Compiling</b></font> tokio-executor v0.1.10
<font color="#8AE234"><b>   Compiling</b></font> crossbeam-queue v0.2.1
<font color="#8AE234"><b>   Compiling</b></font> regex v1.3.4
<font color="#8AE234"><b>   Compiling</b></font> cookie v0.12.0
<font color="#8AE234"><b>   Compiling</b></font> mime_guess v2.0.1
<font color="#8AE234"><b>   Compiling</b></font> rand_chacha v0.2.1
<font color="#8AE234"><b>   Compiling</b></font> tokio-io v0.1.13
<font color="#8AE234"><b>   Compiling</b></font> http v0.1.21
<font color="#8AE234"><b>   Compiling</b></font> tokio-buf v0.1.1
<font color="#8AE234"><b>   Compiling</b></font> string v0.2.1
<font color="#8AE234"><b>   Compiling</b></font> input_buffer v0.2.0
<font color="#8AE234"><b>   Compiling</b></font> mio-uds v0.6.7
<font color="#8AE234"><b>   Compiling</b></font> chrono v0.4.10
<font color="#8AE234"><b>   Compiling</b></font> blake2 v0.8.1
<font color="#8AE234"><b>   Compiling</b></font> hmac v0.7.1
<font color="#8AE234"><b>   Compiling</b></font> sha2 v0.8.1
<font color="#8AE234"><b>   Compiling</b></font> sha-1 v0.8.2
<font color="#8AE234"><b>   Compiling</b></font> aes-soft v0.3.3
<font color="#8AE234"><b>   Compiling</b></font> ctr v0.3.2
<font color="#8AE234"><b>   Compiling</b></font> tokio-current-thread v0.1.7
<font color="#8AE234"><b>   Compiling</b></font> tokio-timer v0.2.13
<font color="#8AE234"><b>   Compiling</b></font> uuid v0.7.4
<font color="#8AE234"><b>   Compiling</b></font> env_logger v0.6.2
<font color="#8AE234"><b>   Compiling</b></font> publicsuffix v1.5.4
<font color="#8AE234"><b>   Compiling</b></font> pem v0.7.0
<font color="#8AE234"><b>   Compiling</b></font> synstructure v0.12.3
<font color="#8AE234"><b>   Compiling</b></font> clear_on_drop v0.2.3
<font color="#8AE234"><b>   Compiling</b></font> libz-sys v1.0.25
<font color="#8AE234"><b>   Compiling</b></font> openssl-sys v0.9.54
<font color="#8AE234"><b>   Compiling</b></font> libgit2-sys v0.9.2
<font color="#8AE234"><b>   Compiling</b></font> backtrace-sys v0.1.32
<font color="#8AE234"><b>   Compiling</b></font> rand v0.7.3
<font color="#8AE234"><b>   Compiling</b></font> http-body v0.1.0
<font color="#8AE234"><b>   Compiling</b></font> h2 v0.1.26
<font color="#8AE234"><b>   Compiling</b></font> lioness v0.1.2
<font color="#8AE234"><b>   Compiling</b></font> hkdf v0.8.0
<font color="#8AE234"><b>   Compiling</b></font> aes-ctr v0.3.0
<font color="#8AE234"><b>   Compiling</b></font> pretty_env_logger v0.3.1
<font color="#8AE234"><b>   Compiling</b></font> rand_distr v0.2.2
<font color="#8AE234"><b>   Compiling</b></font> tokio-reactor v0.1.12
<font color="#8AE234"><b>   Compiling</b></font> crossbeam-deque v0.7.2
<font color="#8AE234"><b>   Compiling</b></font> addressing v0.1.0 (/home/xxx/git/nym/common/addressing)
<font color="#8AE234"><b>   Compiling</b></font> validator-client v0.1.0 (/home/xxx/git/nym/common/clients/validator-client)
<font color="#8AE234"><b>   Compiling</b></font> serde_derive v1.0.104
<font color="#8AE234"><b>   Compiling</b></font> proc-macro-hack v0.5.11
<font color="#8AE234"><b>   Compiling</b></font> tokio-macros v0.2.4
<font color="#8AE234"><b>   Compiling</b></font> pin-project-internal v0.4.8
<font color="#8AE234"><b>   Compiling</b></font> tokio-tcp v0.1.4
<font color="#8AE234"><b>   Compiling</b></font> tokio-threadpool v0.1.18
<font color="#8AE234"><b>   Compiling</b></font> futures-macro v0.3.4
<font color="#8AE234"><b>   Compiling</b></font> curve25519-dalek v1.2.3
<font color="#8AE234"><b>   Compiling</b></font> tokio v0.1.22
<font color="#8AE234"><b>   Compiling</b></font> tokio v0.2.11
<font color="#8AE234"><b>   Compiling</b></font> futures-util v0.3.4
<font color="#8AE234"><b>   Compiling</b></font> tungstenite v0.9.2
<font color="#8AE234"><b>   Compiling</b></font> hyper-tls v0.3.2
<font color="#8AE234"><b>   Compiling</b></font> pin-project v0.4.8
<font color="#8AE234"><b>   Compiling</b></font> futures-executor v0.3.4
<font color="#8AE234"><b>   Compiling</b></font> sphinx v0.1.0 (https://github.com/nymtech/sphinx?rev=8424f4b0933b4a7f64ae828b2edefc5ba43a9e79#8424f4b0)
<font color="#8AE234"><b>   Compiling</b></font> futures v0.3.4
<font color="#8AE234"><b>   Compiling</b></font> crypto v0.1.0 (/home/xxx/git/nym/common/crypto)
<font color="#8AE234"><b>   Compiling</b></font> sfw-provider-requests v0.1.0 (/home/xxx/git/nym/sfw-provider/sfw-provider-requests)
<font color="#8AE234"><b>   Compiling</b></font> tokio-tungstenite v0.10.0 (https://github.com/snapview/tokio-tungstenite?rev=308d9680c0e59dd1e8651659a775c05df937934e#308d9680)
<font color="#8AE234"><b>   Compiling</b></font> pemstore v0.1.0 (/home/xxx/git/nym/common/pemstore)
<font color="#8AE234"><b>   Compiling</b></font> provider-client v0.1.0 (/home/xxx/git/nym/common/clients/provider-client)
<font color="#8AE234"><b>   Compiling</b></font> backtrace v0.3.44
<font color="#8AE234"><b>   Compiling</b></font> failure v0.1.6
<font color="#8AE234"><b>   Compiling</b></font> serde_json v1.0.48
<font color="#8AE234"><b>   Compiling</b></font> serde_urlencoded v0.5.5
<font color="#8AE234"><b>   Compiling</b></font> topology v0.1.0 (/home/xxx/git/nym/common/topology)
<font color="#8AE234"><b>   Compiling</b></font> toml v0.5.6
<font color="#8AE234"><b>   Compiling</b></font> mix-client v0.1.0 (/home/xxx/git/nym/common/clients/mix-client)
<font color="#8AE234"><b>   Compiling</b></font> cookie_store v0.7.0
<font color="#8AE234"><b>   Compiling</b></font> reqwest v0.9.24
<font color="#8AE234"><b>   Compiling</b></font> directory-client v0.1.0 (/home/xxx/git/nym/common/clients/directory-client)
<font color="#8AE234"><b>   Compiling</b></font> healthcheck v0.1.0 (/home/xxx/git/nym/common/healthcheck)
<font color="#FCE94F"><b>warning</b></font><b>: unused imports: `debug`, `error`, `info`</b>
 <font color="#729FCF"><b>--&gt; </b></font>common/healthcheck/src/lib.rs:5:11
  <font color="#729FCF"><b>|</b></font>
<font color="#729FCF"><b>5</b></font> <font color="#729FCF"><b>| </b></font>use log::{debug, error, info, trace};
  <font color="#729FCF"><b>| </b></font>          <font color="#FCE94F"><b>^^^^^</b></font>  <font color="#FCE94F"><b>^^^^^</b></font>  <font color="#FCE94F"><b>^^^^</b></font>
  <font color="#729FCF"><b>|</b></font>
  <font color="#729FCF"><b>= </b></font><b>note</b>: `#[warn(unused_imports)]` on by default

<font color="#FCE94F"><b>warning</b></font><b>: unused import: `directory_client::requests::presence_topology_get::PresenceTopologyGetRequester`</b>
 <font color="#729FCF"><b>--&gt; </b></font>common/healthcheck/src/lib.rs:3:5
  <font color="#729FCF"><b>|</b></font>
<font color="#729FCF"><b>3</b></font> <font color="#729FCF"><b>| </b></font>use directory_client::requests::presence_topology_get::PresenceTopologyGetRequester;
  <font color="#729FCF"><b>| </b></font>    <font color="#FCE94F"><b>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</b></font>

<font color="#FCE94F"><b>warning</b></font><b>: unused import: `directory_client::DirectoryClient`</b>
 <font color="#729FCF"><b>--&gt; </b></font>common/healthcheck/src/lib.rs:4:5
  <font color="#729FCF"><b>|</b></font>
<font color="#729FCF"><b>4</b></font> <font color="#729FCF"><b>| </b></font>use directory_client::DirectoryClient;
  <font color="#729FCF"><b>| </b></font>    <font color="#FCE94F"><b>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</b></font>

<font color="#8AE234"><b>   Compiling</b></font> git2 v0.10.2
<font color="#8AE234"><b>   Compiling</b></font> built v0.3.2
<font color="#8AE234"><b>   Compiling</b></font> nym-client v0.4.1 (/home/xxx/git/nym/nym-client)
<font color="#8AE234"><b>   Compiling</b></font> nym-validator v0.4.1 (/home/xxx/git/nym/validator)
<font color="#8AE234"><b>   Compiling</b></font> nym-mixnode v0.4.1 (/home/xxx/git/nym/mixnode)
<font color="#8AE234"><b>   Compiling</b></font> nym-sfw-provider v0.4.1 (/home/xxx/git/nym/sfw-provider)
<font color="#8AE234"><b>    Finished</b></font> release [optimized] target(s) in 7m 05s
</pre>
