### ISSUE TITLE
[Issue] Wallet 1.0.2 cannot send NYM tokens from a DelayedVestingAccount

### ISSUE THREAD

**Issue by raphael-walther** [nymtech/nym#1215]
**Describe the issue**
Sending NYM tokens with the 1.0.2 wallet is not possible with DelayedVestingAccount as a source account.

**Expected behaviour**
It should send the transaction to validator and the token to destination account.

**Steps to Reproduce**
- Start wallet and log in a DelayedVestingAccount
- click on Send
- fill To address and amount
- Click Next
- Click Send

Error message within the wallet:
An error occured during the request There was an issue when attempting to decode our protobuf data - failed to decode Protobuf message: BaseAccount.address: invalid string value: data is not UTF-8 encoded

**Comment by jstuczyn** [comment]
underlying issue: https://github.com/nymtech/nym/issues/2050
