### ISSUE TITLE
Mixnode FAQ link broken in documentation

### ISSUE THREAD

**Issue by ewennedelec** [nymtech/nym#1222]
In the documentation chapter mixnode, the link [Troubleshooting FAQ](https://nymtech.net/docs/run-nym-nodes/troubleshooting/#how-can-i-tell-my-node-is-up-and-running-and-mixing-traffic) is broken and redirects to "404 not found" page

I would have expected to be redirected to the Mixnode FAQ page

![image](https://user-images.githubusercontent.com/79302708/165108121-395204d4-45e7-4326-bee0-8989a6783132.png)

**Comment by tommyv1987** [comment]
@mfahampshire are you able to fix this routing issue?

Thank you.

**Comment by liam0215** [comment]
Note the correct URL is [https://nymtech.net/docs/stable/run-nym-nodes/nodes/troubleshooting/#how-can-i-tell-my-node-is-up-and-running-and-mixing-traffic](https://nymtech.net/docs/stable/run-nym-nodes/nodes/troubleshooting/#how-can-i-tell-my-node-is-up-and-running-and-mixing-traffic)

**Comment by mfahampshire** [comment]
I'll sort this out now - missed this. @ewennedelec in the future if you find issues in the docs, please drop it in the docs issues here: https://github.com/nymtech/docs/issues

**Comment by mfahampshire** [comment]
thanks for raising this issue as well btw :)
