### ISSUE TITLE
NYM app crashes on launch (W10 x64)

### ISSUE THREAD

**Issue by Agamatus** [nymtech/nym#1226]
After an attempt to start the app it crashes

https://drive.google.com/file/d/1k6z8h26AS_bx1pqXVg6RzpOLI_0egOPU/view?usp=sharing

**Comment by tommyv1987** [comment]
@Agamatus 

Please can you provide more information ->

- Your OS version?
- The steps to reproduce?
- The version of the wallet?

Thank you.

**Comment by tommyv1987** [comment]
I have not been able to reproduce this issue. Going to close this ticket.
