### ISSUE TITLE
[Issue] Failed to unbond mixnode

### ISSUE THREAD

**Issue by hairtail** [nymtech/nym#1255]
**Describe the issue**
Failed to unbond mixnode with pc wallet.

**Expected behaviour**
Get "Failed to unbond mixnode}".

**Stack Traces**
No.

**Steps to Reproduce**
- Click unbond in wallet

**Screenshots**
<img width="355" alt="image" src="https://user-images.githubusercontent.com/82858858/167090582-8b842d06-2d58-4105-9064-445a1bf3fb4a.png">

**Which area of Nym were you using?**
 - Application: Wallet (pc)
 - OS: MacOs Monterey 12.2.1, Apple M1 Pro
 - Version: NYM Wallet 1.0.4
 - Environment: nyx mainnet
 - Identity of Mixnode: 8mfqLLpuPxdBaWbDFWriCiSTkobZspZPHW3QhzmZWdNu

**Comment by tommyv1987** [comment]
Hi @hairtail,

Can you provide more information on this please:

- Which environment is this? {mainnet / sandbo} 
- The Mixnode identity key?

Thank you.

**Comment by hairtail** [comment]
> Hi @hairtail,
> 
> Can you provide more information on this please:
> 
> * Which environment is this? {mainnet / sandbo}
> * The Mixnode identity key?
> 
> Thank you.

Updated

**Comment by tommyv1987** [comment]
Hi @hairtail,

I'm looking at the blocks and can't see any broadcasted txs on the network for unbonding.

Have you tried to unbond again? And in what part of the wallet are you performing the unbond action?

Inside the bond page {there's an additional button here if you have an existing bond} / unbond page?

**Comment by hairtail** [comment]
For 1st question: I have tried for more than 10 times and get this error for all of them. 
For 2nd question: Both of them, bond page and unbond page.
The reason for You cannot find the tx or pending tx maybe " the wallet get panic before broadcast the tx". But, I'm sure my network is ok since gas estimate component works well.

**Comment by miscab** [comment]
I got the same issue in my wallet 1.0.4 on ubuntu 20.04.

In order to get into more detail, I wrote a simple rust program to unbond my node and get the backtrace as below:


thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NymdError { source: AbciError(18, Log("failed to execute message; message index: 0: Error calling the VM: Error executing Wasm: Wasmer runtime error: RuntimeError: unreachable: execute wasm contract failed: invalid request")) }', src-tauri/src/main.rs:159:51
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1065:23
   4: nym_wallet::main::{{closure}}
             at ./src-tauri/src/main.rs:159:15
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
   6: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /Users/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:54
   7: tokio::coop::with_budget::{{closure}}
             at /Users/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
   8: std::thread::local::LocalKey<T>::try_with
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:413:16
   9: std::thread::local::LocalKey<T>::with
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:389:9
  10: tokio::coop::with_budget
             at /Users/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
  11: tokio::coop::budget
             at /Users/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
  12: tokio::park::thread::CachedParkThread::block_on
             at /Users/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:31
  13: tokio::runtime::enter::Enter::block_on
             at /Users/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/enter.rs:151:13
  14: tokio::runtime::thread_pool::ThreadPool::block_on
             at /Users/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/mod.rs:73:9
  15: tokio::runtime::Runtime::block_on
             at /Users/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/mod.rs:477:43
  16: nym_wallet::main
             at ./src-tauri/src/main.rs:122:3
  17: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by miscab** [comment]
My rust program run well yesterday, when I upgraded to 1.0.1 binaries, my rust program automatically unbonded a bunch of nodes and rebonded them, all of those operations succeed. So I'm sure my program is OK. Must be something wrong with the mainnet.

**Comment by hairtail** [comment]
> My rust program run well yesterday, when I upgraded to 1.0.1 binaries, my rust program automatically unbonded a bunch of nodes and rebonded them, all of those operations succeed. So I'm sure my program is OK. Must be something wrong with the mainnet.

Me too. All my bond and unbond operations succeed yesterday.

**Comment by tommyv1987** [comment]
Hi Both, 

We are in the process of looking into this issue and we will update once we have more information. 

I have tried to bond and unbond operations successfully, as a process of elimination. Could both of you try to remove the existing v1.04 version of the wallet, reinstall v1.03 and try the process again.

I'm not indicating this is a fix, I want to see the results from the output. 

We're looking at other areas. 

Thank you.

**Comment by hairtail** [comment]
I have tried version v1.0.3 and it does not work.

**Comment by tommyv1987** [comment]
@hairtail,

Can you confirm you used the 1.0.1 version of the mixnode binary?

**Comment by hairtail** [comment]
Yeah, sir.
<img width="590" alt="image" src="https://user-images.githubusercontent.com/82858858/167137137-448e044b-ce62-4ecd-9dc4-e24aaa576b5c.png">

**Comment by hairtail** [comment]
Actually, I do not change anything. All my operations succeed yesterday, but fail today.

**Comment by tommyv1987** [comment]
Thank you for your response. We are going to try and replay your scenario with a similar transaction.

Once we have an update we will reply.

**Comment by tommyv1987** [comment]
@hairtail 

Please can you try unbonding again please?

Also, please take into account your profit margin percentages when bonding mixnodes in the future.

Thanks

**Comment by hairtail** [comment]
Seems the bug was fixed. unbond successfully with version v1.0.3
