### ISSUE TITLE
[Issue] mixnode crashed with an error

### ISSUE THREAD

**Issue by Yurbason** [nymtech/nym#1259]
today, for some unknown reason, the mixer spontaneously crashed with an error and restarted

```
May 07 08:02:55 nm3 nym-mixnode[24618]:  2022-05-07T05:02:55.245Z INFO  nym_mixnode::node::node_statistics              > Since startup mixed 574464 packets! (58 in last 30 seconds)
May 07 08:03:55 nm3 nym-mixnode[24618]:  2022-05-07T05:03:55.245Z INFO  nym_mixnode::node::node_statistics              > Since startup mixed 574582 packets! (51 in last 30 seconds)
May 07 08:04:17 nm3 nym-mixnode[24618]: thread 'tokio-runtime-worker' panicked at 'attempt to multiply with overflow', /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/num/mod.rs:827:5
May 07 08:04:17 nm3 nym-mixnode[24618]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
May 07 08:04:17 nm3 systemd[1]: nym-mixnode.service: Main process exited, code=killed, status=6/ABRT
May 07 08:04:17 nm3 systemd[1]: nym-mixnode.service: Failed with result 'signal'.
May 07 08:05:17 nm3 systemd[1]: nym-mixnode.service: Scheduled restart job, restart counter is at 1.
May 07 08:05:17 nm3 systemd[1]: Stopped Nym mixnode service.
May 07 08:05:17 nm3 systemd[1]: Started Nym mixnode service.
```
version: 1.0.1
Identity Key: J6BS3sDwt9Du7yeJt4eEGt59uWKjFqV6CoEo8t6xCAcU
Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-109-generic x86_64)
memory and processor utilization in this interval were common (see screenshot)
![nym](https://user-images.githubusercontent.com/52459938/167239813-409cfa47-6a44-4b27-ac48-e7d675c6dae1.JPG)

**Comment by vlasinus** [comment]
Same problem.
Restart every ~20-30k mixed packets
--------------------------------------------
2022-05-06T09:46:24.671Z INFO  nym_mixnode::node::node_statistics              > Since startup mixed 24783 packets! (50 in last 30 seconds)
 2022-05-06T09:47:24.672Z INFO  nym_mixnode::node::node_statistics              > Since startup mixed 24905 packets! (53 in last 30 seconds)
thread 'tokio-runtime-worker' panicked at 'attempt to multiply with overflow', /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/num/mod.rs:827:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
nym-mixnode.service: Main process exited, code=killed, status=6/ABRT
nym-mixnode.service: Failed with result 'signal'.
nym-mixnode.service: Consumed 1min 3.182s CPU time.
nym-mixnode.service: Scheduled restart job, restart counter is at 1.
Stopped Nym Mixnode.
nym-mixnode.service: Consumed 1min 3.182s CPU time.
Started Nym Mixnode.
      _ __  _   _ _ __ ___
     | '_ \| | | | '_ \ _ \
     | | | | |_| | | | | | |
     |_| |_|\__, |_| |_| |_|
            |___/
             (mixnode - version 1.0.1)
________________________________________________________
Identity Key: 3ERjVpCiwKdYfk9fyumfQhy291dxnuXncu4Qn7VkVH7M
Ubuntu 22.04
Dedicated server working over NAT (router)

**Comment by miscab** [comment]
same problem for v1.0.1 on ubuntu 20.04.

This problem happened to each of my mixnodes.

**Comment by zhanghaoda** [comment]
same here for both version 1.0.1 and v1.0.0-rc.2
`2022-05-07T12:01:13.795Z WARN  mixnet_client::client                           > Failed to forward packets to 122.195.186.226:1789 - IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
thread 'tokio-runtime-worker' panicked at 'attempt to multiply with overflow', /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/num/mod.rs:827:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

**Comment by vlasinus** [comment]
> ## Same problem.
> Restart every ~20-30k mixed packets
> 2022-05-06T09:46:24.671Z INFO nym_mixnode::node::node_statistics > Since startup mixed 24783 packets! (50 in last 30 seconds) 2022-05-06T09:47:24.672Z INFO nym_mixnode::node::node_statistics > Since startup mixed 24905 packets! (53 in last 30 seconds) thread 'tokio-runtime-worker' panicked at 'attempt to multiply with overflow', /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/num/mod.rs:827:5 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace nym-mixnode.service: Main process exited, code=killed, status=6/ABRT nym-mixnode.service: Failed with result 'signal'. nym-mixnode.service: Consumed 1min 3.182s CPU time. nym-mixnode.service: Scheduled restart job, restart counter is at 1. Stopped Nym Mixnode. nym-mixnode.service: Consumed 1min 3.182s CPU time. Started Nym Mixnode. _ __ _ _ _ __ ___ | '_ | | | | '_ \ _ | | | | |_| | | | | | | |_| |_|__, |_| |_| |_| |___/ (mixnode - version 1.0.1)
> 
> Identity Key: 3ERjVpCiwKdYfk9fyumfQhy291dxnuXncu4Qn7VkVH7M Ubuntu 22.04 Dedicated server working over NAT (router)

UPDATE with RUST_BACKTRACE=1

thread 'tokio-runtime-worker' panicked at 'attempt to multiply with overflow', /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/num/mod.rs:827:5
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:48:5
   3: mixnet_client::client::Client::make_connection
   4: <mixnet_client::client::Client as mixnet_client::client::SendWithoutResponse>::send_without_response
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
nym-mixnode.service: Main process exited, code=killed, status=6/ABRT
nym-mixnode.service: Failed with result 'signal'.
nym-mixnode.service: Consumed 1min 2.210s CPU time.
nym-mixnode.service: Scheduled restart job, restart counter is at 13.
Stopped Nym Mixnode.

**Comment by tommyv1987** [comment]
Hi Everyone,

We are aware of the issue—https://github.com/nymtech/nym/issues/1123, as it's been raised here. We have started to look into this.

I will close this ticket and point to the open issue above.
