### ISSUE TITLE
[Issue] No gateways on Sandbox network for `nym-client`

### ISSUE THREAD

**Issue by numbleroot** [nymtech/nym#1268]
**Describe the issue**

When following [the build steps](https://nymtech.net/docs/stable/run-nym-nodes/build-nym) with `NETWORK=sandbox cargo build --release` as the final command and subsequently initializing `nym-client` via [these steps](https://nymtech.net/docs/stable/developers/develop-with-nym/websocket-client), the client panicks with the following message:
`'there are no gateways on the network!', clients/native/src/commands/init.rs:142:14`.

**Expected behaviour**

I would expect `nym-client` to connect successfully to the Sandbox network when following the steps from the documentation and [some gateways being available](https://sandbox-explorer.nymtech.net/network-components/gateways).

**Stack Traces**

Full log of initializing a `nym-client` on the Sandbox network:
```bash
user@machine $   ./nym-client init --id test123


      _ __  _   _ _ __ ___
     | '_ \| | | | '_ \ _ \
     | | | | |_| | | | | | |
     |_| |_|\__, |_| |_| |_|
            |___/

             (client - version 1.0.1)


Initialising client...
thread 'main' panicked at 'there are no gateways on the network!', clients/native/src/commands/init.rs:142:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

**Steps to Reproduce**

- Given I successfully compiled a `v1.0.1`-tagged `nym-client` for the Sandbox network via the instructions in the docs,
- And gateways are [listed in the Nym Network Explorer as running](https://sandbox-explorer.nymtech.net/network-components/gateways),
- When I ran `nym-client init --id test123`
- Then the client panicked with above listed error message.

**Which area of Nym were you using?**
 - Application: `nym-client`
 - OS: Ubuntu 22.04
 - Version: nym at `v1.0.1`

**Comment by numbleroot** [comment]
If I replace `v1.0.1` with `v0.12.1` in the steps above, I can successfully connect to the Sandbox network. Are Nym infrastructure nodes partitioned according to their Nym version, such that they can only be used by Nym clients of the same version?

**Comment by tommyv1987** [comment]
Hi @numbleroot - thank you for raising this, and we're aware of the situation. We will be amending our Sandbox environment shortly, and everything will be working, with the latest binaries and so forth. We're sorry for the inconvenience in the interim.

**Comment by numbleroot** [comment]
I see, thanks @tommyv1987. Please feel free to close.
