### ISSUE TITLE
Simplify message encapsulation with regards to topology 

### ISSUE THREAD

**Issue by jstuczyn** [nymtech/nym#127]
Currently when creating a route for a message, there's relatively a lot computation being done for every single packet - like `make_layered_topology()`. In the long run this will be improved by introducing `GraphTopology`, but is it possibly to introduce some better solution in the meantime?

**Comment by tommyv1987** [comment]
Closing issue, archiving for future planning session - the issues / tasks have moved to a new project board, so we can evaluate shortly.
