### ISSUE TITLE
[Issue] Duplicate definitions: error: duplicate lang item in crate

### ISSUE THREAD

**Issue by Grommish** [nymtech/nym#1280]
**Describe the issue**
When building `nym`, crate `nym-netowrk-requester` fails to build.  Building with `aarch64-openwrt-linux-musl` under `rust-1.60.0` from source.

`RUSTFLAGS=" -C link-arg=-lgcc -C linker=/media/data/openwrt/staging_dir/toolchain-aarch64_cortex-a72_gcc-11.2.0_musl/bin/aarch64-openwrt-linux-musl-gcc -C ar=/media/data/openwrt/staging_dir/toolchain-aarch64_cortex-a72_gcc-11.2.0_musl/bin/aarch64-openwrt-linux-musl-gcc-ar -C target-cpu=cortex-a72" CARGO_HOME="/media/data/openwrt/staging_dir/host" cargo build -v --release -Z build-std --target aarch64-openwrt-linux-musl --workspace`

**Expected behaviour**
Build Successfully

**Stack Traces**

Due to size limitations, Log is here: https://gist.github.com/Grommish/2bc94420249bc1ec7cbd60ec85abba5d

**Which area of Nym were you using?**
Source Build from HEAD `d7e82b075f438fbeb529eac26f83dc5af3328dd9`

I have integrated `rust-lang` into the OpenWrt project, including the rust-lang tuples for the various OpenWrt targets.  It has no issues compiling every test package I've tossed at it, and as part of the testing process, I tried `nym`. 

I've discovered issues with `ring` under `aarch64`, which requires the `-C link-arg=-lgcc`, and now I've hit the wall with the above error.  Any help you might be able to provide would be greatly appreciated!

**Comment by gyrusdentatus** [comment]
Did you manage to build some other binaries @Grommish ?

**Comment by Grommish** [comment]
Other rust-lang applications?  Yes.. Currently, I support `bandwhich`, `bottom`, `ripgrep`, `vaultwarden` and `suricata6` for OpenWrt, all of which are rust-based, and in the case of `suricata6`, has a Makefile wrapper similar to `nym`.

**Comment by Grommish** [comment]
Received the following errors when trying to compile the `nym-gateway` binary.

https://gist.github.com/Grommish/626e8431d25f4dcf43c23791659c6a59

**Comment by gyrusdentatus** [comment]
@Grommish I successfully compiled the thing (**tags/v0.12.1**) in a `cross` docker container (I don't even know what container it is actually lol...)  

I compiled it kinda the same way as I would with using `cross` (cargo) directly but if you attach to the container, then clone OpenWRT repo it works ! 

so the whole `ring` issue can be ruled out as a fault of Nym's code. 

I have yet to try other binaries, only tried `nym-gateway` 

EDIT: 

try `git checkout tags/v0.12.1` and just `nym-gateway` binary.

**Comment by Grommish** [comment]
It isn't a `ring` issue, as I've said.  The `ring` issue was not really an issue.

The issue I'm currently seeing has to do with duplicate definitions, especially in the `libc` crate.  The last time I saw something like this, it was with the `rustix` crate and the fact their default backend wasn't playing nice with MUSL. (https://github.com/bytecodealliance/rustix/pull/343)

That being said, the `rustix` crate allowed for using `libc` and `nym` does not.  Compiling it with a docker container?  That defeats the entire purpose of compiling code from source along a trusted chain.  It's one of the reasons the OpenWrt implementation builds both `rust` and `llvm` from source, rather than using `rustup`.

Whatever scary voodoo magic is going on in the `cross` docker container should be able to be applied 1 for 1 with a standard `rustc` and `cargo` install.

**Comment by gyrusdentatus** [comment]
> It isn't a `ring` issue, as I've said. The `ring` issue was not really an issue.
> 
> The issue I'm currently seeing has to do with duplicate definitions, especially in the `libc` crate. The last time I saw something like this, it was with the `rustix` crate and the fact their default backend wasn't playing nice with MUSL. ([bytecodealliance/rustix#343](https://github.com/bytecodealliance/rustix/pull/343))
> 
> That being said, the `rustix` crate allowed for using `libc` and `nym` does not. Compiling it with a docker container? That defeats the entire purpose of compiling code from source along a trusted chain. It's one of the reasons the OpenWrt implementation builds both `rust` and `llvm` from source, rather than using `rustup`.
> 
> Whatever scary voodoo magic is going on in the `cross` docker container should be able to be applied 1 for 1 with a standard `rustc` and `cargo` install.

Yeah, well I'm just telling you it worked - I am not sure why it does not work some other way but I would really want to find out. 


> It's one of the reasons the OpenWrt implementation builds both `rust` and `llvm` from source, rather than using `rustup`

I was running into issues with your implementation. I would need some documentation since I am not that familiar with OpenWRT and `make` and all that... 

It would be great if you could write a short README in that branch of your `packages` fork. Thanks for all the good stuff you're doing anyway. Problem is probably at my side most of the time, PEBKAC! So excuse my stupidity 

**EDIT**: I realized I used [this](https://github.com/messense/rust-musl-cross) , try checking out the Dockerfile what is going on there and try to apply it on your host ...? Perhaps it will lead somewhere ?

**Comment by gyrusdentatus** [comment]
@mmsinclair what did you do that all bins are built without a problem out of the box? Did you fix it during your android development or was it fixed downstream in the crypto libs like ring etc ? I don’t really remember anymore.
