### ISSUE TITLE
[Feature Request] mix node version endpoint 

### ISSUE THREAD

**Issue by mfahampshire** [nymtech/nym#1337]
( moved here by me, originally an issue made by @evgeny-garanin in docs repo )

Currently, we can only learn which version mixnode is running by seeing what node operator has put into Version field.
There are few issues with this:

version can be gamed
in order to change it after you update the mixnode - you have to unbond, do update, bond again which makes you leave active set for 1 hour (at least). This may hurt node operator reputation as currently mixnode updates are not mandatory and are not announced beforehand so that node operators can prepare to it and alert their delegators on planned technical downtime
Proposal:

add version query endpoint for mixnode.
This will remove necessity to input version in the Bond form and 1hour downtime of mixnodes.
set rewards mechanism to only reward mixnodes of latest release version
optionally, add version-check in validator-api for uptime measurement module. Only count uptime for latest version of mixnodes
prepare workflow which will make mixnode updates more clear with coordination of CMs, prior announcements in the official NYM channels

**Comment by evgeny-garanin** [comment]
Thank you for cleaning it up! @mfahampshire
