### ISSUE TITLE
Rethink client addressability

### ISSUE THREAD

**Issue by jstuczyn** [nymtech/nym#135]
Right now client is identified by it's address and address only. It is derived directly from its public key (in fact it IS it's public key). However, the problem arises when there are more than a single provider on the network - how should we be constructing packets to given client? Somehow client should be addressed by it's address as well as it's providers'. However, presumably, once implemented SURBs will change this even further. We really need to give it some thought as right now our network is really restricted and will not function correctly if there is more than a single provider (of the correct version) on the network and can be very easily 'attacked' this way.

**Comment by futurechimp** [comment]
Is it the case that if we look to our elders, we may find answers from an earlier time? 

What about our old buddy the `@` symbol? 

Clients need to pick a provider (and we can provider a default hostname like `testnet-gateway.nymtech.net` in our implementation). Then they might be addressed as `foo123456xthisismybigbadaddress@testnet-gateway.nymtech.net`? And if others want to also run gateways/providers (if we go that way), then application authors can allow users to choose which one? 

At that point it looks a lot like email servers. Coming from my in-built 1970s perspective I think that's not a bad thing. Let's chat about it some more.
