### ISSUE TITLE
[Feature Request] sign in by pressing Enter key

### ISSUE THREAD

**Issue by rachyandco** [nymtech/nym#1358]
**Is your feature request related to a problem? Please describe.**
On the Wallet 1.0.5, Ubuntu, during the signing process, after entering the password or the mnemonic,  pressing  the "Enter" key should allow the similar action as clicking on the "sign in" button.

**Where does the feature fit in the Nym real estate?**
- Nym Wallet

**What is this solving?**
After pasting with Control+V the password or the mnemonic, some users, like me, hit the Enter button for further action. We currently are left in disarray after hitting the Enter button and noticing no reaction from the app. We then have to use the mouse in order to click on the button, or hit the "Tab" twice then "Enter" in order to keep a full keyboard experience.

**Comment by fmtabbara** [comment]
Released in wallet version 1.0.7
