### ISSUE TITLE
Compound reward make total stake mismatch

### ISSUE THREAD

**Issue by vnpmid** [nymtech/nym#1433]
**Describe the issue**
Compound reward make total stake mismatch

**Expected behaviour**
Mixnode total stake match with detail delegation

**Steps to Reproduce**
- Compound reward
- Deleted from node delegation list but total stake not decreased
- Wait 1 epoch
- Listed in node delegation list total stake increase

**Screenshots**
![1xx](https://user-images.githubusercontent.com/17582293/177249545-742ab219-989c-49e3-bb16-626308373ffb.png)
![2xx1](https://user-images.githubusercontent.com/17582293/177249913-31b7042d-2020-4799-a733-8047a376875d.png)
![3xx1](https://user-images.githubusercontent.com/17582293/177250288-afed2b64-ef5c-4883-93c9-3e887fb45658.png)

**Which area of Nym were you using?**
 - Nodeguru explorer
 - Wallet 1.0.6
 - Windows 10

**Additional context**
Please provide any other information

**Comment by sven-hash** [comment]
Nym explorer is impacted too

**Comment by vnpmid** [comment]
pos mechanism impacted too. seems it saved on blockchain as network topology. if your node want to active more frequently just do compound reward. :D

**Comment by vnpmid** [comment]
> Nym explorer is impacted too

yes i know. pos mechanism impacted too. seems it saved on blockchain as network topology. if your node want to active more frequently just do compound reward. :D

**Comment by sven-hash** [comment]
Two of our mixnodes are impacted by this bug. Is there a way to solve this ?
```
APxUbCmGp4K9qDzvwVADJFNu8S3JV1AJBw7q6bS5KN9E
4yRfauFzZnejJhG2FACTVQ7UnYEcFUYw3HzXrmuwLMaR
```
