### ISSUE TITLE
Secure multi-node communications outside of the chain

### ISSUE THREAD

**Issue by durch** [nymtech/nym#1436]
Looking into using the [chitchat](https://github.com/quickwit-oss/chitchat/tree/562b5ee7dffd3434928ec8dc82df8033d0d29cf1) crate for this, it seems to give us the secure communication and additional Sync primitives we could use for more complex state management. Good rundown of what it does over over [here](https://quickwit.io/blog/chitchat/). I've come across it while researching [Serf](https://www.serf.io/docs/internals/gossip.html).

**Comment by tommyv1987** [comment]
Closing ticket as part of the chit chat example code which has since been merged.
