### ISSUE TITLE
Add SIGTERM handler to nym-validator-api

### ISSUE THREAD

**Issue by raphael-walther** [nymtech/nym#1437]
systemd sends SIGTERM signal by default and they are ignored by the process nym-validator-api

**Comment by tommyv1987** [comment]
We need to sequence the order of the shut down here on SIGINT:

We're listening for SIGTERM, but we're not acting upon it correctly (i.e. shutting down stuff in correct order) for example:

On V-API shutdown, the error says packet receiver has died! Which is thrown when we attempted to read from, well, packet receiver from another task, implying we should have killed the reader before the sender

**Comment by tommyv1987** [comment]
After testing locally and tunnelling to the validator, then after deploying to QA:
When the validator now stops it does so gracefully in the correct sequence, also whilst monitoring the logs with increased levels of verbosity we could see no panics. Moving to ticket to deployment.
