### ISSUE TITLE
[Issue] Nym-connect status bar menu incoherent option

### ISSUE THREAD

**Issue by rachyandco** [nymtech/nym#1474]
**Describe the issue**
Nym-connect status bar menu shows  `connect` option while already connected. this is incoherent. 

**Expected behaviour**
When Nym-Connet is actually connected, the  `connect` option in the Status bar menu should either greyed-out or replace with a  `disconnect` option.

**Steps to Reproduce**
- Run Nym-Connect
- Connect Nym-Connect
- Check the status bar menu

**Screenshots**
![Screenshot from 2022-07-22 08-55-29](https://user-images.githubusercontent.com/2358699/180382996-abd270c2-45a3-4e03-b83d-900ce656c8df.png)

**Which area of Nym were you using?**
 - Application: Nym-Connect
 - OS: Ubuntu 22.04 with i3
 - Version: https://github.com/nymtech/nym/releases/tag/nym-connect-v1.0.1

**Comment by tommyv1987** [comment]
Issue resolved in later in later release.
