### ISSUE TITLE
NE: Number of filtered results in Light mode isn't properly visible

### ISSUE THREAD

**Issue by benedettadavico** [nymtech/nym#1501]
![paste](https://user-images.githubusercontent.com/46782255/183385768-b91b97e2-9ace-4908-a5ee-2d040d9695e1.png)

**Comment by gala1234** [comment]
For QA:
Branch `1501-contrast-text`

After the fix it looks:
![image](https://user-images.githubusercontent.com/33252067/183414823-3be3f916-3c6d-450d-8eaa-3bbcb25c0c79.png)

![image](https://user-images.githubusercontent.com/33252067/183414852-79c461e1-c620-4f54-8a51-85e52d1c384c.png)
