### ISSUE TITLE
Checking for updated version on startup

### ISSUE THREAD

**Issue by jstuczyn** [nymtech/nym#152]
When starting a mixnode, it should try to check if there's a more recent version available, if so, it should display an appropriate message. Perhaps it could look at this repo's releases?

**Comment by futurechimp** [comment]
At first, we should do this check only for releases with compatible semantic versions. If everybody running mixnodes at version 0.10.x upgrades to 0.11.x (incompatible), the network effectively commits suicide. Semver is a big deal for us, people will need to understand it and upgrade when it's safe to do so.

**Comment by tommyv1987** [comment]
@futurechimp @jstuczyn - bringing this back to life with our intended release plans, what do we want to do with this?

**Comment by tommyv1987** [comment]
Going to close this ticket, based upon some recent in house comments regarding our versioning on binaries etc.
