### ISSUE TITLE
[Issue] Gateway's statistics_service_url is set to 'http://127.0.0.1:8090/', changing it manually doesn't help

### ISSUE THREAD

**Issue by scarletbright** [nymtech/nym#1526]
**Describe the issue**
I initialise NYM Gateway - version 1.0.2 with `--enabled-statistics true` flag
After that there is this value in config.toml:
```
# Domain address of the statistics service
statistics_service_url = 'http://127.0.0.1:8090/'
```

Running Gateway with that statistics URL leads to this error:
```
2022-08-12T09:03:09.623Z ERROR statistics_common::collector  > Statistics not sent: Reqwest error: error sending request for url (http://127.0.0.1:8090//v1/statistic): error trying to connect: tcp connect error: Connection refused (os error 111)
```

After manually changing config.toml with `statistics_service_url = 'https://mainnet-stats.nymte.ch:8090/'` the changes are being ignored by Gateway and it's still trying to connect to http://127.0.0.1:8090/

I'm also using `--enabled-statistics true` to start the gateway

**Expected behaviour**
Gateway sending usage statistics to https://mainnet-stats.nymte.ch

**Which area of Nym were you using?**
 - OS: Ubuntu 22.04.1 LTS
 - Version: nym binary(1.0.2), build from source

**Comment by tommyv1987** [comment]
@scarletbright - can you double-check the commit hash on the build please? we noticed the configuration on the prevoous build commit didn't address the stats-url domain correctly - this should be the correct hash of the binary `c7fdcf0a79d7adfe45e879f152a90e6fa0bfc29e` - if you can let me know how you get on that will be great.

**Comment by scarletbright** [comment]
> @scarletbright - can you double-check the commit hash on the build please? we noticed the configuration on the prevoous build commit didn't address the stats-url domain correctly - this should be the correct hash of the binary `c7fdcf0a79d7adfe45e879f152a90e6fa0bfc29e` - if you can let me know how you get on that will be great.

Yes, after I rebuilt it, the stats started to work, as there is the correct URL in the config. However, one little detail: that URL seems to be 'hardcoded', i.e. changing it manually in the config doesn't affect the gateway behaviour.

**Comment by tommyv1987** [comment]
I'm going to close this ticket, as I believe the latest binary updates would've remedied the situation.
