### ISSUE TITLE
[Issue] Broken x86 dockerimage for validator 

### ISSUE THREAD

**Issue by jstuczyn** [nymtech/nym#1539]
**Describe the issue**
While https://github.com/nymtech/nym/pull/1329 has presumably fixed the build for arm, it broke it for x86. 

**Expected behaviour**
With clean environment I expected `docker-compose up` to build the images and start the 2 validators and make them produce blocks.

**Stack Traces**

It crashes when attempting to copy `libwasmvm`:

```
Step 8/11 : COPY --from=go_builder /go/wasmd/build/nymd /root/nymd
 ---> 1ef8bee6bc53
Step 9/11 : COPY --from=go_builder /go/wasmd/build/libwasmvm*.so /root
When using COPY with more than one source file, the destination must be a directory and end with a /
```

When I removed the `*` it was complaining the file wasn't there. I didn't really have time to investigate it further, so for time being I just locally reverted to before the PR was merged so that I could have started my local setup.

**Steps to Reproduce**
- run an x86 machine
- clone current develop (in my case I tested it on `957cbb45b00553025efe71db27c7b3f2a06e5c68`)
- make sure you don't have any lingering images / containers
- run `docker-compose up`
- stuff fails to build

**Screenshots**
N / A

**Which area of Nym were you using?**
- Application: docker-compose
- OS: Pop!_OS 20.04 LTS x86_64
- Kernel: 5.17.5-76051705-generic 
- docker-compose version 1.29.2, build 5becea4c
- Docker version 20.10.17, build 100c701

**Additional context**
Please provide any other information

**Comment by tommyv1987** [comment]
@jstuczyn - going to close this, as we're going to be working on a global epic for this shortly (finishing off k8s / docker etc)
