### ISSUE TITLE
[Issue] verloc data is not returned after update to 1.0.2 upgrade

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#1549]
**Describe the issue**
verloc data is not returned after update to 1.0.2 upgrade

**Expected behaviour**
Expect Verloc data to be there

**Steps to Reproduce**
Run a 1.0.1 mixnode, wait for verloc data to appear. Upgrade to 1.0.2, rebond, see for results:

https://mixnet.explorers.guru/mixnode/B9mtFTUy3N7R1ARs8MTjinfZ46ifS353HB1rKnLBSS54

http://88.119.175.100:8000/verloc

**Screenshots**
n/a

**Which area of Nym were you using?**
n/a

**Comment by vnpmid** [comment]
maybe using this patch https://patch-diff.githubusercontent.com/raw/nymtech/nym/pull/1581.patch will solve this issue, while waiting developer to fix it or release v1.0.3

**Comment by tommyv1987** [comment]
an outdated ticket closing this.
