### ISSUE TITLE
[Issue] In some cases operator of mixnode bonded with locked tokens can't get its rewards when unbond.

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#1550]
**Describe the issue**
In some cases operator of mixnode bonded with locked tokens can't get its rewards when unbond. Playaround - rebond same node with liquid tokens, then unbonding will drag operator rewards.

**Expected behaviour**
Rewards should get back to node operator

**Steps to Reproduce**
 should be
1) bond mixnode with locked tokens
2) let it get rewards
3) unbond
4) rewards stay in the contract (query_operator_rewards)

*An example:*
1) Mixnode at question:
https://mixnet.explorers.guru/mixnode/9wpTv1TyekdV2JfPXtfAG8q38b6R3iDZhLPpgAQqTYZ4

2) Operator:
https://mixnet.explorers.guru/account/n1m3cn5q2ugfy3qvxxu5tjanqfkekfhwyw4mcmq5

3) Unsuccessful unbond (node was bonded with 40k NYM locked; rewards stay in the contract, not shown as withdrawable as well):
3.1) via nym-wallet 1.0.6 - see 'amount' value in tx is set as 40k by wallet app
https://nym.explorers.guru/transaction/A4BEABC1BD66A215A0BB8FA72412176F52D5B4B98F63750EA574AB01145E158D
3.2) attempt via CLI with amount set exactly as 40k + rewards
https://nym.explorers.guru/transaction/02D21A89215A66D8F71402D764E51E50DAA8F48B20CBC59E5C0E90563339285B

4) Successful unbond (rewards transferred to balance):
https://nym.explorers.guru/transaction/F0EF3C55F5070EBE21E8A3C8A446356C554CDBB9B26824DEC2CE6A3DA65A78FA

** Another case with same story. Same resolution helped withdraw rewards:

https://mixnet.explorers.guru/mixnode/FkpgUpcF7Jq78r9MH2zcHCbkvcYKiKBuiqpEp4yXPeLB

**Which area of Nym were you using?**
windows10
ubuntu 20.04 (validator node env)

**Comment by tommyv1987** [comment]
This is a very outdated ticket. Going to close. As I believe this issue was resolved.
