### ISSUE TITLE
[Issue]delegators has a pending delegation stuck for about 4 hours

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#1552]
**Describe the issue**
On the 08.08.2022 a delegator told us a pending delegation was stuck for about 4 hours
Tx hash https://nym.explorers.guru/transaction/D4EEE6F8C6F6520B82EE14337F2B963581C5E91FF14E017392BD701E7941E2B8

The delegation was in Delegations after 14 PM CEST

So we looked in the grafana board we have and saw that the Accumulated NYM rewards didn't increase in on both node, here's the timeframe ~1030-1600 CEST

https://status.notrustverify.ch/grafana/d/l71MWkX7k/ntv-mixnode?orgId=1&var-timeframe=30.0&var-mixnode=ntv2&viewPanel=19&from=1659896514432&to=1659984212792

We saw that the epoch didn't change too (but not monitoring it) but we monitor (just for tests) the NYM Pool rewards and the NYM didn't depleted between the same time https://snapshots.raintank.io/dashboard/snapshot/2Kuyr5l6y43OLFHjW7eGpMH1hU7dXkTk

**Expected behaviour**
Pending delegation is active after 1 epoch

**Steps to Reproduce**
Delegate on the wallet

**Screenshots**
Mixnodes Accumulated rewards https://status.notrustverify.ch/grafana/d/l71MWkX7k/ntv-mixnode?orgId=1&var-timeframe=30.0&var-mixnode=ntv2&viewPanel=19&from=1659896514432&to=1659984212792

NYM Pool rewards https://snapshots.raintank.io/dashboard/snapshot/2Kuyr5l6y43OLFHjW7eGpMH1hU7dXkTk

**Which area of Nym were you using?**
Mixnode 1.0.2

**Comment by tommyv1987** [comment]
@merve64 
Going to close this ticket as it was all associated with our previous contract, since the contract upgrade this would've resolved the issue.
