### ISSUE TITLE
[Issue] Compound reward make total stake mismatch 

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#1553]
**Describe the issue**
 Compound reward make total stake mismatch for APxUbCmGp4K9qDzvwVADJFNu8S3JV1AJBw7q6bS5KN9E and
4yRfauFzZnejJhG2FACTVQ7UnYEcFUYw3HzXrmuwLMaR

**Expected behaviour**
Normally the total stake should be around 471K

**Steps to Reproduce**
This issue explain everything
https://github.com/nymtech/nym/issues/1433

**Which area of Nym were you using?**
nym-client

**Comment by tommyv1987** [comment]
All erroneous data and values should now be rectified by the mixnet contract upgrade
