### ISSUE TITLE
[Issue]Some mixnodes were not getting rewards despite being in the active set.

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#1554]
**Describe the issue**
Some mixnodes were not getting rewards despite being in the active set.

**Expected behaviour**
Mixnode being active (and ofc having 90+ uptime) should be getting rewards and be present in the message in 'Checkpoint Mixnodes' tx)

**Steps to Reproduce**
https://mixnet.explorers.guru/mixnode/G5XMERsYpP7iyv4xFeWSB6UYgbWupvtt48ixebdLrPBu

I investigated this mixnode with operator. Mixnode was in the active set from 17.05 to 03.07. But was never included in the rewarded set (check mixnode_checkpoint transactions in that period, they don't have this identity key).

Unbonded => bonded on 03.07 and started getting rewards finally.

There were few cases similar to this one.

**Screenshots**
n/a
**Which area of Nym were you using?**
n/a

**Comment by tommyv1987** [comment]
@merve64 putting this down to our previous contract, since the roll out of our new contract we shouldn't be experiencing these issues.

**Comment by roomit-xyz** [comment]
I claim/redeem reward operator, but still not show in wallet available balance. please check asap! https://nym.explorers.guru/transaction/D0FA2374A50CABEB28A1CAC724FA7E3490C32AFE53EDC1233695C187E72750AF
