### ISSUE TITLE
[Issue] lost Internet connection while connecting NymConnect 

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#1555]
**Describe the issue**
When ever  user connect NymConnect on PC windows. his  PC use to lost Internet connection 

**Expected behaviour**
To provide secure connection 

**Steps to Reproduce**
Lunch NymConnect and select any service provider from the drop-down menu and click connect then my PC lost Internet connection 

**Screenshots**
no

**Which area of Nym were you using?**
OS WINDOWS
NymConnect version 1.0.1 x64

**Comment by tommyv1987** [comment]
Haven't been able to reproduce this error on the latest NYM binaries and post the contract update, going to close this ticket.
