### ISSUE TITLE
[Issue] The --help subcommand in nym-client doesn't show description about --gateway flag.

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#1556]
**Describe the issue**
The --help subcommand in nym-client doesn't show description about --gateway flag.

**Expected behaviour**
I I was expecting to get some information about --gateway flag (what argument to pass, what it should do, etc).

**Steps to Reproduce**
use nym-client --help

**Screenshots**
https://i.imgur.com/4ReEjzA.jpeg

**Which area of Nym were you using?**
Ubuntu 20.04.4 LTS
nym-client 1.0.2

**Comment by octol** [comment]
Try `--help` for the `init` or `run` subcommands, something like `nym-client init --help`

**Comment by tommyv1987** [comment]
Going to close this ticket given the advice above.
