### ISSUE TITLE
[Issue] nym-client does not connect to sandbox network

### ISSUE THREAD

**Issue by lambdapioneer** [nymtech/nym#1583]
**Describe the issue**

I am unable to build a nym-client that connects to a sandbox gateway by following the instruction in the documentation.

This issue is similar to #1268. However, the fallback option to v0.12.1 also no longer works.

**Expected behaviour**

Following the instruction from the documentation (https://nymtech.net/docs/stable/run-nym-nodes/build-nym/), I can init my nym client with a sandbox gateway.

**Stack Traces**
 n/a

**Steps to Reproduce**

I built the nym client following the instructions from the documentation:

```shell
$ git checkout tags/nym-binaries-1.0.2
$ NETWORK=sandbox cargo build --release
[...]
Finished release [optimized] target(s) in 2m 20s
```

Then I try to use the client to connect to a gateway from the sandbox test network:

```shell
$ NETWORK=sandbox ./target/release/nym-client init --id test --gateway 6LyPKmAhKC9iX6zK4tUskUdV1C37mg1VSJntfJ78VAxb


      _ __  _   _ _ __ ___
     | '_ \| | | | '_ \ _ \
     | | | | |_| | | | | | |
     |_| |_|\__, |_| |_| |_|
            |___/

             (client - version 1.0.2)

    
Initialising client...
Client "test" was already initialised before! Config information will be overwritten (but keys will be kept)!
Using gateway provided by user, keeping existing keys
thread 'main' panicked at 'no gateway with id 6LyPKmAhKC9iX6zK4tUskUdV1C37mg1VSJntfJ78VAxb exists!', /home/[.. retracted ..]/nym/clients/client-core/src/init.rs:50:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

I observe that the init fails with the warning that the gateway does not exist. However, it does show up in the explorer: https://sandbox-explorer.nymtech.net/network-components/gateways

The same is true for other gateway IDs from the explorer. However, using a gateway id from the mainnet works. This lets me assume that the build step did not respect the `NETWORK` env variable.

**Screenshots**
n/a

**Which area of Nym were you using?**
 - UI: https://sandbox-explorer.nymtech.net/network-components/gateways
 - Application: native client
 - OS: Ubuntu 20.04
 - Version: nym-binary-1.0.2

**Additional context**

I was not able to find any reference where the `NETWORK` env variable is used for the build process. Is perhaps the documentation outdated?

**Comment by lambdapioneer** [comment]
Looks like the `build.rs` which took in the env variable was deleted here:

https://github.com/nymtech/nym/commit/a94272ffd661d8cd168ccae9dd58f4f7c6afe65f#diff-507cf9778a5374134c013bbc29212c4c783e696b72c264e0473baa1ef7082ca7L1-L11

**Comment by tommyv1987** [comment]
@lambdapioneer I'm going to close this ticket as we will be spinning up a new sandbox env in the future. 

For the time being I suggest using mainnet as access to mainnet is free.
