### ISSUE TITLE
[Issue] moving nym-gw from one machine to another

### ISSUE THREAD

**Issue by satman81** [nymtech/nym#1592]
In order to move gw from old machine to new, it's necessary to do 'init' on new machine and then move the keys file (*.pem) doing that gw starts successfully.

next, if I try to connect NR with new gw I am getting this error:
```
 2022-09-05T12:21:39.144Z WARN  nym_client::commands::run > The native-client binary has different version than what is specified in config file! 1.0.2 and 1.0.1
 2022-09-05T12:21:39.144Z INFO  nym_client::commands::run > but they are still semver compatible. However, consider running the `upgrade` command
 2022-09-05T12:21:39.144Z INFO  nym_client::client        > Starting nym client
 2022-09-05T12:21:39.158Z INFO  nym_client::client        > Obtaining initial network topology
 2022-09-05T12:21:39.439Z INFO  nym_client::client        > Starting topology refresher...
 2022-09-05T12:21:39.439Z INFO  nym_client::client        > Starting received messages buffer controller...
thread 'main' panicked at 'could not authenticate and start up the gateway connection: NetworkError(Io(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }))', clients/native/src/client/mod.rs:208:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
nym-client.service: Main process exited, code=killed, status=6/ABRT
nym-client.service: Failed with result 'signal'.
```

I have tried following things:

1. simply restarted the nym-client on NR server
2. did a simple init (without removing .nym directory)
3. did a init by removing .nym directory

in either case I always get above error. 

Important: if i turn off gw on new machine and turn it on on new machine NR immediately connect, i suspect that somewhere the IP address of GW is cached.

**Comment by stakrspace** [comment]
Still the same issue after successful init:

Using gateway: 3ojQD6V7skM1bSXJX7fVQvscjmcgptzdixQEaAha2ixh
Client configuration completed.

Version: 1.1.14
ID: stakr-space
Identity key: 8gRdGTzsDxYzpasRQhsRg59MCgNNhnfag2oFfwwZPXnB
Encryption: DtDrGz7ScVm4o7sN4K3CYUJveYgz7fcXELBVLNDfMS9Y
Gateway ID: 3ojQD6V7skM1bSXJX7fVQvscjmcgptzdixQEaAha2ixh
***
ERROR client_core::client::base_client                                          > Could not authenticate and start up the gateway connection - Authentication failure
Error: FailedToConnectToMixnet { source: ClientCoreError(GatewayClientError(AuthenticationFailure)) [}](url)

**Comment by mmsinclair** [comment]
Hi there, when you move your GW to a new machine with another IP address, you need to change the gateway's details in the Nym directory. Please use the Nym Wallet to change the IP address (look in the bonding tab).
