### ISSUE TITLE
[Feature Request] network-requester dynamic filtering

### ISSUE THREAD

**Issue by parazyd** [nymtech/nym#1595]
Currently, when adding endpoints to `allowed.list`, the network requester does not recognize this
and a restart of the software is required to re-read the file and reinitialize the filters.

A useful feature would be the possibility of dynamically reading the filter list and applying it on-demand.

One (less-performant, but more concise) solution is to read this file on every connection and apply the
filters dynamically for every request.

Another (more-performant, requiring user input) solution is to implement `SIGHUP` signal handling which
would make the software re-read the `allowed.list` file and reapply the new filters.

This feature would, for example, be useful if there is some middleware implemented that sits in front of
network-requester and then based on the protocol/data passing though, decide whether the endpoint
should be added to the whitelist.

**Comment by jstuczyn** [comment]
the network requester should now be automatically reloading the `allowed.list` whenever the file is modified
