### ISSUE TITLE
Traffic from Blockstream not gaining throgh

### ISSUE THREAD

**Issue by iamonuwa** [nymtech/nym#1596]
**Describe the issue**
Listening to traffic from blockstream is failing

**Expected behaviour**
All traffic pass
![880216B7-938F-43A1-80C1-17A59E95CC71](https://user-images.githubusercontent.com/6551094/188631580-0ee9f33e-c690-48b0-b610-56b007247e2e.png)

**Stack Traces**
If there are stack traces or logs, please provide them here...

**Steps to Reproduce**
Steps to reproduce the behaviour, if you're familiar with BDD syntax, please write it in this style:
- Given I was doing X
- And I installed Y
- When I actioned Y
- Then I expect Z

*An example:*
- Given I was setting up a mix-node following the instructions in the docs
- And I successfully bonded my node via the the wallet
- When I went to start my mixnode
- Then I was presented with an error

**Screenshots**
If applicable, add screenshots to help explain your problem...

**Which area of Nym were you using?**
 - UI: [e.g. Websites - network-explorer, nym-website]
 - Application: [e.g Gateway, Client, Wallet]
 - OS: [e.g. Ubuntu 20.x, MacOs Big Sur, Windows 10]
 - Browser: [e.g Chrome (if applicable)]
 - Version: [e.g. nym binary(0.11.0), browser(94.0)]

**Additional context**
Please provide any other information

**Comment by mfahampshire** [comment]
Fixed in PR #1611

**Comment by tommyv1987** [comment]
Closing ticket, issue resolved.
