### ISSUE TITLE
[Feature Request] Display Compound fees as percentage

### ISSUE THREAD

**Issue by MrGoldenpioche** [nymtech/nym#1607]
**Is your request a feature not related to an existing problem? A new feature.**
- I want to see compound fees as percentage.

**Where does the feature fit in the Nym real estate?**
- Application / UI  -> Delegation -> Compound

**What is this solving?**
This feature allows the user to directly choose if compound fees are acceptable now, or it is better to wait more to avoid paying too many fees. 

**Is this an update to packages or libraries?**
If so, please list them. If not, please ignore this section.

**Describe alternatives you've considered**
no one. 

**Additional context**

**Comment by tommyv1987** [comment]
Hi @MrGoldenpioche 

As mentioned in a previous ticket, auto compounding is part of our contract upgrade therefore, removing this requirement/ 

Thank you for your ticket once again, it's appreciated.
