### ISSUE TITLE
Mispelling on main Loopix paper

### ISSUE THREAD

**Issue by irelativism** [nymtech/nym#1657]
After reading some of the mixing related papers, in order to understand what is actually happening on the mixnet, I found a mispelling.

On section 1 so "Introduction" on the paragraph that starts with "For this reason we reexamine and reinvent mix-based"

there are 2 mispellings "reexamine" and "Loopix is resists", the "is" is unecessacery and makes a simple point confusing

![Screenshot_2022-10-03-13-07-22-50_f541918c7893c52dbd1ee5d319333948](https://user-images.githubusercontent.com/75645715/193738390-b69558d9-f739-4f9a-a0e7-629517723f0a.jpg)

Cheers Irelativism

**Comment by tommyv1987** [comment]
@irelativism - I've passed this request onto the research team to amend. I'm going to close this ticket. 

Thank you.

**Comment by irelativism** [comment]
@tommyv1987 No worries my pleasure. Cheers Irelativism
