### ISSUE TITLE
 [Issue] uptime story is not updated 

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#1675]
**Describe the issue**
It seems that the uptime story is not updated anymore, neither with my mixnode instance nor with any other:
https://explorer.nymtech.net/network-components/mixnode/5mbiUjSgdLgh1XA2KH9j1U8YccvMw4EXPvajYLivbvv6

**Expected behaviour**
Updated in a more frequent interval

**Steps to Reproduce**
Just look at the uptime stories of different mixnodes. Last update was 27th of September

*An example:*
- Given I was setting up a mix-node following the instructions in the docs
- And I successfully bonded my node via the the wallet
- When I went to start my mixnode
- Then I was presented with an error

**Screenshots**
no

**Comment by jstuczyn** [comment]
Should get resolved once the new version is pushed out
