### ISSUE TITLE
[Issue] text in the Wallet "Receive" screen is blurred

### ISSUE THREAD

**Issue by rachyandco** [nymtech/nym#1705]
**Describe the issue**
The text in the "Receive" screen is blurred

**Expected behaviour**
The text in the "Receive" screen is sharp like other screens.

**Stack Traces**
no logs

**Steps to Reproduce**
- open wallet
- click on "Receive"
- notice that the text and address is blurred

**Screenshots**
![Screenshot from 2022-10-23 13-54-31](https://user-images.githubusercontent.com/2358699/197390921-d9d17ad1-f4a0-495c-8f3e-9129c464329a.png)

**Which area of Nym were you using?**
 - UI: Wallet
 - Application: Wallet
 - OS: Ubuntu 22.04
 - Version: 1.0.9

**Comment by tommyv1987** [comment]
Closing ticket as seen fixed on laptop in question.
