### ISSUE TITLE
[Issue] wallet creation mnemonic confirmation

### ISSUE THREAD

**Issue by Slowly-Grokking** [nymtech/nym#1738]
**Describe the issue**
When creating a new wallet, and verifying your seed phrase, the application only lets you choose the correct answer.
Allows you to bruteforce the seed phrase by clicking all the words.

**Expected behaviour**
Allow for incorrect seed phrases.

**Which area of Nym were you using?**
-[Appliction] nym-wallet_1.0.9_x64_en-US

Additional:  Furthermore, Telegram and discord are not consistent with the goals of NYM.   Please provide sane options.  Same for github...

**Comment by tommyv1987** [comment]
@Slowly-Grokking 
This is a feature enhancement.

In the application, this is an extra layer / page to ensure sure you write your mnemonic safely.

There’s further screens inside the application that ensure you use the correct mnemonic (password protected option / entering the mnemonic) 

As for product vision, we’re always investigating. and sourcing the best tech to use and align our visions to exclude such services, watch this space. 

Thank you for comments, I have passed these onto the relevant team, but for the time being i'm going to close this ticket.
