### ISSUE TITLE
[Issue] MacOS releases are lacking

### ISSUE THREAD

**Issue by Huge** [nymtech/nym#1755]
I have tested the Wallet release for MacOS, that works well, nym Connect is only available in version 1.0.2 but from a quick look seems fine. The `socks` binary seems would be most versatile but there are no binary releases for MacOS, can you build them too?

**Comment by tommyv1987** [comment]
Hi @Huge 

Whilst we publish our binaries to a linux based distribution, there is no reason for you not to build the project locally on your machine and compile them for use.

Firstly, you will need to have rust installed on your machine and I can recommend using rustup.sh as the installer.

Once you've cloned the nym repository. Inside the root directory folder you can run:

`cargo build --release` and this will produce the relevant binaries in the `nym/target/release` directory for you to use.

Then the nym-socks client will be able to use at your disposal.

if you have any other questions don't hesitate to ask.
