### ISSUE TITLE
[Issue] Network requester run in open proxy mode when args set

### ISSUE THREAD

**Issue by sven-hash** [nymtech/nym#1767]
**Describe the issue**
When running the network requester with `nym-network-requester run enable-statistics` it runs in open-proxy mode

**Expected behaviour**
Not running in open-proxy mode

**Stack Traces**

```
Nov 17 09:27:56 ntv-client nym-network-requester[71354]:
YOU HAVE STARTED IN 'OPEN PROXY' MODE. ANYONE WITH YOUR
CLIENT ADDRESS CAN MAKE REQUESTS FROM YOUR MACHINE. PLEASE QUIT IF YOU DON'T UNDERSTAND WHAT YOU'RE DOING. 
```

**Steps to Reproduce**
Run the network with `nym-network-requester run enable-statistics` or `nym-network-requester run randomValue`

**Screenshots**
If applicable, add screenshots to help explain your problem...

**Which area of Nym were you using?**
 - Application: [Nym network requester]
 - Version: [e.g. nym network requester(1.1.0)]

**Comment by tommyv1987** [comment]
@sven-hash  - we published a new binary to fix this issue last week. This should be available from the release page.

Thank you for notifying us.
