### ISSUE TITLE
Consider rewriting sfw_provider_requests using tokio Framed + Codec

### ISSUE THREAD

**Issue by jstuczyn** [nymtech/nym#181]
Right now I've written custom wrappers for tokio `AsyncRead` and `AsyncWrite` to parse things into provider requests and responses. Apparently the the recommended way of handling this kind of use case is by using `Framed` and `Codec`

They used to be in tokio crate in version 0.1 but were removed in 0.2 due to required tweaks in `AsyncBufRead` trait. Right now it was moved to `tokio_util` crate. (https://docs.rs/tokio-util/0.3.1/tokio_util/codec/struct.Framed.html) So we could use it from there or alternatively wait for tokio 0.3 as from what I've read it's supposed to be brought back to the main crate. 

Personally, I wouldn't touch the current implementation (assuming it works and isn't too inefficient) until we start refactoring everything to make it more idiomic and/or more efficient. However, I wanted to make this issue to remember about it.

**Comment by futurechimp** [comment]
As the sfw-provider is now gone, and the new gateway is using websockets, this one solves itself :)
