### ISSUE TITLE
[Feature Request] Possibility to set a custom gateway and nym client on NymConnect

### ISSUE THREAD

**Issue by sven-hash** [nymtech/nym#1847]
**Is your feature request related to a problem? Please describe.**
It could be useful to give the possibility to set a custom gateway and nym client on NymConnect, in order to extend the custom services supported if some people want to implement or authorize on their gateways/nym-client

**Is your request a feature not related to an existing problem? A new feature.**
Only possible to use the predefined services even if some people authorize other traffic to go trough

**Where does the feature fit in the Nym real estate?**
- NymConnect

**What is this solving?**
Adoption since it could be possible to support more services

**Describe alternatives you've considered**
Proxifier like but nothing is opensource or still developped

**Additional context**
If it's implemented for simplicity, when the user copy paste the nym-client id@gateway the nym connect automatically set the info behind the @ as the gateway

**Comment by octol** [comment]
If I'm not mistaken, this is now possible in nym-connect? To manually set the gateway that is

**Comment by octol** [comment]
I'll close this as completed, please re-open if I misunderstood
