### ISSUE TITLE
WASM version of the Sphinx packet

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#19]

**Comment by futurechimp** [comment]
If we kick out a WASM build of the Nym client, we'll open up private communications to a very large audience, which would be fun. When we get a moment, let's try it and report back here about how it goes. If I remember correctly, @mileschet was also hoping to take a crack at this - let's see who gets there first!

**Comment by jstuczyn** [comment]
Re-opening as we still don't have a full wasm nym-client. What we have now is capabilities of sending sphinx packets from the browser. It still doesn't create background cover traffic streams, etc.

**Comment by futurechimp** [comment]
Heheh I've changed the title to "wasm version of Sphinx packet" to side-step. I think we should take it as a win, and then add specific tickets for all the other needed things: control messages, message receiving, cover traffic etc.

**Comment by jstuczyn** [comment]
Such a tricky way of dealing with the issue : )
