### ISSUE TITLE
Test memo field rendering in Big Dipper v2 and NG explorers for XSS

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#1947]
Use https://xsshunter.com/ to see if Big Dipper v2 and the NG explorers have XSS issues because of the `memo` field in transactions

See `HAL-02` in audit report in https://drive.google.com/drive/folders/1RbBatqL_uA8RQLTdn4vc6cIP2PJvgouf

**Comment by tommyv1987** [comment]
I put a preventative measure in our big digger explorer, will try the v2 shortly.

**Comment by tommyv1987** [comment]
We moved away from using big dipper, no longer an issue
