### ISSUE TITLE
Cluster RPC lite nodes to the wallet traffic

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#1983]
- [x] two VMs running `nyxd` RPC nodes (exoscale) 4 VCPU 8GB
- [x] reverse proxy with nginx
- [x] add HTTPS
- [x] expose API port with nginx (1317)
- [x] expose RPC with nginx (26657)
- [x] monitoring / alerts
  - [x] graph nginx response times (because it easy)
  - [x] investigate prometheus monitoring (cosmos specific)
  - [x] investigate using grafana to display
- [x] add DNS
  - round robin
  - `rpc.nymtech.net`

**Comment by raphael-walther** [comment]
Metrics are collected on the nginx exporter, tendermint and the node exporter. Grafana is installed. There is a dashboard for mainnet validators reverse proxy time.
