### ISSUE TITLE
Have network requester return some kind of response if outbound connection is blocked (i.e. you're trying to access something not on its whitelist) instead of just hanging.

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#1986]
- [x] extra logging on connection failure in the network requester
- [x] investigate if it is possible to get an error response to the calling client (nym-connect) that it explains that the request cannot be made, because it is not in the whitelist
- [x] deploy on nym keybase NR
- [x] deploy on nym electrum NR

**Comment by benedettadavico** [comment]
tested against qa, using keybase with socks5 proxy; the error messages (such as `nym_socks5_client::socks::mixnet_responses > Network requester failed on connection id 18222110756302472710 with error: Domain "api-0.core.keybaseapi.com:443" failed filter check`) are appearing on the socks5 client as expected. 

<img width="1320" alt="Screenshot 2022-08-31 at 18 29 33" src="https://user-images.githubusercontent.com/46782255/187731196-b2e6ba95-51d9-4c4b-9308-a78c0fcff154.png">

**Comment by raphael-walther** [comment]
This should be deployed after next platform release.
