### ISSUE TITLE
Update mixnet TypeScript client methods so that they match current contract

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#1997]
- [x] update methods to match mixnet contract (and make list of missing methods)
- [ ] update methods to match vesting contract (and make list of missing methods)
- [ ] export message types from Rust (in the same way as the wallet)
- [ ] use new messages in execute messages

**Comment by fmtabbara** [comment]
Replaced by
https://github.com/nymtech/nym/issues/2783
https://github.com/nymtech/nym/issues/2784
https://github.com/nymtech/nym/issues/2785
https://github.com/nymtech/nym/issues/2786
