### ISSUE TITLE
Remove all obvious ways socks5/native client can panic/unwrap during init and instead return error types suitable for e.g. `nym-connect`

### ISSUE THREAD

**Issue by octol** [nymtech/nym#2011]
Most of the panics relates to configuration file, especially when using from `nym-connect`.

Examples:
- If we couldn't figure out path to config file, e.g if `$HOME` is not set
- If running `nym-connect` a second time, at which point it should read existing configuration files for gateway data, it should not panic if this fails for whatever reason (missing, corrupt, etc). (this might still panic when running socks5-client from CLI)

**Comment by benedettadavico** [comment]
socks5 doesn't panic anymore, instead it fails gracefully with a message such as: 

<img width="1031" alt="Screenshot 2022-09-01 at 10 07 01" src="https://user-images.githubusercontent.com/46782255/187864848-1009c397-9ab2-42e4-b099-0dcfd611d058.png">
