### ISSUE TITLE
Further improve `nymd_client` starting experience

### ISSUE THREAD

**Issue by jstuczyn** [nymtech/nym#2012]
Initial steps were undertaken in https://github.com/nymtech/nym/pull/1335 However, the said PR didn't really fix the underlying issues as it would have required introducing bunch of breaking changing and as a result spending a lot of time fixing them up. But at some point somebody has to bite the bullet and do it.

The notes I left there that might be relevant to whoever decides to pick this one up:
> 
> - I also dislike this separate, seemingly redundant, separate `network` argument for client creation, but if I were to remove it now, it would chaos a tiny chaos inside the wallet code since it requires that information to figure out where it's connected and I'd rather deal with that issue separately. But my end goal is to obviously get rid of it at some point (or restore it to its previous stateless enum variant that doesn't contain any extra data on it)
> - The same is true for that `None` used in `connect_with_mnemonic`. This is `GasPrice` that I want to eventually moved into `NymNetworkDetails` inside `ValidatorDetails` section since gas price is a per-validator setting. Currently that struct [`NymNetworkDetails`] contains `nymd` url and an optional API url.
> - the requirement of validator address in `connect_with_mnemonic` is still something I need to further ponder about since in theory `NymNetworkDetails` already contain it. But, it contains possible multiple of them, while the client is only going to connect to a single endpoint. I'm not sure what to do here for now, but I left it this way to cause fewer conflicts.

**Comment by tommyv1987** [comment]
im going to close this, this is ancient and alot has changed with the network details
