### ISSUE TITLE
Use native cosmwasm types (`Uint128`, `Decimal`) for reward calculations, instead of the Fixed type we use now to try and fix rounding errors.

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#2018]

**Comment by durch** [comment]
After some considerations and experiments with @jstuczyn we've concluded that we'd gain nothing with this

**Comment by jstuczyn** [comment]
@durch: actually, I've managed to considerably improve precision of calculations making it comparable to `fixed` implementation and I'm leaning toward this native solution.

The benefits of it are: easy and cosmwasm compatible serialisation, fewer dependencies and more straightforward way of getting a `Coin` result that we need to obtain to actually give out the rewards

**Comment by durch** [comment]
Then let’s go for it!
