### ISSUE TITLE
Not sure if shortcut works

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#2038]
Our docs say:

```nyxd tx staking create-validator --amount=10000000unyx --fees=0unyx --pubkey=$(/home/youruser/path/to/nym/binaries/nymd tendermint show-validator) --moniker="whatever you called your validator" --chain-id=nym --commission-rate="0.10" --commission-max-rate="0.20" --commission-max-change-rate="0.01" --min-self-delegation="1" --gas="auto" --gas-adjustment=1.15 --from="KEYCHAIN NAME" --node https://rpc.nyx.nodes.guru:443```

For the `--pubkey=$(/home/youruser/path/to/nym/binaries/nymd tendermint show-validator)` part, I'm not sure if this actually would work in v0.26.0. For me when I do it locally i get the result: 

```{"@type":"/cosmos.crypto.ed25519.PubKey","key":"9YrcpqmVkiKoCEyMayRBWP0d8qIbpOKMRr1C2RLXvhA="}``` 

which I suspect wouldn't work in real life anymore. Perhaps it has changed since an earlier version.

**Comment by tommyv1987** [comment]
This ticket is somewhat outdated now, especially since we're using v43.0 of wasmd, closing this ticket.
