### ISSUE TITLE
Wrong validator binary name in docs

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#2039]
The validator command: 

```nyxd tx staking create-validator --amount=10000000unyx --fees=0unyx --pubkey=$(/home/youruser/path/to/nym/binaries/nymd tendermint show-validator) --moniker="whatever you called your validator" --chain-id=nym --commission-rate="0.10" --commission-max-rate="0.20" --commission-max-change-rate="0.01" --min-self-delegation="1" --gas="auto" --gas-adjustment=1.15 --from="KEYCHAIN NAME" --node https://rpc-1.nyx.nodes.guru:443```

Has  a `path/to/nymd` in it, which will be confusing for most new validator operators (should probably be nyxd)

**Comment by tommyv1987** [comment]
All docs have been moved to the operators guide with updated information, closing the ticket.
