### ISSUE TITLE
Wrong staking denom in validator instructions

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#2040]
On the [validator nodes](https://nymtech.net/docs/stable/run-nym-nodes/nodes/validators) page in docs, there's a command: 

```nyxd tx staking delegate VALOPERADDRESS AMOUNTunym --from="KEYCHAIN NAME" --keyring-backend=os --chain-id=nym --gas="auto" --gas-adjustment=1.15 --fees 5000unyx```

I suspect that the `AMOUNTunym` part is incorrect and should be `unyx`?

**Comment by tommyv1987** [comment]
All docs have been moved to the operators guide with updated information, closing the ticket.
