### ISSUE TITLE
Possibly wrong chain-id in nyx docs needs a fix.

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#2041]
The mainnet validator docs at https://nymtech.net/docs/stable/run-nym-nodes/nodes/validators show the following command for staking in the validator: 

```nyxd tx staking create-validator --amount=10000000unyx --fees=0unyx --pubkey=$(/home/youruser/path/to/nym/binaries/nymd tendermint show-validator) --moniker="whatever you called your validator" --chain-id=nym --commission-rate="0.10" --commission-max-rate="0.20" --commission-max-change-rate="0.01" --min-self-delegation="1" --gas="auto" --gas-adjustment=1.15 --from="KEYCHAIN NAME" --node https://rpc.nyx.nodes.guru:443```

Is it the case that the `chain-id` should be `nyx`?

Also, I think the rpc url has changed to `rpc-1.nyx.node.guru` (with a `-1` added).

**Comment by tommyv1987** [comment]
no longer valid as doc site is situated elsewhere
