### ISSUE TITLE
The experience of starting a client connection to a validator is unnecessarily complex and mysterious. 

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#2045]
The worst part is the generic type parameter `U` - as a coder who wants to connect to a validator: what do I put here? And further: I need to pass in an environment (e.g. mainnet) when starting the client, but then I also need to specify a whole pile of information (contract addresses etc) that should already be known by the system. I can see the argument for leaving those there (maybe we need to change contracts or something), but if they are all options and I can just put `None` in the simple case, it would go a long way toward making a client connection simpler to use.

**Comment by tommyv1987** [comment]
When coding this now, it's super easy, we can use the the following:

```
#[tokio::main]
async fn main() -> anyhow::Result<()> {
    nym_bin_common::logging::setup_logging();

    setup_env(Some("../../../envs/sandbox.env"));

    let sandbox_network = mixnet::NymNetworkDetails::new_from_env();
    let mnemonic = String::from("my super secret mnemonic");
```
