### ISSUE TITLE
Unify coin types across the platform

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#2046]
Provide wrappers for external calls. Right now I need to provide either CosmWasm `Coin` or Cosmos's `CosmoCoin` depending on what kind of transaction I'm doing (CosmWasmor Cosmos native). It seems like we could have automated conversion wrappers (and use them everywhere) at the edges of our own clients, so that when I'm coding inside Nym I never need to think about this. An example of this occurs in the `nymd` client's `send` vs `create_vesting_account` methods.

**Comment by tommyv1987** [comment]
I believe off the top of my head, we have done this. So, I'm going to close this.
