### ISSUE TITLE
Test how many mixnodes the payment system can handle

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#2049]
Take a closer look at `epoch_operations` run at every epoch change by the validator API. It seems like it might blow up due to the amount of work it tells the chain to do in a single block, i.e. reward all mixnodes from the active set, reconcile all delegations and write the rewarded set. The most problematic thing is, in my opinion, the mixnode rewarding as we've attempted this thing in the past and had to settle on rewarding ~50 nodes at once per block otherwise it'd all fail spectacularly

**Comment by tommyv1987** [comment]
We changed the implementation for this in our second version of the mixnet contract and we put it to test and everything was working fine.
