### ISSUE TITLE
Gateway `sign --address` isn't working.

### ISSUE THREAD

**Issue by neacsu** [nymtech/nym#2063]

**Comment by futurechimp** [comment]
This one is not too much of an immediate problem insofar as nodes are now inited with a `--wallet-address` - so the manual signing procedure is not really used. Let's talk about whether we need it anymore, I'm not sure.

**Comment by neacsu** [comment]
> This one is not too much of an immediate problem insofar as nodes are now inited with a `--wallet-address` - so the manual signing procedure is not really used. Let's talk about whether we need it anymore, I'm not sure.

I've already fixed it: https://github.com/nymtech/nym/pull/1004/
