### ISSUE TITLE
Transfer vesting account owner

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#2066]

**Comment by tommyv1987** [comment]
When an account is created, there's an option to pass the owner address and the staking address.

The staking address can perform actions on behalf of the owner address, however, the staking address cant use their wallet-address to get the owner signature for bonding mixnodes or gateways. This is for enhanced security.

The parent / owner_address will have to pass their address when initing a mixnode or gateway 

`./nym-gateway --id owner_address --host 1.2.3.4 --wallet-address wallet_address_of_owner_account`

This will then generate the following:

```
Identity Key: 7BYKhepT7BbDWb5CvozihMzS6BwrvkoBbhxxxx
Sphinx Key: Fz4ZHK5s7qGBjmXZhLH89VaKTNjZz5s8qDKtq5xxxx
Owner Signature: 4B2fmxuMg92cBpVQ9RnvECyvBtPezpQTqYis9gddVedZfdieR4JEo7CxbMpaJ9wuiCHCTwBwRgBJexxxxxxxxxxx
Host: 1.2.3.4 (bind address: 1.2.3.4)
Version: 0.12.1
Mix Port: 1789, Clients port: 9000
Data store is at: "/home/address/.nym/gateways/accountnew/data/db.sqlite"
```

Now, the owner_address account can give the information to the person / who administers the staking account. They can now do:

- bonding mixnodes / gateways
- delegate and undelegate to mixnodes

The staking address will not be able to perform or release tokens from the vesting contract, only the address owner can perform these actions.
