### ISSUE TITLE
Check examples before release

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#2072]
- check examples work

**Comment by mfahampshire** [comment]
* native client 
* [x] js 
* [x] python
* [ ] go 

* webassembly 
* [ ] js 
* [ ] react

**Comment by mfahampshire** [comment]
Some readme fiddling to include on this. 

Currently blocked on waiting for wasm npm package to be updated before checking webassembly stuff

**Comment by mfahampshire** [comment]
Adding tommy to this for QA
