### ISSUE TITLE
Fix network monitor when it stops receiving test packets.

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#2111]
Block until Cosmos releases 1.0

**Comment by tommyv1987** [comment]
Moving this ticket to done. Both @jstuczyn jumped on a call to test this. 

[Ticket] ("https://github.com/nymtech/nym/pull/833/files") - resolves this.

**Testing**
We pointed the work in this PR against the testnet, and ran the gateway pinger, the template.rs provides a descriptive overview of what this implements. The timed execution of this is configurable and is currently set to run on a 15 min schedule. Essentially by running this every 15 mins and pinging the gateways we have good visibility of their states.
