### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2151]
**Describe the issue**
Does not connect for me today for using with Telegram. i get this message "Could not connect
No gateway with id: EEyq16v63aotPBCepxUpCgAojrNasZ6Hk1PjpRyBAdEp". tries several times, nothing changed for me

**Expected behaviour**
expected to connect for further usage 

**Steps to Reproduce**
1. launch NymConnect, 2. choose Telegram on drop down list, 3. click Connect

**Screenshots**
https://prnt.sc/zf5hLMeu9hDE

**Which area of Nym were you using?**
 win10

**Comment by tommyv1987** [comment]
Going to close this issue, as we have since made a lot of improvements on the selection of providers in our UI based applications
