### ISSUE TITLE
[Issue]User undelegate part of his locked NYM tokens,  now he cant see this part in his NYM WALLET

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2152]
**Describe the issue**
User undelegate part of his NYM tokens (about 2 488.57) (they were locked) and now he cant see this part in his NYM WALLET

**Expected behaviour**
1. I'am would be able to see my tokens in NYM WALLET and would be able to delegate them later when they will be unlocked
2. been able to delegate 10% of locked tokens

**Steps to Reproduce**
undelegate locked tokens

**Screenshots**
https://disk.yandex.ru/d/Z7ZbE7qIIfpyBQ

**Additional context**
address n1aet876myrf628am2q3fdjm7mp90ge030t665yk

**Comment by tommyv1987** [comment]
This is strange, @merve64 can you confirm whether the issue still persists in a later version of the wallet?

**Comment by tommyv1987** [comment]
Closing issue
