### ISSUE TITLE
[Issue] NymConnect v.1.1.1 failed to connect with error message: Could not connect

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2154]
**Describe the issue**
NymConnect v.1.1.1 failed to connect with error message: Could not connect

No gateway with id: HyS2UZtZX3kQXdazbdE99DhCjBXjbG61LC9QsmXwbxrU

**Expected behaviour**
He expected NymConnect to switch to connected state. But it just returned to disconnected state with active Connect button.

**Steps to Reproduce**
Try to connect with Telegram chosen as service.

**Screenshots**
Not applicable

**Which area of Nym were you using?**
Win 11, nym-client v1.1.1

**Additional context**
This quickfix works as a charm! https://discord.com/channels/824256813200834580/1011627349919404132/1046458656193003591

**Comment by tommyv1987** [comment]
As mentioned in previous tickets, NC has made improvements on service provider selection, and new iterations have been deployed since. Closing this ticket.
