### ISSUE TITLE
[Issue]Telegram crashed during "Nymconnect mass testing"

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2156]
**Describe the issue**
Telegram crashed during "Nymconnect mass testing"

**Expected behaviour**
User says that he kinda expected this

**Steps to Reproduce**
1. First, after Sudonym counted to 3, I uploaded a small file. It loaded in about 3-4 minutes. While it was loading I was not able to load the next file.

2. Then Sudonim had already allowed a medium file to be uploaded. I was a little late and managed to load it a minute after the start. Surprisingly, the second file loaded faster. Probably because I didn't get into the general flow. The file took about 2 minutes to load.

3. I uploaded the third file as soon as the launch was announced. I expected it to take a very long time to load, but the file managed to load in about 4 minutes.

4. The last file, that huge one, loaded normally at first, but then my Telegram crashed. This approximately happened at 20:23 GMT + 2

**Screenshots**
https://drive.google.com/drive/folders/1MP6ADhGJQmj0wZ-LVP9n2klyeptTiFON

**Which area of Nym were you using?**
Latvia, Riga. Windows 10, RAM 8, x64

**Comment by tommyv1987** [comment]
Thank you for providing this overview, during a mass testing event, we were due to experience some throughput or maxing out on the network. We've collated all the logs during this time and we are continuously improving the performance on the network so we don't encounter this again.
