### ISSUE TITLE
[Issue]After about an hour of NYM Connect working, Telegram stops being online and trying to reconnect (unsuccessfully), messages are not recieved

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2157]
**Describe the issue**
After about an hour of NYM Connect working, Telegram stops being online and trying to reconnect (unsuccessfully), messages are not recieved

**Expected behaviour**
Telegram is working normally, messages are recieved

**Steps to Reproduce**
1. Open Telegram
2. Open NYM Connect
3. Tap the Connection button
4. Wait for an hour   

**Screenshots**
https://imgur.com/a/h0Xnz9Q

**Which area of Nym were you using?**
 Windows, Nym Connect 1.1.0. 64x

**Comment by tommyv1987** [comment]
We've since made a lot more improvements on the selection of network providers in the UI based applications, therefore, I'm going to close this now.
