### ISSUE TITLE
[Issue] When you start the application and try to connect to Telegram, the app does not connect (does not display the proxy address),

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2158]
**Describe the issue**
When you start the application and try to connect to Telegram, the app does not connect (does not display the proxy address), the "Сonnecting" message appears, and then changes to the "Connect" message. If you try to select other applications to connect, try to connect to them, and only after that you try to connect to Telegram, the connection is obtained and the IP address is displayed.

**Expected behaviour**
The app should display message "Connected" and show SOCKS5 Proxy and Port addresses

**Steps to Reproduce**
1. Open the app. 
2. Choose Telegram from cascading menu
3. Tap Connect

**Screenshots**
https://imgur.com/nGQhKdr

**Which area of Nym were you using?**
Windows nym-connect_1.1.1_x64_en-US

**Comment by tommyv1987** [comment]
As mentioned in previous tickets, NC has made improvements on service provider selection, and new iterations have been deployed since. Closing this ticket.
