### ISSUE TITLE
prevailing liquidity - high fees

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2159]
When bridging back NYM from BSC to ETH there is a prevailing liquidity - token mechanics issue. The transaction fees are insane high. (around 100 NYM = self-stake amount for bonding a mixnode). I'm not familiar whats happening on protocol level but this must be too much. Considering that you have to bridge again then with Gravity - this is not looking so professional atm.

https://cbridge.celer.network/56/1/NYM
https://bscscan.com/token/0xdd2612c292431aaa727fe24d1a8afbe4928bbc55
https://etherscan.io/token/0x525a8f6f3ba4752868cde25164382bfbae3990e1?a=0x7510792a3b1969f9307f3845ce88e39578f2bae1

metamask with celer on chrome.

first the celer bridge to work (but after a couple refresh that is solved I guess - all transfers got refunded by now - they don't even appear on the token contract itself - my initial transfer got reversed too from the smart contract .
second, which is the reason im submitting this ticket - is because bridging from bsc to eth should not cost over 100NYM. this must be something not well configured on the protocol level or a liquidity issue. 
another thing which I'm unsure about is why there is no NYM/BNB liquidity pool anywhere on BSC. This basically constrains only ETH to BSC tranfers to be l'art'pour'lart as in not making any sense.
I'm trying to transfer out NYM bsc from OKEX see how that goes to bridge back to eth via celer.

https://imgur.com/a/5cIihI4

mac os mojave as before

User says= not sure how big of a problem you think this is - or if im not seeing something. I think it can be pretty brand damaging. imo NYM dev stuff should be associated with quality and well-testedness - as much as it is possible. I'm really happy to help in user testing more. lmk

**Comment by tommyv1987** [comment]
this is not an issue we can resolve, as far as i'm aware we have never provided any liquidity into any pools, this will be users out in the crypto space who have done. In the future there may come a time where a liquidity pool is set up on the BSC network, but as for now, there are no plans, closing ticket
