### ISSUE TITLE
[Issue] NYMConnect app does not connect 

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2173]
**Describe the issue**
NYMConnect app does not connect 

**Expected behaviour**
He expected to see connected app, proxy address and port

**Steps to Reproduce**
He installed NymConnect, chose Telegram app, click on Connect button and it does not connect in most cases. Very rare He see it connected. He can click 20+ times and it does not connect.

**Screenshots**
https://prnt.sc/wGwRt2a_SlSv

**Which area of Nym were you using?**
win 10, NymConnect was installed from this file - nym-connect_1.1.0_x64_en-US.msi

**Comment by tommyv1987** [comment]
As mentioned in a few other tickets, NC and the service provider list has been improved in recent weeks. I think this issue has stabilised. I'm going to close this ticket, please re-open it if the user is still experiencing issues here.
