### ISSUE TITLE
[Issue]NymConnect doesnt connect on previously (earlier) choosen app 

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2174]
**Describe the issue**
when User launch the NymConnect app and app (Electrum wallet / Keybase / Telegram) is already choosen on NymConnect, NymConnect does not connect for him. But if he chose once again from the drop down list (for example, once again Telegram) it connects. Tried this many times, same result.

**Expected behaviour**
User expects that NymConnect connects on previously (earlier) choosen app 

**Steps to Reproduce**
launch NymConnect app, and click Connect (do not chose your app again, theres already earlier choosen app).

**Screenshots**
https://prnt.sc/7fmcrmdNIUQf

**Which area of Nym were you using?**
win 10, NymConnect

**Comment by tommyv1987** [comment]
As mentioned in previous tickets, NC has made improvements on service provider selection, and new iterations have been deployed since. Closing this ticket.
