### ISSUE TITLE
[Issue] Nym connect only works with vpn

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2176]
**Describe the issue**
1. Nym connect only works with vpn
2. It doesn't always connect the first time
3. After working for 30 minutes or more, the connection is disconnected.
4. There is a permanent connection without a vpn

**Expected behaviour**
expecting a more stable job

**Steps to Reproduce**
1. Opening nym connect
2. I choose telegram
3. Click connect

**Screenshots**
http://prntscr.com/1aJL9F6e4nQj
http://prntscr.com/VgSlP7K7b_23

**Which area of Nym were you using?**
Windows 7 Nym Connect 1.1.0

**Comment by tommyv1987** [comment]
As mentioned in previous tickets, NC has made improvements on service provider selection, and new iterations have been deployed since. Closing this ticket.
