### ISSUE TITLE
[Issue] NymConnect doesn't establish a connection when application first time 

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2177]
**Describe the issue**
NymConnect doesn't establish a connection when application first time (it is important) started  with Telegram enabled as a default application.

**Expected behaviour**
Expected the connection should be established with Telegram selected. Also, NymConnect configuration folder "/home/%USERNAME%/.nym" was not created. 

**Steps to Reproduce**
1. Remove NymConnect configuration folder "/home/%USERNAME%/.nym"
2. Run nym-connect_1.1.0_amd64.AppImage
3. Press "Connect" button
4. I can see "Connecting" for several seconds and then the caption of the button return to "Connect", nothing happend

**Which area of Nym were you using?**
nym-connect_1.1.0_amd64.AppImage
Ubuntu 20.04.5 LTS

Additional info

Console output when press "Connect" button:
$ ./nym-connect_1.1.0_amd64.AppImage 
Starting up...
 2022-11-26T10:07:46.534Z INFO  nym_connect::state > Connecting
 2022-11-26T10:07:46.534Z ERROR nym_connect::state > Failed to initialize: Could initialize without service provider set
 2022-11-26T10:07:47.535Z INFO  nym_connect::state > Disconnected

After user tryed to establish a connection to another application (Keybase or Electrum), NymConnect started connecting to a Telegram as well.

**Comment by tommyv1987** [comment]
As mentioned in previous tickets, NC has made improvements on service provider selection, and new iterations have been deployed since. Closing this ticket.
