### ISSUE TITLE
[Issue] NymConnect GUI is freezing 

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2178]
**Describe the issue**
NymConnect GUI is freezing when select an application from a drop down list of applications when application first time (it is important) started. 

**Expected behaviour**
I expected to select another appliction from a drop down list of applications.

**Steps to Reproduce**
1. Remove NymConnect configuration folder "/home/%USERNAME%/.nym"
2. Run nym-connect_1.1.0_amd64.AppImage
3. Press "Connect" button
4. I can see "Connecting" for several seconds and then the caption of the button return to "Connect", nothing happend (this bug report I sent before)
5. Select another appliction from a drop down list of applications
6. NymConnect GUI is freezing forewer, it is still possible to close an application with a red cross in the right upper corner.

**Screenshots**
https://imgur.com/a/sj0vylY

**Which area of Nym were you using?**
 nym-connect_1.1.0_amd64.AppImage
Ubuntu 20.04.5 LTS

**Additional context**
This is a stable bug, He can always reproduce it.

**Comment by tommyv1987** [comment]
@merve64 can you confirm if the user is still experiencing this issue in later iterations of nym-connect?

**Comment by tommyv1987** [comment]
This is no longer relevant, closing ticket
