### ISSUE TITLE
[Issue]can not connect to nym proxy server user from belarus 

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2179]
**Describe the issue**
A clear and concise description of what the issue is...

**Steps to Reproduce**
no errors just cant connect 

**Screenshots**
https://imgur.com/a/I72h9w2

**Which area of Nym were you using?**
windows 10 last versioin of nym connect

**Comment by tommyv1987** [comment]
@merve64; will need a bit more information on this ticket, where was the user trying to connect in from? what version of nym-connect it was, where did here acquire the version (did they download it from the website or build it from the source code) - if we can confirm this is still an issue, i will dig deeper, in the meantime, im closing the issue, and we can re-open it based upon input
