### ISSUE TITLE
Wallet - global settings part 1 general and advanced 🟢

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2181]

**Comment by MarcinSN** [comment]
- [ ] 3 categories in main wallet settings, General Security Advanced
- [ ] General - version of wallet + option to update if update is available
- [ ] General - theme, dark or light mode switch
- [ ] We are deleting dark/light mode switch from top menu of the wallet
- [ ] Advanced - logs section with option to open logs in separate window

In case of questions contact Marcin



![Image](https://user-images.githubusercontent.com/95295201/207855470-7a679122-96c0-4769-91a8-1b84b3e6c6f0.png)



![Image](https://user-images.githubusercontent.com/95295201/207855500-9d64328e-264d-450e-95dc-4c7332610dd0.png)
