### ISSUE TITLE
Wallet - discrepancies figma vs wallet

### ISSUE THREAD

**Issue by MarcinSN** [nymtech/nym#2183]
![image](https://user-images.githubusercontent.com/95295201/207037832-91369e97-2a8a-4bb2-b4ba-3f4f56a3139f.png)

Talk with Marcin, before you will start doing this, please :)

**Top navigation wallet**
- [ ] Change behaviour and design of dropdown(network selector) same dropdown design we will use in inputs for locked and liquid tokens

**Send**
- [ ] Back button - should be square (global change for back buttons)

**Receive**
- [ ] Alignments + delete text below title

**Accounts**
- [ ] create account - font size in yellow border

**Delegate more**
- [ ] amount input description - fix
- [ ] dropdown states - active, highlighted, disabled (same as network selector)
- [ ] In case of error, not enough funds - highlight of whole input like in bond mixnode form
- [ ] square back button

**Node settings**
- [ ] Alignments
- [ ] Underline of categories - align to words
- [ ] General/Info - Button changes to active after clicking in input - without any changes
- [ ]  General/parameters - lack of tooltips for PM and OC

**Comment by doums** [comment]
After discussion, square back button is **not** to be implemented.
