### ISSUE TITLE
Wallet sign in, create account, mnemonic - discrepancies figma vs wallet

### ISSUE THREAD

**Issue by MarcinSN** [nymtech/nym#2185]
Talk with Marcin, before you will start doing this, please :)

https://www.figma.com/file/KiYKZnWeefSALAe0j2dAPI/Nym-Wallet?node-id=3812%3A55561&t=Tal7KqAZmTYB0xLe-1

**Comment by tommyv1987** [comment]
This ticket is heavily outdated, closing.
