### ISSUE TITLE
[Issue] rewards  were not accrued to user

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2215]
**Describe the issue**
''I delegated my tokens to an active mixnode, I received much less tokens than I should have, for several months they were not accrued to me''

**Expected behaviour**
'''I was expecting to get 500+ coins during delegation, but I only got 200+, because the rewards accrual stopped in a moment for a few months, the node was active all the time, no percentages exceeded. My friend and I delegated. at the same time, he was fine. Also, I have 500 coins were delegated to another node, there is the same accrual stopped and even now it does not go, although the node is active.'''

**Steps to Reproduce**
1. Open the “Nym Wallet”
2. Tap on the “Delegation”
3. I see my delegations and rewards were not accrued

**Screenshots**
https://imgur.com/a/4jk64m4

**Which area of Nym were you using?**
macOS Ventura 13.0, wallet Version 1.0.9

**Additional context**
'''I have two active nodes, I made a compound in one and revards began to accrue, but before that they were not accrued. In. the. second did not make the compound and rewards are not accrued.'''' wallet adress n14mhm3s6aj0j5q96qmk6n00h02ftsyzsklxh88t

**Comment by tommyv1987** [comment]
No response from this. Closing ticket.
