### ISSUE TITLE
NYMCONNECT - new UI + errors

### ISSUE THREAD

**Issue by MarcinSN** [nymtech/nym#2226]
New UI elements
![image](https://user-images.githubusercontent.com/95295201/199473330-76c2e02f-af99-4f57-af44-42e8f49a6888.png)

- Colors, background, txt and elements
- Help in top left corner
- New copy
- New dropdown
- Connection timer
- Bandwith meter(to implement later)

Dropdown after you will select service:
![image](https://user-images.githubusercontent.com/95295201/199474247-602367fa-cca3-4e2b-a2a9-e9db1c52312f.png)

Flow change, after you click yellow button we are showing modal with ip and port values + info to copy them in socks5 proxy settings in users app, after clicking done - user see green connected screen
![image](https://user-images.githubusercontent.com/95295201/199511103-3a60063d-dc62-4e5a-853c-65cd81428d55.png)

Help icon - opens this menu: 
![image](https://user-images.githubusercontent.com/95295201/199475747-dd9b51e9-1a68-4e96-ba17-c80afea4ae17.png)

you have link to docs and 
How to connect guide, where you have to click to see next step

Errors:
![image](https://user-images.githubusercontent.com/95295201/199476363-f79a0c00-b8a6-4121-a4ee-c3dd8a1e7971.png)

Figma file:
![image](https://user-images.githubusercontent.com/95295201/199476668-c5c51a5f-5ede-4873-bf5e-3a0a1e31c1b7.png)

**Comment by tommyv1987** [comment]
No longer needed and closing
