### ISSUE TITLE
[Issue] Out of gas; wallet did not estimate enough fee 33 failed transactions

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2229]
**Describe the issue**

User's compound and reedem are keeping failed **(33 failed transactions)**

https://nym.explorers.guru/account/n1238e2kvp9v9zk0pc5ex4dv6n95z3eayd39wav6

https://nym.explorers.guru/transaction/0F8E972C1885F7FFFFD3D28111CA5989BA3DE01D75A1B461DA708AC558005BFD

**Expected behaviour**
redeem 
see rewards in balance

**Steps to Reproduce**
redeem 
see rewards in balance

**Screenshots**
[If applicable, add screenshots to help explain your problem...](https://we.tl/t-7rI1aljlvh)

**Which area of Nym were you using?**
windows 10 pro, NYM - 1.0.9

**Additional context**
He wants his fee's back

**Comment by tommyv1987** [comment]
this was prior to v2 migration, closing ticket.
