### ISSUE TITLE
Wallet - If a gateway is bonded show gateway settings in the node settings:

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2242]
Settings page for gateway only includes one page to allow changing of the two ports and host. 
![image](https://user-images.githubusercontent.com/95295201/196675173-9aeafb6a-d88c-4d3e-b5c0-12a574357dc0.png)

File: nym wallet/NYM Wallet

**Comment by gala1234** [comment]
Currently the contract doesn't support `UpdateGatewayConfig` and `simulateUpdateMixnodeConfig`. We need core work to connect this functionality, the UI is done.
