### ISSUE TITLE
Wallet - Bonding flow - 3 steps instead of 2, Unbonding flow update

### ISSUE THREAD

**Issue by MarcinSN** [nymtech/nym#2245]
Hey

we are adding one more step to bonding flow.
1 step is the same
2. profit margin and operator cost fields with description
3. Bond amount(we are changing input description from amount to "Bond amount"

screens below, designs in figma file/Nym wallet/Nym wallet page with pirate flag

![image](https://user-images.githubusercontent.com/95295201/194017353-cebb05b1-0199-4238-bdde-ce2bc7b41273.png)

![image](https://user-images.githubusercontent.com/95295201/194017401-b3abb9e2-5f1c-46ed-b5be-64d8a1d21576.png)

![image](https://user-images.githubusercontent.com/95295201/194017431-e63eca6d-485d-4af7-98fb-f61b006f71d6.png)

Unbonding
Instead of modal we will use whole settings container:
![image](https://user-images.githubusercontent.com/95295201/194028411-b76eeb41-8c38-4288-91e4-273d533672a2.png)

![image](https://user-images.githubusercontent.com/95295201/194028431-b84c3666-e8fa-4648-9246-c6786cd7e197.png)

**Comment by tommyv1987** [comment]
i don't believe the wallet on the flow is requiring more development at present therefore closing ticket
