### ISSUE TITLE
[Issue]People redeem their rewards but the rewards don't come to the wallet

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2252]
**Describe the issue**
People redeem their rewards but the rewards don't come to the balance. They can see their rewards in explorer but cant see in wallet. in order to get rewards they should undelegate all their assets.  There were 4 issues and we solve them advicing undelegation. 

Expected behaviour is see assets in wallet when you claim them. 

**Screenshots**
https://ibb.co/SRrWdfr

**Which area of Nym were you using?**
 Nym wallet Version 1.0.9

**Additional context**
EFB0E56833756F48F6A40D2C9426CFC7EBB622B57E0DDE8007A98DD26FB5C704
D25857F8A10BB73C2AA1C7231090AD3D33F99A5AC6AF18FB9A56187DF6E90B89
B0EC26D1D48D605F66116E009A96A9F1C0BDE88A079C2FB4ABC30BB80D170D00
D8093FAF871D3B5AE3D9A648E3F6A0853CD62D531F4A3A400CED6D4D0FA08E7F
25925DBE06991971E71408948E17764EC732F1471CC48147F1F7E29198245BC9
First 3 claim reward didnt arrive
last 2 undelegate didnt arrive

**Comment by tommyv1987** [comment]
Putting this issue down to our first version of the mixnet contract, since we migrated to a new version this issue doesn't persist anymore. Closing the ticket.
