### ISSUE TITLE
Wallet: Input field border missing after click

### ISSUE THREAD

**Issue by benedettadavico** [nymtech/nym#2256]
Part of the border disappears when clicking on the input field, and then comes back when clicking elsewhere. 
See two examples: 

https://user-images.githubusercontent.com/46782255/190094427-43dfcbfa-cd87-4f06-ba13-5865b00c56f9.mov

https://user-images.githubusercontent.com/46782255/190126947-064f7d54-8d9d-42ea-b91f-2fce6ff24d6e.mov

**Comment by gala1234** [comment]
I'm trying to link the PR, but It's not working

PR https://github.com/nymtech/nym/pull/1733
Branch `417-inputs-label`
