### ISSUE TITLE
NE - change "Self" with raw Bond in below screen:

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2260]
The title should be `Bond`, meaning the values need to be in NYM instead of a percentage.
And add this tooltip: "Node operator's share of stake"
<img width="1321" alt="Screenshot 2022-09-13 at 12 20 38" src="https://user-images.githubusercontent.com/31625607/189888559-8d0fce90-ca5a-436c-b01b-9f1400901bad.png">

**Comment by gala1234** [comment]
For QA:
Branch `413-ne-content`
Staging URL: https://network-explorer-413-ne-content.ci.nymte.ch/
