### ISSUE TITLE
Wallet: create delegation screen first step & NE: table toolbar ui update

### ISSUE THREAD

**Issue by MarcinSN** [nymtech/nym#2264]
This ticket require changes on the Network Explorer and the Wallet.

First step delegation screen - before any delegation user should see this screen with link to NYM explorer and explanation why they should use filters
![image](https://user-images.githubusercontent.com/95295201/190599172-1836e17e-25d6-40ca-9763-a9695b7e4166.png)

_**Network Explorer:**_
Explorer filters currently are not visible enough

so let's change link to button in explorer and add copy to delegation screen that user for optimal search results should use advanced filters
![image](https://user-images.githubusercontent.com/95295201/190108937-167063fb-5b92-47c1-90d9-302d93f592af.png)
mobile
![image](https://user-images.githubusercontent.com/95295201/190361953-999689bd-6b5f-454c-ac66-20d6c8adee28.png)

_**Wallet:**_
Create this first step when users doesn't have delegations

![image](https://user-images.githubusercontent.com/95295201/190108835-3f3c6ba1-8740-47cb-97d3-9e090c22ddc0.png)

Figma file location:
![image](https://user-images.githubusercontent.com/95295201/190108578-75c9d530-7586-4b45-b2cd-fa25690c7900.png)

@benedettadavico I've been having a look with Marcin on the ui tickets done to fix Figma differences and he found one missing thing, that wasn't included on any of our tickets, and I'm going to use this one to include the change. Is the mnemonic on the signup, below screenshot is how it's looking currently on develop.

![image](https://user-images.githubusercontent.com/33252067/191499746-4ef73d1c-2fee-4ecb-83c0-e38703e48364.png)

**Comment by gala1234** [comment]
@MarcinSN do you have a mobile view for this explorer change, please?

I did this, but I would like your opinion:

<img width="240" alt="image" src="https://user-images.githubusercontent.com/33252067/190175861-07154dc7-243a-4e9f-9314-b312fb5903f7.png">

You can have a look here: https://network-explorer-409-ne-filters-info.ci.nymte.ch/network-components/mixnodes


Before changes it looks: 
<img width="611" alt="image" src="https://user-images.githubusercontent.com/33252067/190184505-9e5524d0-3e81-48c3-a8a2-d96dd71fcc4c.png">

**Comment by gala1234** [comment]
I'm pasting Marcin response with mobile design:
![paste (1)](https://user-images.githubusercontent.com/33252067/190405207-501f4a9c-740a-4805-97a5-32b7cbc0ff1a.png)

**Comment by benedettadavico** [comment]
The delegation screen on the wallet and the explorer filters are looking good 
<img width="1441" alt="image" src="https://user-images.githubusercontent.com/46782255/191536647-6b5af43a-3fa5-45ef-ac1b-41b47a8e4392.png">

And the new account screen on the wallet also matches the comment above
