### ISSUE TITLE
Website - fix the issue on "Get Involved" page where Shipyard icon shows smaller on the large screen:

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2268]
<img width="1391" alt="Screenshot 2022-09-08 at 16 48 24" src="https://user-images.githubusercontent.com/31625607/189167830-ada97266-d4cc-4320-8340-1075bd6c82f8.png">

**Comment by raphael-walther** [comment]
Cannot reproduce the issue on a 1920x1080 screen. 

@jessgess  Do you still have the issue ?
