### ISSUE TITLE
Wallet - global settings part 2 Security - Add&Change Password 🟢

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2275]
General Settings -> Security -> Change password or create a password 

Depending on whether a password already exists on the machine or not, one of the below flows will be shown:
 
1) Change password 
2) Create a new password   
 

![Image](https://user-images.githubusercontent.com/95295201/232062652-f548dda1-3b1c-4c55-bf49-3e11601cc5c9.png)

![Image](https://user-images.githubusercontent.com/95295201/232062724-e45c8233-7bd3-4c65-8820-c3dec6581be9.png)

Figma file: NYM wallet with pirate flag - section: General settings

**Comment by roughprada** [comment]
The paragraphs on the left side are much shorter than the recommended readability standards (8 words) and can be hard to read. If I need to add this to a bug ticket or need clarification, please reach out
