### ISSUE TITLE
[Issue]  it does not connect to the service in the first time  when you run the program

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2280]
**Describe the issue**
The first time you run the program, it does not connect to the service. The button returns to the "Connect" state. To be able to use the program, just switch to any other service. Now you can work normally with the program and switch/connect to any service. This is similar to the second step to get started - switching a service in the menu

**Expected behaviour**
Expected status Connected

**Steps to Reproduce**
0. Close Nym Connect if it running
1. Click on Nym Connect shortcut or .exe file to start
2. Click Connect (do not change current option), not matter which service
3. Done

**Screenshots**
https://tenor.com/view/cutie-cat-chan-no-unhappy-gif-15998785

**Which area of Nym were you using?**
Windows 10 Pro, Version 21H2
Nym Connect 1.0.8

**Comment by tommyv1987** [comment]
Closing this ticket, as this ticket is really outdated, a lot of iteration of NC have been released which have addressed a lot of these issues.
