### ISSUE TITLE
[Issue] Your tokens are not delegated to any mixnode, you have no rewards for delegation, warning- no tokens to delegate.

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2281]
**Describe the issue**
For a few days, people have been encountering these few problems:
1. Tokens are not delegated to any mixnode.
2. Some long-delegated wallets have no rewards to reedem.
3. No tokens to delegate alert when you want to delegate tokens even though there are tokens in the wallet.
4. 

**Expected behaviour**
1. Open wallet see rewards and reedem if you want
2. Open the wallet and see the mixnode you delegated. Redeem rewards if you want.
3. Select mixnode to delegate tokens, delegate

**Screenshots**
https://disk.yandex.ru/i/vFoBkaQW5rrBUw
https://disk.yandex.ru/i/OTpcQ-UnLSzeBA
https://disk.yandex.ru/i/1B4gXdMmciHCww
/var/folders/wg/nbdkty6d4v59pfqjgbt5t8bm0000gn/T/IMAGE 2022-09-01 14:48:08.jpg

**Which area of Nym were you using?**
Nym wallet version 1.0.8

**Comment by tommyv1987** [comment]
I believe a lot of these issue will now be resolved with the compounding we ran on tuesday, we will be altering a few things inside the wallet shortly which will fully display the accumulated rewards for any mixnode as the gas cost on querying to get rewards was quite high. We don't think this issue will persist in the next day or two.
