### ISSUE TITLE
[Issue] Wallet produces a non descriptive error when using bad address format in transaction

### ISSUE THREAD

**Issue by rachyandco** [nymtech/nym#2282]
**Describe the issue**
When using the wallet on mainnet, creating a transaction with a testnet address (nymt) as recipient is failing as expected BUT in a non descriptive way.

**Expected behaviour**
The wallet, when being used in Mainnet should explicitly refuse to process testnet addresses when creating a transaction

**Stack Traces**

```
 2022-09-01T08:12:49.112Z INFO  nym_wallet::operations::mixnet::send     > >>> Send: display_amount = 1 nym, base_amount = 1000000unym, from = n104glfyskvrnx9u4upgqnz67axma72m5we3qaj4, to = nymt1jaj8fz7gd72tmg5fq0mdqx9j07j5w4f2q3tnrs, fee = None
```

**Steps to Reproduce**
- open Wallet on mainnet 
- send 1 NYM to nymt1jaj8fz7gd72tmg5fq0mdqx9j07j5w4f2q3tnrs

**Screenshots**

![Screenshot from 2022-09-01 10-26-16](https://user-images.githubusercontent.com/2358699/187868736-a0b08f68-0c63-4f73-84c0-44b1960c5091.png)

**Which area of Nym were you using?**
 - Application: Wallet
 - OS: Ubuntu 22.04
 - Version: 1.0.8

**Comment by tommyv1987** [comment]
For each one of these @rachyandco  - we've gone through updating the wallet to give more reflective error messaging. I believe this one to be fixed now. So I'm closing this ticket. :)
