### ISSUE TITLE
[Issue]Oh no! Something went wrong... while trying undelegate

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2283]
**Describe the issue**
When user tried to undelegated NYM token, an error appeared: "Oh no! Something went wrong..."

**Expected behaviour**
Undelegate tokens

**Steps to Reproduce**
Delegation -> Undelegate

**Screenshots**
https://i.imgur.com/NS98qgE.jpg

https://i.imgur.com/kBwtuG4.jpg

**Which area of Nym were you using?**
OS: Windows 10
Nym Wallet Version 1.0.8

**Comment by sandglasstu** [comment]
I tried again today and still report the same error, but here it shows success,It didn't actually work. BTW my balance of more than 200 is enough
https://nym.explorers.guru/account/n1ce7uywfla4avzyrkkfvx0m6x2pygxtfppvg3wa
![image](https://user-images.githubusercontent.com/12029190/187824870-766d8de4-ce68-4c5a-b3fe-274ae091a51d.png)

**Comment by tommyv1987** [comment]
Hi @sandglasstu, does this issue still remain I can see you had some success in your recent activity of events?

**Comment by benedettadavico** [comment]
Based on logs above it seems the issue is no longer happening.
