### ISSUE TITLE
[Issue] Abci query failed with code 18 

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2284]
**Describe the issue**
Trying to unbond wallet and getting either message 

1. Abci query failed with code 18 - account sequence mismatch, expected 5, got 4: incorrect account sequence: invalid request
or 
2. "Unbond successful" message and no tx hash (i.e. not found)

Previously also had error when trying to Bond with message "Abci query failed with code 18 - account sequence mismatch, expected 3, got 2: incorrect account sequence: invalid request"

**Expected behaviour**
These actions are related to server migration from Hetzner, bond had a new IP address. Eventually managed to bond back again to the old server, but cannot unbond this wallet now. Network fee for every operation is taken regardless.
I'm using 1.0.8 wallet version and have >3 NYM for fee.

**Steps to Reproduce**
Bond / unbond function. I have done this action many times and never got this problem.

**Screenshots**
https://ibb.co/DwsDkGL
https://ibb.co/9YQzXtf

**Which area of Nym were you using?**
2 / 4 / 40

**Comment by tommyv1987** [comment]
I believe this issue was caused due to some intermittent network connectivity. We have since rolled out some new light nodes to relieve the strain on some validators so everything is in sync and functioning correctly. Going to close this ticket now.
