### ISSUE TITLE
[Issue]  insufficient fund while trying to delegate

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2285]
**Describe the issue**
Nym token were transferred from kraken to NYM wallet. Tried to delegate but was saying insufficient fund. Delegation amount was reduced by about 20% and it went through,  but  attempt to delegate the remaining balance keep saying insufficient funds and sometimes the successfully delegated token   doesn't appear on lists of delegations, it goes off and on. 
And wallet balance occasionally keep changing to the old balance before the kraken transfer 

**Expected behaviour**
Expected delegation to be successful as there is enough balance. And also wallet balance shouldn't occasionally change to old balance before token was successfully transferred from kraken into the wallet 

**Steps to Reproduce**
Transfer nym token from kraken to NYM wallet, Click on delegation, select delegate token fill in amount to delegate, it shows you insufficient funds, reduce delegation amount, if it goes through, try to delegate the remaining balance, it shows you insufficient funds, sometimes it allows you to successfully submit request and then you get insufficient fund

**Screenshots**
https://drive.google.com/file/d/1J-SRkFyxtRgE-zHBcNzkU9pX308SumWt/view?usp=drivesdk

**Which area of Nym were you using?**
Windows 10, nym wallet 1.0.8

**Additional context**
As you can see from the screen shot, it shows not enough funds even though there is enough balance to cover the delegation amount. And the initially successful delegation doesn't appear on the list of delegations

**Comment by benedettadavico** [comment]
@merve64 This should be fixed as part of the universal compound run
