### ISSUE TITLE
[Issue] not receiving rewards 

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2290]
**Describe the issue**
A delegator send this
this morning between 11am and noon, He made Redeem on NTV1 and NTV2 and he put the rewards on NTV3 by making delegate more. Since then he have had 0 rewards on NTV1 and NTV2, on NTV3 (mixnode where delegator has been done) rewards are increasing

so 3 epochs without rewards on NTV1 and NTV2 for my delegations

**Expected behaviour**
Rewards continue to increasing on NTV1 and 2

**Steps to Reproduce**
Redeem from a mixnode and delegate more to another one

Redeem ntv1
redeem ntv2
delegate more ntv3
compound ntv3

**Screenshots**
https://i.imgur.com/CN9Q3CK.png

**Which area of Nym were you using?**
nym-wallet 1.0.8

**Additional context**
Reedem txs
https://nym.explorers.guru/transaction/E0919231516811DEC3037BD6556ACAD13D831E07A924762D68364D6DDD8FB9AE
https://nym.explorers.guru/transaction/686E6E1BB458FB9DC3F5B25CB6556166E82FA941E908E697850B945F9D4565DC

Delegate more tx
https://nym.explorers.guru/transaction/55F3B6739B09FB1E5368DA00F6442C2D506F0FD4FE2F7F8D56D86C5659D220E0

**Comment by tommyv1987** [comment]
@merve64  - how was this user checking to see if they got rewards? Inside the wallet?

**Comment by sven-hash** [comment]
> @merve64 - how was this user checking to see if they got rewards? Inside the wallet?

Yes it was inside the wallet, checking it the rewards was increasing from hour to hour

**Comment by tommyv1987** [comment]
Was the reward balance showing in the wallet, and was the balance delegated = 14.8nym? 

Can you confirm that the balance was showing in the reward it was stuck out with `-` sign?

**Comment by tommyv1987** [comment]
Also, I just checked delegation to the mixnode identity:

```

"sender":"n19um6hy8ghp5e63cnfy36msj2cqd24uu4eefp85"
"contract":"n14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9sjyvg3g"
"msg":{
"delegate_to_mixnode":{
"mix_identity":"B63yxdf92RdjwEeUFouxU4x5gRpWXKorT51px8EbpQvJ"
}
}
"funds":[
0:{
"denom":"unym"
"amount":"14870000"
}
]
```

I can't see this delegation bound to the mixnode ->
`The delegator-rewards is: 0uNYM for account id n19um6hy8ghp5e63cnfy36msj2cqd24uu4eefp85 for ID B63yxdf92RdjwEeUFouxU4x5gRpWXKorT51px8EbpQvJ` 

As per the delegation stated here:
https://nym.explorers.guru/transaction/55F3B6739B09FB1E5368DA00F6442C2D506F0FD4FE2F7F8D56D86C5659D220E0

**Comment by sven-hash** [comment]
If think it solved by now. The delegator didn't come back to me so you can close the issue

Thanks for your support

**Comment by tommyv1987** [comment]
Closing the issue based upon the above.
