### ISSUE TITLE
[Issue]displaying the staking rewards in the wallet (it's different than in the explorer) 

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2291]
**Describe the issue**
there are problems with displaying the staking rewards in the wallet (it's different than in the explorer) and problems with redeeming or compounding rewards (comissions for transactions are being taken each time you try but rewards dont go anywhere)

**Expected behaviour**
matching balances of rewards in the wallet and in the explorer
no errors during redeeming or compounding rewards

**Steps to Reproduce**
go to delegation, try to redeem or compound rewards and you see the error "oh no.. something went wrong"
and also the balance of staking rewards in the wallet is different than the balance in the explorer

**Screenshots**
https://imgur.com/a/xZMcGf8

**Which area of Nym were you using?**
windows10. nym wallet Version 1.0.8

**Comment by tommyv1987** [comment]
I believe to be an issue with our first mixnet contract, since we migrated to a new version, this issue shouldn't persist anymore. Closing the issue.
