### ISSUE TITLE
[Issue] something went wrong while trying to make a transaction

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2292]
**Describe the issue**
When trying to make a transaction but the remaining balance is insufficient to cover the fee of the transaction, the wallet shows the error message "oh no, something went wrong" for one user.
**Expected behaviour**
the error message should say something along the lines of "insufficient balance" or similar. 

**Steps to Reproduce**
initiate transaction where the remaining balance does not cover the transaction fee. 

**Screenshots**
no
**Which area of Nym were you using?**
any

**Comment by tommyv1987** [comment]
As mentioned in a few other tickets, we retrospectively went through errors provided by the wallet, and have updated them accordingly to be more user friendly. Closing ticket
