### ISSUE TITLE
[Issue] deposit transaction errors on the NYM wallet

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2294]
**Describe the issue**
it seems that the deposit transaction on the NYM app has quite a few errors including the display aspect. When the user makes a deposit transaction, even though the app says transaction failed, the transaction on the smart contract is still recorded.

Reporter tried 5 transactions and 4/5 transactions have the same problem. this will cause confusion for users
Confirmation for one of the transactions:
https://nym.explorers.guru/transaction/29931F2166E27E9B65F4E72592233AF78300C0095449B63EDB0DD969FD07D141

**Screenshots**
![IMAGE 2022-08-23 17:42:29](https://user-images.githubusercontent.com/111695676/186187954-e1e0b3c0-f3d5-4c61-9563-28fb3dee45f1.jpg)

**Which area of Nym were you using?**
nym wallet

**Comment by tommyv1987** [comment]
The wallet has had multiple releases since the first report of this issue, and this is no longer an issue. Closing ticket.
