### ISSUE TITLE
[Issue] redelegate issue

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2296]
**Describe the issue**
People have a problem when thew claim rewards and then stop receiving them
that is, in order to continue working,  they need to undelegate them and then delegate them again, it is quite inconvenient when they want to redelegate them every day

**Expected behaviour**
After point 11 i was expecting rewards in rewards column within 1-2 hours but i am not getting them

**Steps to Reproduce**
1. Open nym wallet
2. Click on Delegation
3. Click on Delegate button 
4. set Node identity key and Amount
5. Click on Delegate stake
6. Wait about 1 hour or 2 (you need get some reward)
7. On delegation page find your active delegation 
8. Click on 3 points 
9. Click on Redeem(Tranfer your rewards to your balance)
10. Click on Redeem rewards(wair for confirmation)
11. Click on finish
12. Get rewards
12. Wait for new rewards(but you not get new rewards from active delegation)

*An example:*
- Given I was setting up a mix-node following the instructions in the docs
- And I successfully bonded my node via the the wallet
- When I went to start my mixnode
- Then I was presented with an error

**Screenshots**
https://ibb.co/4JMbD8S
https://ibb.co/mXWKCm3
https://ibb.co/ZfS8nHF
https://ibb.co/8gKqMQg

**Which area of Nym were you using?**
Ubuntu 20.04 LTS 
Nym Wallet 1.0.7 version

**Comment by benedettadavico** [comment]
@merve64 This should be fixed as part of the universal compound run

**Comment by benedettadavico** [comment]
Rewards are generated as seen here when querying it:
The delegator-rewards is: 2 NYM for account id n17uldedg77lvc8hk2t7w7ut2909qgn55zmnx0aj for ID 2j6ZSZ4ASyYCFt86s9k3xUEnPAvPZyBeMAu9uy8aZ4hy
This may have been affected by the wallet not rendering it, as well as the small stake size taking a longer time for rewards to display
