### ISSUE TITLE
[Issue] The rewards are not accumulating after "redeem" rewards.

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2297]
**Describe the issue**
The rewards are not accumulating after "redeem" rewards.

**Expected behaviour**
Generate reward after redeeming

**Steps to Reproduce**
1. Delegate NYM to any Mix Node (I was delegating to 75GFGk5BJ1KsokEob8cFLB7331Tbz3gQR4wSTAJD8tZb and 8brpoiMioxWGUrkYhhdu4b9K7XV46LuabgBFZWLMR8T5)
2. Redeem rewards after it has some rewards
3. The reward won't accumulate anymore

**Screenshots**
https://imgur.com/VNYMHBr
I delegate the reward to Node 8brpoiMioxWGUrkYhhdu4b9K7XV46LuabgBFZWLMR8T5, and redeem rewards on around Aug 8, 2022, and delegate the redeemed rewards to this node again, and only the second delegation (redeemed reward on Aug 8) is generating yield, and the first delegation is not generating yield anymore. 

**Which area of Nym were you using?**
macOS, nym-client 1.0.7

**Comment by benedettadavico** [comment]
@merve64 This should be fixed as part of the universal compound run.

**Comment by benedettadavico** [comment]
There is no account address provided, we can't investigate further until this is provided
