### ISSUE TITLE
[Issue] iquid+locked tokens delegated from same wallet to same node compounding only takes one of two types of rewards -

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2300]
**Describe the issue**
In case of liquid+locked tokens delegated from same wallet to same node: 

Compounding only takes one of two types of rewards - presumable only locked ones.

**Expected behaviour**
Compound button should generate transactions and execute compound both in vesting contract and in mixnet contract

**Steps to Reproduce**
1. Delegate locked tokens to a mixnode
2. Delegate liquid tokens to a mixnode
3. Wait for rewards to accumulate
4. Try to compound. It should only compound part of rewards

**Screenshots**
n/a

**Which area of Nym were you using?**
windows 10

**Comment by benedettadavico** [comment]
@merve64 This should be resolved as a part of the universal compounding fix. All behaviour around delegations should behave as expected

**Comment by tommyv1987** [comment]
Closing issue based upon the previous comment.
