### ISSUE TITLE
[Issue]. Delegation rewards not shown properly in the wallet 

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2301]
**Describe the issue**
Delegation rewards not shown properly in the wallet if delegation consists of both locked and unlocked tokens.
In such case only locked token rewards are displayed.

**Expected behaviour**
Delegation rewards should be a sum of liquid and locked (query_delegator_rewards with simple payload and with 'proxy' payload).

**Steps to Reproduce**
1. Delegate locked tokens to a mixnode
2. Delegate liquid tokens to a mixnode
3. Wait for rewards to accumulate
4. Check delegation rewards in the nym-wallet (1.0.6)
5. Check delegation rewards in the mixnet.explorers.guru
See the difference (for example if you have 1000 NYM Locked and 1000 NYM liquid delegated, difference between nym wallet and explorer rewards will be x2)

**Screenshots**
n/a

**Which area of Nym were you using?**
windows 10

**Comment by benedettadavico** [comment]
@merve64 This should be resolved as a part of the universal compounding. All behaviour around delegations should behave as expected

**Comment by tommyv1987** [comment]
Closing based upon previous comment.
