### ISSUE TITLE
[Issue] get_pending_delegation_events

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2302]
**Describe the issue**
querying mixnet contract with `get_pending_delegation_events` does not return pending event (though nym-wallet shows it)

**Expected behaviour**
Expect to see pending delegation and undelegation as it worked previously (april, may, june 2022)

**Steps to Reproduce**
1) delegate tokens
2.1) check query with payload `get_pending_delegation_events`
2.2) check pending delegations in nym-wallet
3) undelegate tokens
4.1) check query with paylod `get_pending_delegation_events`
4.2) check pending undelegations in nym-wallet

**Screenshots**
n/a

**Which area of Nym were you using?**
ubuntu 20.04 validator node, rpc node envs
windows 10 latest updates

**Comment by benedettadavico** [comment]
@merve64  This should be resolved as a part of the universal compounding. All behaviour around delegations should behave as expected

**Comment by tommyv1987** [comment]
Closing based upon the previous comment
