### ISSUE TITLE
[Issue]can't use Nym Connect proxy on Electrum wallet

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2303]
**Describe the issue**
User can't use Nym Connect proxy on Electrum wallet

**Expected behaviour**
Tools > Network > Overview show "Connected to xx nodes"

**Steps to Reproduce**
1.  On Nym Connect: Choose Nym Electrum Service Provider, press Connect
2. On Electrum wallet. Go to Tools > Network > Proxy. Tick Use proxy. Fill 127.0.0.1, port: 1080, leave other fields empty. Press Close.
3. Electrum wallet Network show red light at the bottom and "Not connected" status. Tools > Network > Overview show "Not connected" too

**Screenshots**
[If applicable, add screenshots to help explain your problem...](https://prnt.sc/m2AKBpZW58Fo
https://prnt.sc/eaEccHJNDg9S
https://prnt.sc/7OiNrYNBjRGJ
https://prnt.sc/34Z4_Kd4klNr
https://prnt.sc/HSISriJIPN6g)

**Which area of Nym were you using?**
 nym-connect-v1.0.1
electrum-4.2.2-portable

Processor	Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz   3.79 GHz
Installed RAM	16,0 GB (15,9 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Pro
Version	21H2
Installed on	‎11/‎04/‎2021
OS build	19044.1826
Experience	Windows Feature Experience Pack 120.2212.4180.0

**Comment by tommyv1987** [comment]
As mentioned in previous tickets, NC has made improvements on service provider selection, and new iterations have been deployed since. Closing this ticket.
