### ISSUE TITLE
[Issue] how to spoof delegations using the current version of the NYM wallet

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2304]
**Describe the issue**
It is possible to spoof delegations using the current version of the NYM wallet 1.0.7 and your own mixnode to increase operator rewards

**Expected behaviour**
Compounding should add the delegator's rewards into the the delegated stake, not count it double!

**Steps to Reproduce**
1) Start your own mixnode
2) Bond the node and delegate some stake (the more NYM the higher the effect). Let's use 50k NYM for this example
3) Wait one epoch until you see delegation rewards
4) Use "compound" in the wallet to compound rewards. This will end up in your stake being counted double! So 50k + 50k + real rewards.
5) Repeat step 4 until your node reaches saturation
6) Now you can undelegate and start over from step 1 with the next node

You node will still created operator's rewards as if the node was fully saturated with real stake even there are 0 delegations.

**Screenshots**
https://imgur.com/a/HHnGOIk

**Which area of Nym were you using?**
NYM wallet on MacOS - not sure it's relevant, seems more like a bug in the contract to me, but I could be wrong.

**Comment by tommyv1987** [comment]
This is not an issue, and definitely not reproducible in later versions of the wallet. Closing ticket.
