### ISSUE TITLE
[Issue]The default gateway port is incorrect on the Nym wallet.

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2305]
**Describe the issue**
The default gateway port is incorrect on the Nym wallet. Since it only shows up when checking advanced options, it's desirable to change the default websocket port to 9000 in the wallet UI

**Expected behaviour**
Expected wallet to have same defaults as present in the binary (i.e port 9000)

**Steps to Reproduce**
1. Login to Nym wallet
2. Go to bonding page and click advanced options
3. Note the default port in the wallet is incorrect (set to 1790)

**Screenshots**
https://imgur.com/a/jaKdfIh

**Which area of Nym were you using?**
 Wallet version 1.0.8

**Comment by tommyv1987** [comment]
@merve64 this is now fixed and will be rolled out in the next wallet release.
