### ISSUE TITLE
[Issue] nym-wallet 1.07 & 1.0.8 does not work on Windows 11 21H2 build 22000.778

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2306]
**Describe the issue**
nym-wallet 1.07 & 1.0.8 does not work on Windows 11 21H2 build 22000.778

**Expected behaviour**
It starts

**Steps to Reproduce**
Install nym-wallet on Windows 11

*An example:*
- Given I was setting up a mix-node following the instructions in the docs
- And I successfully bonded my node via the the wallet
- When I went to start my mixnode
- Then I was presented with an error

**Screenshots**
Application does not start, just a blink, that's all.

**Which area of Nym were you using?**
 Windows 11 21H2 build 22000.778

**Additional context**
Please provide any other information

**Comment by tommyv1987** [comment]
no longer needed, closing ticket
