### ISSUE TITLE
Wallet - bonding, adding table with stats

### ISSUE THREAD

**Issue by MarcinSN** [nymtech/nym#2321]
![image](https://user-images.githubusercontent.com/95295201/184111508-55e2f70d-9ae1-4075-ad93-7b82c85392de.png)

We are adding table with node stats below main bonding table

These stats were alredy developed by us months ago(by Fouad) now we are just introducing this panel in different form

Panel is purely informative and you can't perform any action there

figma file: https://www.figma.com/file/KiYKZnWeefSALAe0j2dAPI/Nym-Wallet?node-id=123%3A3706

- [x] design
- [x] development

**Comment by doums** [comment]
TODO:
- backend request to fetch estimated reward, probabilities active/inactive set, routing score
