### ISSUE TITLE
Shipyard - change all mentions of Nym Connect (shown in the image) to NymConnect

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2323]
<img width="1304" alt="Screenshot 2022-08-10 at 10 27 39" src="https://user-images.githubusercontent.com/31625607/183867837-bea69f50-c8cd-439f-8451-01c740edbcba.png">

**Comment by gala1234** [comment]
PR: https://gitlab.nymte.ch/nym/shipyard-www/-/merge_requests/7
Branch to test it: `247-content-change`
