### ISSUE TITLE
Update of bonding flow part 1

### ISSUE THREAD

**Issue by MarcinSN** [nymtech/nym#2324]
What is new

Table:
- delete Node rewards category
- add Operator cost category
- change settings description to node settings

![image](https://user-images.githubusercontent.com/95295201/183900225-28fb2e98-3851-4ab2-860e-49ced9492fd6.png)

3 action dots
Now we will have only 3 actions
- Bond more
- Redeem rewards
- Unbond

without any descriptions, just text and icon
![image](https://user-images.githubusercontent.com/95295201/183901832-6bb8869b-3015-450f-8bdf-77d5f1d7d735.png)

Dark mode
- dark mode version is also prepared

![image](https://user-images.githubusercontent.com/95295201/183904112-47e9803c-fefb-4f4b-8740-52556fff144c.png)

figma file: https://www.figma.com/file/KiYKZnWeefSALAe0j2dAPI/Nym-Wallet?node-id=3239%3A50783

- [x] design
- [ ] copy
- [x] development
- [ ] qa

**Comment by doums** [comment]
@MarcinSN can you provide me the tooltip value for the new column "Operator cost" please?

**Comment by doums** [comment]
TODO:
- "Bond more" action once the request is available and backend ready for it
- tooltip values to define
