### ISSUE TITLE
NE - Amend stake saturation level on all tooltips:

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2328]
Stake saturation level is showing the old 1 million NYM, it should be corrected to 400k NYM on below screens: 

![Screenshot 2022-08-09 at 12 57 56](https://user-images.githubusercontent.com/31625607/183642624-6a24b4b3-30dd-47a8-9b22-1d1f90831356.png)

![Screenshot 2022-08-09 at 12 58 22](https://user-images.githubusercontent.com/31625607/183642659-9d712123-ad59-4049-aa95-2ac76d0aef5b.png)

**Comment by gala1234** [comment]
For QA:
Branch `343-amend-stake-sat`
