### ISSUE TITLE
Website - SEO to fix:

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2330]
Google search for "nym explorer" shows Finney explorer and a few other irrelevant stuff instead of mainnet explorer and sandbox, we need to fix that. 

![paste](https://user-images.githubusercontent.com/31625607/183413719-60973479-740c-45db-8ce2-91dcd410fc14.png)

**Comment by rachyandco** [comment]
some tips here that we can follow: https://www.voog.com/blog/how-to-remove-your-website-or-web-page-from-google
