### ISSUE TITLE
NE - Upgrade Sandbox and make below changes: 

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2332]
Basically update Sandbox as its way way behind mainnet. 

Once upgraded make below changes:
1. Change the name from "Network Explorer" to "Sandbox Explorer" 
2. Add a button on the top that says "Switch to Mainnet explorer" that links to mainnet explorer. 
3. Link to the faucet too

**Comment by gala1234** [comment]
Deployment block till having the `sandbox explorer` updated
