### ISSUE TITLE
NE - Change how `Active set probability` is shown.

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2336]
NOTE to not forget: on v2 probably the id is coming from another path

Inclusion probabilities should translate to below buckets for UI use (based on Monte Carlo probability, not saturation)

    probability >= 70% -> high
    between (including) 30% to 70% -> good 
    probability <30% -> low

**Comment by mmsinclair** [comment]
Requires https://github.com/nymtech/nym/issues/2088 to be implemented correctly

**Comment by octol** [comment]
Update:

It was decided that we should have three buckets:

    >= 70% -> high
    between (including) 30% to 70% -> good 
    <30% -> low

**Comment by octol** [comment]
Raised https://github.com/nymtech/nym/pull/1626 to fix the last bits
