### ISSUE TITLE
Wallet - Vesting schedule on the dark mode needs more visible colours

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2339]
The timeline bar is using a black colour on the ticker for the time passed which is invisible (see picture). Need to change to a lighter colour. 
<img width="1134" alt="Screenshot 2022-08-01 at 18 43 26" src="https://user-images.githubusercontent.com/31625607/182210715-4a0a1e34-98d7-4e30-b325-03d75243c004.png">

Screen from figma:
![image](https://user-images.githubusercontent.com/95295201/182330470-3fd2af7b-26bc-47d4-a87f-838524e82d03.png)

Correct design in figma:
https://www.figma.com/file/KiYKZnWeefSALAe0j2dAPI/Nym-Wallet?node-id=2086%3A34523

- [x] design
- [x] development

**Comment by gala1234** [comment]
For QA:

Testing branch `332-fix-vesting-ui`

Changes done:
Fixing on dark mode progress bar colour and row color text
![image](https://user-images.githubusercontent.com/33252067/182379113-05da109f-8c2e-4802-99a3-8168703eadaa.png)
