### ISSUE TITLE
Wallet - Menu, highlights, global background colors

### ISSUE THREAD

**Issue by MarcinSN** [nymtech/nym#2341]
- We are using wrong background color in light version of wallet
![image](https://user-images.githubusercontent.com/95295201/180407149-8092270c-778f-4963-8eea-38ce4c4b667e.png)

- Spacing in leftside menu
So between each position in menu we have 32px of spacing, but each position is in block/group which height is 20px. Because we don't have this space menu still looks clutered
![image](https://user-images.githubusercontent.com/95295201/180416545-de411778-1d5e-4db2-ade4-a8a2e9d58639.png)

- Hovers  in leftside menu, light and dark mode

https://user-images.githubusercontent.com/95295201/180409005-33ccce48-a5e8-4ca0-8693-34cb76bdc07e.mp4

https://user-images.githubusercontent.com/95295201/180409048-8495208a-116c-43e5-b300-0730669a8dab.mp4

Figma file
![image](https://user-images.githubusercontent.com/95295201/180418010-0fa6931f-dbcf-4188-a517-86910920d684.png)
: https://www.figma.com/file/KiYKZnWeefSALAe0j2dAPI/Nym-Wallet?node-id=2646%3A43681

- [x] design
- [x] development

**Comment by gala1234** [comment]
@MarcinSN I'm attaching one screenshot per mode, I think I fixed all, but I would like your confirmation:

![image](https://user-images.githubusercontent.com/33252067/182810643-7a76f600-6591-44af-9815-c7178018d8e5.png)

![image](https://user-images.githubusercontent.com/33252067/182810821-6f67f659-3e06-4fc6-b6d0-e168c788173f.png)
