### ISSUE TITLE
Shipyard: Update discord links

### ISSUE THREAD

**Issue by fmtabbara** [nymtech/nym#2342]
Everywhere it says Join Discord, it needs to link to: https://discord.com/invite/nym

The current links are broken.

**Comment by gala1234** [comment]
@fmtabbara I found the "join Discord" in two places, but both already point to https://discord.com/invite/nym, and you did the change, I think I can close this task  : )


![image](https://user-images.githubusercontent.com/33252067/182118564-2bef6f89-b856-41d7-8378-7bf31e8304ad.png)
