### ISSUE TITLE
Shipyard docusaurus site

### ISSUE THREAD

**Issue by jayapapaya** [nymtech/nym#2358]
Shipyard needs a simple website, like the docs pages, but with more images! Shipyard is launching on Thursday as the Beta space for experimental apps and for our grants program. We need just a simple set of pages describing the basic information, initially just an Overview page, and a Service Grants page.

Site map: https://drive.google.com/file/d/1guZEDixhcwkV9F2Bnu9vUFq34EEaxlTK/view?usp=sharing

OVERVIEW (urgent for Thursday)
NYM CONNECT (not public until next week)
SERVICE GRANTS (urgent for Thursday)
BUILD GRANTS (not public until the week after next)
- VINGE
- BRIER
- YELEN
- DELLA LU

Website copy is being drafted here: https://docs.google.com/document/d/192NfVcZSaSNkMcJ8eDbBGl6WxpIq11HZ6sTYVeJXb50/edit?usp=sharing

Images are here: https://www.notion.so/01c6dce56742474b88185a3db1225603?v=61f2ca60b0e7430789891a88ca21b4c8

**Comment by gala1234** [comment]
First iteration done, deployed to: https://shipyard.nymtech.net/
