### ISSUE TITLE
NE: Fix up links to validators and block explorer

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#2359]
The url is malformed: `https://explorer.nymtech.net/https://blocks.nymtech.net/validators` instead of `https://blocks.nymtech.net/validators`

**Comment by gala1234** [comment]
@mmsinclair could it be the same issue fixed here https://github.com/nymtech/nym/issues/2371 ?

Has this linked PR https://github.com/nymtech/nym/pull/1442 and is waiting to be deployed
