### ISSUE TITLE
Connect - UI should display errors/events generated by the disconnect listener

### ISSUE THREAD

**Issue by octol** [nymtech/nym#2373]
If the disconnect listener detects an errors, then we should display it in the UI. 

This also includes emitting tauri events from: https://github.com/nymtech/nym/blob/8f1cb67bf7df5bb7d7b0617c42a14f359356a04d/nym-connect/src-tauri/src/tasks.rs#L87

**Comment by tommyv1987** [comment]
no longer needed here, closing ticket
