### ISSUE TITLE
NE - Change name and tooltip for Avg. Uptime:

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2395]
Change name to "Routing Score"

Tooltip: Node's routing score is relative to that of the network. Each time a node is tested, the test packets have to go through the full path of the network (a gateway + 3 nodes). If a node in the path drop packets it will affect the score of other nodes in the test.

**Comment by gala1234** [comment]
For QA:
Testing branch `276-ne-name-tooltip-avg-uptime`

![image](https://user-images.githubusercontent.com/33252067/176151051-288eb849-45f6-4f16-ba25-dcc04b6da612.png)


Is not deployed yet
