### ISSUE TITLE
Nym Connect - macos build not working

### ISSUE THREAD

**Issue by octol** [nymtech/nym#2404]
Note: this might have been fixed by: 3aff419a764079c813c81784bd65d71e021be0a2

**Comment by gyrusdentatus** [comment]
Feature/hryczsynvpn worked for me on MacOS Monterey 10.xx (the widget with GUI - not the socks5 client itself obviously...) 

Sorry, just lurking around on my iPad :)

**Comment by octol** [comment]
Turns out this was indeed fixed in `3aff419a764079c813c81784bd65d71e021be0a2`
