### ISSUE TITLE
Connect - Gracefully disconnect

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#2419]
Currently we run the socks5 client in its own thread and runtime, and the abruptly terminate it when the user clicks disconnect.

Instead we should send a message to the socks5 client to stop, and politely wait for it to finish.

This includes creating a channel for reporting state back to the UI from the client task.

Blocked by: https://github.com/nymtech/nym/issues/2020

**Comment by benedettadavico** [comment]
example of the graceful disconnect: 
<img width="1004" alt="disconnect" src="https://user-images.githubusercontent.com/46782255/190620131-c3decf28-4e9d-4523-95e8-56c799ac8efe.png">
