### ISSUE TITLE
NE - Bring up the number of delegators and show it in the header section of "Stake Breakdown"

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2430]
Currently its a bit hidden how many delegators a node has. So instead of showing it in the dropdown for "Delegation total" we should show it in the header of that section. So something like this -> "Stake Breakdown (XXX delegators)"

**Comment by gala1234** [comment]
For the QA:
Feature URL https://network-explorer-feature-241-num-of-delegators.ci.nymte.ch

Now the delegators number is displayed here:

<img width="537" alt="image" src="https://user-images.githubusercontent.com/33252067/172802367-6649780d-ce9c-4505-826a-95fc64e9b9ab.png">

**Comment by gala1234** [comment]
It isn't deployed to the sandbox.

- Mainnet:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/33252067/176122755-9dca6733-59f6-4e71-8c67-3fbf7f68ca3a.png">

- QA:
<img width="420" alt="image" src="https://user-images.githubusercontent.com/33252067/176122852-7a360f3a-92da-4c83-8d77-221e81dfb3d7.png">

 - Sandbox 
<img width="457" alt="image" src="https://user-images.githubusercontent.com/33252067/176122952-5f626269-50cc-4459-951a-8e0be632f8d2.png">
