### ISSUE TITLE
[Issue] Unable to undelegate locked tokens from the node if delegated amount is less than total locked amount.

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2433]
**Describe the issue**
Unable to undelegate locked tokens from the node if delegated amount is less than total locked amount.

**Expected behaviour**
Delegation should be removed from the mixnode and tokens be available for another delegation.

**Steps to Reproduce**
1. Delegate locked tokens (e.g. you got option2 with 3500 NYM - delegate 3498 NYM)
2. Wait for next epoch
3. Try to undelegate.
4. Transaction will be successful, but delegation won't be removed and transferred to the balance.

**Screenshots**
https://i.imgur.com/aN7cFJT.png
https://i.imgur.com/fr3Rv34.png

**Which area of Nym were you using?**
1.0.6
windows 10 latest

Aditional info: testing report form

**Comment by merve64** [comment]
Hi.  Can you please check this bug report? its still present. Thank you!

**Comment by tommyv1987** [comment]
hi @merve64  can you confirm this issue still persists with the user? thank you

**Comment by tommyv1987** [comment]
Closing based upon no response.
