### ISSUE TITLE
[Issue] 'something went wrong' while trying undelegate

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2434]
**Describe the issue**
When user tries to undelegate he gets a an error message saying "something went wrong". At the same time a pending tx shows up to wait for an hour. Then the tx just disappears and no undelegation goes through. He has tried this many time over a time span of 4-5 days. The same behavior is persisting

**Expected behaviour**
He had a problem redeeming rewards, for that he has filled a form for a potential bug before this one. As a workaround he was advised to undelegate and then redelegate. He expects his nym to get undelegated. Then transfer to balance. Then delegate everything locked and unlocked

**Steps to Reproduce**
1. go to delegation
2. choose undelegate

**Screenshots**
https://imgur.com/a/3MnGlT7
https://imgur.com/a/mr737zc

**Which area of Nym were you using?**
win10 
using wallet 1.0.8

**Comment by tommyv1987** [comment]
not reproducable, closing ticket
