### ISSUE TITLE
[Issue]with delegators count on the wallet

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#2435]
Describe the issue
Mixnode delegators count is always ==20 on any mixnode (The bug reported by Evgeny and he mentioned that checked 7 mixnodes they run and they all show the same wrong value)

To Reproduce
Run a mixnode and get 20+ delegators on it

Expected behaviour
get actual number of delegators (or at least delegations)

Screenshots
https://i.imgur.com/7qVRR7L.png
https://i.imgur.com/m56L1Ap.png

Hardware specs on your device
win 10 en pro, latest updates, nym wallet 1.0.8, ryzen 5800x, 32gb

**Comment by tommyv1987** [comment]
this is no longer relevant for later releases of the wallet, closing the ticket
