### ISSUE TITLE
NE - correct the delegation number

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2449]
Currently node page is showing multiple delegations for one account, they sould be merged to show one delegation per account (delegator) only

- [x] Backend
- [x] Frontend

**Comment by gala1234** [comment]
For QA:
Feature frontend branch: `feature-225-delegation-number`
Now, shouldn't be repeated delegators, on the node bond section.
Before:
![image](https://user-images.githubusercontent.com/33252067/171403835-69a30282-e476-4761-9704-a22810db5b2f.png)
Now:
![image](https://user-images.githubusercontent.com/33252067/171403920-05cee298-3175-4c7e-9a22-339b006cfc47.png)

**Comment by gala1234** [comment]
This one has been deployed to all envs, sandbox, mainnet and Qa. We can see that we receive duplicate delegators id from the API endpoint `v1/mix-node/nodeId/delegations`. But the UI now use the new endpoint with unique delegators `v1/mix-node/nodeId/delegations/summed`.

- Sandbox:
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/33252067/176125097-5ca82052-ab6e-409b-8512-99391c4ff049.png">
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/33252067/176127770-604f5f88-29b5-449a-943a-5397269815b9.png">
