### ISSUE TITLE
NE - other small changes 

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2455]
Changes to be made: 

- [x] Remove “Layer” from node list page
- [x] add Avg. Uptime to the node list
- [x] Use STAKE everywhere for Bond+Delegation on the explorer (5 places). Remove all notions of Pledge and change it to Bond. 
- [x] Re-organising node list columns to: owner indentity location host stake stake-saturation self delegators profit-margin uptime

**Comment by gala1234** [comment]
@jessgess, is @octol going to change the `mix-nodes` API to have the delegator number in the node list?
If so, we need to assign him this ticket too.

**Comment by gala1234** [comment]
Only deployed to QA and Mainnet
