### ISSUE TITLE
Add all the reward data into the wallet, similarly to that of the network explorer

### ISSUE THREAD

**Issue by tommyv1987** [nymtech/nym#2460]
Image attached shows all the properties and values that need to be included into the wallet (Node settings page)

**Comment by tommyv1987** [comment]
![image](https://user-images.githubusercontent.com/60836166/167377150-70a4008b-0cfb-48ac-9321-74e20c6211fd.png)

**Comment by fmtabbara** [comment]
Closed as 1.0.8 includes this detail in the bonding page
