### ISSUE TITLE
Wallet - Add "Test my node" section and it results to the Node Settings

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2474]
I think one way to do this would be to have a designated gateway, call it DG, that we can keep usage for free of charge. But to prevent free riding of this gateway for other usages the packets sent to the DG should end in there too (a closed loop). 
Flow: 
- User clicks "Test my node" button in the wallet.
- Wallet creates a random path that is something like DG -> Node1 -> Node2 -> Node3 -> DG. (Each time the user clicks maybe the other 2 nodes in the path can change to stay the same!) 
- Some results show in the wallet i.e. X packets were sent, Y many were received in X time etc etc.

**Comment by futurechimp** [comment]
We can use the WebAssembly client for this, it can go directly into the wallet's TypeScript (no Rust bindings).
