### ISSUE TITLE
Network Explorer - add `ErrorBoundary` to catch unhandled errors

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#2479]

**Comment by mmsinclair** [comment]
Shows this error boundary on uncaught errors:

![image](https://user-images.githubusercontent.com/14054343/157512971-f52eedbc-67c7-4e4c-a26e-89fd3e59036d.png)

A stack trace is only shown when running locally.

**Comment by tommyv1987** [comment]
will pick up when new network explorer is spec'd out
