### ISSUE TITLE
nym wallet- unbonding problem (UX)

### ISSUE THREAD

**Issue by eellf** [nymtech/nym#2502]
**Describe the bug**
@hayabusa300kmh - The user says they couldn't unbond and they see the loading wheel for a long time because they don't have enough testnet tokens for the transaction. 

**To Reproduce**
1. Go to nym wallet
2. Click on unbond button
3. Sees the loading wheel for a long time
4.

**Expected behavior**
Unbond quickly, and see there is a fee for bond/unbond.

**Screenshots**

**Hardware specs (please complete the following information):**
 - OS: windows/mac
 - nym wallet
 - Version 0.12.1

**Additional context**

People who have this issue are @hayabusa300kmh and @cherrytone. For this issue, Harry wrote the chat "That's a very good idea for a UX warning - the fees are sort of "symbolic" and just are there to prevent attacks where people bond/unbond over and over again."

**Comment by tommyv1987** [comment]
We've now added the section in the wallet advising users to make sure they have enough balance to cover fees for their transactions. Closing issue.
