### ISSUE TITLE
Nym wallet - UI issue: spacing between amount and nymt ticker

### ISSUE THREAD

**Issue by noahpierau** [nymtech/nym#2508]
**Describe the bug**
There is a small UI issue in the Sandbox wallet where the spacing between amount and nymt ticker is missing.

**To Reproduce**
1. Go to the Send tab
2. Fill in the amount
3. Click on Next
4. See the UI issue on screenshot

**Expected behaviour**
Spacing between the amount and the nymt ticker.

**Screenshots**
![nym-ui-issue](https://user-images.githubusercontent.com/16287891/147296004-cd2acec2-fc80-4e4c-be8a-6d30e8fb4ddf.PNG)

**Hardware specs:**
 - Windows 10 Pro
 - Nym wallet
 - Version 0.12.1

**Additional context**
Found while testing the wallet.

**Comment by noahpierau** [comment]
The spacing issue is also visible on the next screen, on the overview of the transaction: 
![nym-ui-issue2](https://user-images.githubusercontent.com/16287891/147296565-e2e9faac-9c3d-43db-bd92-a4f8fa1b4853.PNG)

**Comment by tommyv1987** [comment]
rework done on wallet since, no longer applicable
