### ISSUE TITLE
Project Elephant updates

### ISSUE THREAD

**Issue by tommyv1987** [nymtech/nym#2511]
Updates:
 - `<title> Nym Project Elephant </title>` needs to be updated

 - Some of the copy doesn't sound grammatically correct

**Confirmation screen** 
Return the confirmation id on the confirmation screen - 
```
{
	"result": true,
	"confirmationId": "aed2cb07-120c-478e-bbe4-0573082e63df"
}
```

This gives the user their confirmation guid, we have this stored in the db, this is returned after a successful post request to registration This will need a design element added to the confirmation screen.

​**Error warnings** 

`Could not find account id` - could be represented....

`We could not find your account`

on the mnemonic validation it ends in a full stop, we should standardise all error messages to render on screen. For example will they all have full stops?

`A Mnemonic would normally be 24 words.`

**awaiting deployment to see these changes.. tbc** 

go to homepage should be (go to nym home) or have a better explanation of where the route is going
as I think return to homepage means go back to the start of the application

**Mobile responsive view** 
Some of the headings values on the homepage differ in size. 
Steps, being on the homepage, change your display view to mobile and you can see.

**Comment by Aid19801** [comment]
- Page title updated to just "Nym". Lemme know if you'd like something else? "Whitelisting" or "Elephant Sale" or something?

- "confirmationId" is on a diff branch and awaiting approval [https://gitlab.nymte.ch/nym/project-elephant/-/merge_requests/5]

- The error string "Could not find account id" actually comes from the API. I have hard coded it _also_ in the FE code for TS reasons. If you're interested, this is going back a couple of weeks now but from memory - the way to catch errors that could be of multiple types in a typescript try-catch and _then_ to hand them to a hook form's error handling revolves syntax is like...

```
} catch (error) {
        const dynamicErrorHandled =
          error instanceof Error
            ? error
            : new Error('We could not find your account');
        setError('mnemonic', {
          type: 'manual',
          message: dynamicErrorHandled.message,
        });
      }
```

That way we always have an error.message to hand to their setError, even if the actual error being caught isn't an error type. Or at least that's what made sense to me. Mark may disagree.

- I've removed the full stop from the mnemonic error, standardising.

- Ok so this one... "go to homepage should be (go to nym home) or have a better explanation of where the route is going
as I think return to homepage means go back to the start of the application". Originally it did go to the nymtech.net site, but Jess asked for it to route back to the beginning again. I can change that or leave as is. Let me know which you'd like?

- With headings sizes... could you check in with Marcin, as i've used the font sizes or elements in the inspect of Figma. If you can give me specifics, i'm happy to change.

**Comment by tommyv1987** [comment]
@MarcinSN  can you check on the last comment from @Aid19801  please?

Bullet one - I reckon `Nym Whitelisting`

With the error messaging, maybe, @mmsinclair  to confirm? If it hinders releasing we may just stick with the API response.

Also, with the `go to homepage` and the `nym icon` on click, they should go back to the start of the whitelisting flow.

Thanks and good stuff :muscle:
