### ISSUE TITLE
Rename formatAsRecipient

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#252]
Could this method in `client.js` in the webassembly client

```
    /**
     * @return {string} a user-pubkey@nym-gateway recipient address
     */
    formatAsRecipient() {
        return `${this.identity.address}@${this.gateway.mixAddress}`
    }
```

be renamed to `address()`? 

I don't want to change this as we're right before 0.7.0 release but it seems to me that that's what this method means.

**Comment by jstuczyn** [comment]
Then we have to discuss what would be "Destination", "Address", "Recipient", etc. Because technically client's address is only the first 32bytes of the destination.
