### ISSUE TITLE
UI Update - Rebuild create account page

### ISSUE THREAD

**Issue by fmtabbara** [nymtech/nym#2533]

**Comment by tommyv1987** [comment]
Tested in branch `feature/ui-enhancements`

Tested on all OS -
- WIndows (11), PopOS (21,04), Ubuntu (20.04), MacOs Bigsur

Steps to test, clone and pull the repo.
- Build the wallet on all platforms
- Launch the wallet 
- Select create account 

Expected, wallet to behave as previously, new look and feel in accordance to designs in Figma.

To do - update test framework.
