### ISSUE TITLE
UI update - Rebuild sign in page

### ISSUE THREAD

**Issue by fmtabbara** [nymtech/nym#2537]

**Comment by tommyv1987** [comment]
Tested in branch `feature/ui-enhancements`

Tested on all OS -

    - Windows (11), PopOS (21,04), Ubuntu (20.04), MacOs Bigsur

Steps to test, clone and pull the repo.

    - Build the wallet on all platforms
   - Launch the wallet
   - Splash screen displayed

Expected, wallet to behave as previously, new look and feel in accordance to designs in Figma.

![image](https://user-images.githubusercontent.com/60836166/144098869-d6225ba9-a75a-466c-baa5-e41743a0cbd0.png)
