### ISSUE TITLE
UI update - Add top navigation

### ISSUE THREAD

**Issue by fmtabbara** [nymtech/nym#2538]

**Comment by tommyv1987** [comment]
Tested in branch `feature/ui-enhancements`

Tested on all OS -

   -  Windows (11), PopOS (21,04), Ubuntu (20.04), MacOs Bigsur

Steps to test, clone and pull the repo.

   -  Build the wallet on all platforms
  -   Launch the wallet
  -  Log in with your existing mnemonic or create an account from scratch
  - On the top menu, you now have you Token address and your balance,
  - You can also log out from the top menu header.
 
Expected, wallet to behave as previously, new look and feel in accordance to designs in Figma.

![image](https://user-images.githubusercontent.com/60836166/144099115-e819ce59-90f7-4116-b37d-4a3c4a6302cd.png)
