### ISSUE TITLE
UI update - Refine side navigation

### ISSUE THREAD

**Issue by fmtabbara** [nymtech/nym#2539]

**Comment by tommyv1987** [comment]
Tested in branch `feature/ui-enhancements`

Tested on all OS -

    WIndows (11), PopOS (21,04), Ubuntu (20.04), MacOs Bigsur

Steps to test, clone and pull the repo.

 -   Build the wallet on all platforms
  -  Launch the wallet
   - Sign into wallet
   - The navigation pane has now been updated

Expected, wallet to behave as previously, new look and feel in accordance to designs in Figma.

![image](https://user-images.githubusercontent.com/60836166/144098577-44a98397-4ad6-41c0-a580-8afeca7710d8.png)
