### ISSUE TITLE
Make the wallet configurable?

### ISSUE THREAD

**Issue by tommyv1987** [nymtech/nym#2542]
Questions: 
More of a requirement / spike piece -

If and when we deprecate the web wallet  -do  we need to have the environments configurable for the desktop wallet, so users can use mainnet, testnet and others if applicable?

Do we require a new screen which is configurable by input, where is the screen displayed?
> Config Settings?
 - Urls, addresses, mnemonics...

**Comment by fmtabbara** [comment]
ref - https://github.com/nymtech/nym/issues/2490
