### ISSUE TITLE
Faucet for permanent testnet

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2546]
- [x] Build UI
- [x] Integrate with Validator
- [x] Link address to block explorer
- [x] Use testnet faucet account
- [x] Deploy

**Comment by tommyv1987** [comment]
We have not provided the faucet account details yet. But this has been deployed. Moving to done.

**Comment by tommyv1987** [comment]
Deployed and released, closing ticket. Not archived correctly.
