### ISSUE TITLE
Remove gateway delegation/undelegation from web wallet

### ISSUE THREAD

**Issue by fmtabbara** [nymtech/nym#2551]

**Comment by tommyv1987** [comment]
Steps to test:

Navigate to the `/wallet-web` directory in the Nym solution
Checkout the respective branch 
Build and deploy the wallet
Then if you navigate to the `delegate` page on the web-wallet

The option for staking to gateways has been removed.

![image](https://user-images.githubusercontent.com/60836166/141761184-04b94c59-d5d6-47c3-86d8-412c0861cb73.png)

Tested on Brave
This will still need to be deployed, moving to done.
