### ISSUE TITLE
Project Elephant

### ISSUE THREAD

**Issue by Aid19801** [nymtech/nym#2552]
Build basic scaffolding of FE app:

- [x] 6 routes (welcome/explanation, select which option applies to user, provide credential, enter further info, submit/end + 404 page)
- [x] form(s)
- [x]  Footer
- [x] Responsive
- [x] 1. Check mnemonic decodes/decrypts correctly
- [x]  2. Check mnemonic is on whitelist 
- [x]  3. Check user data is good locally
- [x]  4. Register user data via API

**Comment by tommyv1987** [comment]
Done, not archived properly. Closing ticket.
