### ISSUE TITLE
Change Mixnode Detail's DataGrid into a regular 1-row MUI Table

### ISSUE THREAD

**Issue by Aid19801** [nymtech/nym#2557]
✅ Change the MUI Datagrid instance on Mixnode Detail pages to be a regular one-row MUI Table.

Before - with Mui Data Grid:
https://feature-network-explorer-react.ci.nymte.ch/network-components/mixnodes/2cFpCe7yP79CcuRpf6JBRdJaSp7JF5YcA5SHi8JVm1d2
inspect element, you'll find old Datagrid classes etc. eg. "MuiDataGrid-root"
Note: Sorting arrows in the UI

After - with MUI Table:
https://network-explorer-mixnode-detail-datagrid.ci.nymte.ch/network-components/mixnodes/2Vrr7s2peGiWsPh6xY3ZFEMDRmMNv8xLBUtV5XMyQLSB

Note, no sorting arrows, inspect elements and find Table classes eg "MuiTable-root".

**Comment by tommyv1987** [comment]
This is yet to be deployed. However, this is working locally.

Currently, there's a feature branch - `https://network-explorer-bug-mapp-nodemap.ci.nymte.ch/network-components/mixnodes/2cFpCe7yP79CcuRpf6JBRdJaSp7JF5YcA5SHi8JVm1d2`

If you navigate to this specific user, you can see that the mix node details are presented in a MUI-Table as opposed to a grid.
