### ISSUE TITLE
Client should try to reconnect to gateway on broken pipe

### ISSUE THREAD

**Issue by jstuczyn** [nymtech/nym#256]
Currently if gateway goes down (or crashes), the client will continuously fail on:
``` 2020-06-04T09:25:10.082 ERROR nym_client::client::mix_traffic          > Failed to send sphinx packet to the gateway! - NetworkError(Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))```
Instead it should either just fail and terminate or even better, try to reconnect after some backoff interval

**Comment by futurechimp** [comment]
@jstuczyn is this still a thing? Please close if it's doing what it needs to do, you'll have a better handle on this one than me.
