### ISSUE TITLE
Add a burger menu on top left for open closing the side bar. Currently the Nym logo is doing that

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2572]

**Comment by tommyv1987** [comment]
Steps for testing:

Run the explorer locally / or on feature branch for the new react site
On the left hand menu - the burger menu button is actionable

![image](https://user-images.githubusercontent.com/60836166/140375045-f9adf5e3-c11a-4edf-97c6-0c4a6a238ae2.png)


Tested on:
Browser: Brave v1.3 
Automation tests using webdriverio in flight for this as well.
