### ISSUE TITLE
Update website icons

### ISSUE THREAD

**Issue by fmtabbara** [nymtech/nym#2575]
Request from Pablo to update four icons on the website. The current icons slightly misrepresent mixnets and need updating

**Comment by tommyv1987** [comment]
@PabloNym  - just a checking to make sure you have a look at this.

**Comment by PabloNym** [comment]
> @PabloNym - just a checking to make sure you have a look at this.

Sure will do it asap, just finishing some stuff on the marketing side and will start with icons
