### ISSUE TITLE
Enable paste on input of mnemonic on production version of builds on nym-wallet

### ISSUE THREAD

**Issue by tommyv1987** [nymtech/nym#2579]
**Description**
Given I am building the nym wallet on a mac os
When the application is launch 
And I want to enter my mnemonic 
Then the production version on mac does not allow the entry to be `cmd + v` pasted
   -Work around I can `ctrl-click` and paste into the field
   
![image](https://user-images.githubusercontent.com/60836166/137872176-27fddbdb-40b7-4350-88d2-02254b37fe02.png)

   
 For ease of use we should enable allow this field to be pasted from keyboard only

**Comment by gyrusdentatus** [comment]
**ctrl-click** does not work on **M1** nor does two finger click as on this picture >>>>
<img width="604" alt="Screenshot 2021-10-26 at 15 23 20" src="https://user-images.githubusercontent.com/33793809/138887788-60a4b1c9-3ca8-4fb1-9505-9d57592a1af4.png">
 
@tommyv1987

**Comment by gyrusdentatus** [comment]
this might be a solution 
read the comment for more info
https://github.com/tauri-apps/tauri/issues/849#issuecomment-918442151

example:
https://github.com/probablykasper/mr-tagger/blob/master/src-tauri/src/main.rs#L28-L78

**Comment by tommyv1987** [comment]
This is successfully now working.

*Steps to testing:*

- Install the latest nym wallet (build the binaries)
- Launch the binary 
- Have an item copied to the clipboard from outside the wallet
- Enter the wallet homepage / splash screen
- In the input mnemonic field `cmd + v` - the values are copied correctly

![image](https://user-images.githubusercontent.com/60836166/140380680-2aadbfb3-9044-4e4f-8002-ceae8b5a7a1f.png)

**Comment by gyrusdentatus** [comment]
@tommyv1987 @mmsinclair 

<img width="248" alt="Screenshot 2021-11-18 at 22 14 05" src="https://user-images.githubusercontent.com/33793809/142497741-c2038f30-f803-4be1-b2d0-92d3b4585d61.png">
`cmd + v` does not work on my Macbook M1 Air after installing it from .dmg 

Thought right click does not work either but somehow I have figured it out :)
