### ISSUE TITLE
Migrate to SvelteKit

### ISSUE THREAD

**Issue by benmccann** [nymtech/nym#2586]
Sapper is no longer actively developed and SvelteKit is a much better experience

Migration guide: https://kit.svelte.dev/migrating
SvelteKit + Tauri doc: https://css-tricks.com/how-i-built-a-cross-platform-desktop-application-with-svelte-redis-and-rust/

**Comment by tommyv1987** [comment]
Thank you for letting us know @benmccann, I've assigned this to the appropriate team to action.
