### ISSUE TITLE
NE - Change the network explorer to show new economic dynamics.

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#2597]
@gala1234 

add below to node profile with their tooltips
- [x] reward estimates
- [x] node saturation
- [x] chance of being in the active set
- [x] profit margin

- [x] add No. delegators to the delegators section of the node profile

- [x] add PM, Delegators and Avg. Uptime fields to the node list 

API changes to provide the values

**Comment by gala1234** [comment]
@mmsinclair I'm using this ticket to fix this small ui issue, when is selected the light mode: 
![image](https://user-images.githubusercontent.com/33252067/162211514-14be8281-69e3-4f6e-992e-cf1b5d9a2b7b.png)
