### ISSUE TITLE
Get signing certificates for Nym Wallet

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#2599]
- [x] Apple signing certificate
  - [x] Create Apple developer team
  - [x] Issue development cert
  - [x] Issue prod cert
- [x] Windows signing certificate
  - [x] EV docs submitted
  - [x] Get cert @raphael-walther 
  - [x] Update CI to build Windows wallet

**Comment by rachyandco** [comment]
EV cert verification in process
