### ISSUE TITLE
Discourse added to website

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#2619]
Blocked by nymtech/nym#2617 

- [ ] CSS match Nym branding
- [ ] integrate into a dev branch of the website (add constants so that we can switch over to prod/hosted instances later)

Docs are https://www.discourse.org/

Examples are:
- https://community.vega.xyz
- https://gov.uniswap.org/t/community-governance-process/7732

**Comment by tommyv1987** [comment]
I no longer think this ticket is relevant, closing this.
