### ISSUE TITLE
Hide / scroll mix node delegates when the list is very long

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#2625]
We are expecting there to be lots of delegations on mixnodes and we should do something like this:

![image](https://user-images.githubusercontent.com/14054343/138068079-f44675f8-367f-4449-a5cf-b95690282c19.png)

At the moment the vue-js and react explorers show an unbounded table:

![image](https://user-images.githubusercontent.com/14054343/138068182-b8b47fb2-3841-416b-90c3-9c429a2f7f39.png)

It would be nice to improve this 😀 

- [ ] Show up to 5 delegators in the mixnode detail view
- [x] When there are more than 5 delegations, hide the extra delegators in a expand section, or make the table scrollable (but keep the headers visible, so only scroll the table content rows - use MUI's equivalent of `tbody { overflow: auto; }` )
- [x] Test with this node https://testnet-milhon-explorer.nymtech.net/nym/mixnodes/2cFpCe7yP79CcuRpf6JBRdJaSp7JF5YcA5SHi8JVm1d2

**Comment by tommyv1987** [comment]
@mmsinclair @Aid19801
in the old explorer as seen above we have the blockheight of the delegation stake, has this requirement now been removed?
![image](https://user-images.githubusercontent.com/60836166/140046945-a2b5330a-70e2-43ed-a724-6580b7162395.png)

**Comment by tommyv1987** [comment]
Moving to done, requirement to add the transaction data to be added at a later date.
