### ISSUE TITLE
Mix node view `bond` column displays `pledge` instead of total stake, and sorting by string and not be value

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#2626]
Things to fix:

- [x] `bond` column in mix nodes should show a value of "node.bond_amount + node.total_delegation" in PUNK
- [x] sorting should be by the decimal value, not the string value

### Value

The mix node table `bond` column is showing only the owner's pledge value and not the total pledged by the owner + sum of all delegates.

![image](https://user-images.githubusercontent.com/14054343/138064883-090ff090-07fb-4eea-90a0-e6a2495eb692.png)

![image](https://user-images.githubusercontent.com/14054343/138064955-8288058e-cded-4979-aca5-18e860977b3b.png)

### Sorting

Both the vue-js explorer and the react explorer sort by the string value instead of the decimal value. This node has the most stake on it and it is never first. Currently is has 50k PUNKs on it:

https://testnet-milhon-explorer.nymtech.net/nym/mixnodes/2cFpCe7yP79CcuRpf6JBRdJaSp7JF5YcA5SHi8JVm1d2

**Comment by tommyv1987** [comment]
LGTM:
Bond total is correct.
Steps for testing:

- Navigate to the url listed above
- Check the total calculation 
- Navigate to the mixnode overview detail page (extract the previous identity key)
- Input the identity in the input search
- The calculation of the bon total should match that displayed from inside the mixnode page
