### ISSUE TITLE
Network Explorer - create 404 page

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#2627]

**Comment by tommyv1987** [comment]
LGTM:
Steps for testing:

- Run the explorer locally in the latest branch for the new react site
- Input an unknown route in the url

![image](https://user-images.githubusercontent.com/60836166/140039261-5145c3d7-be7e-4835-9697-ac08f4e10380.png)
- Selecting the overview button successfully returns the user to the overview page.

Moving to done.
