### ISSUE TITLE
Network Explorer - fix up formating

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#2629]
- [x] Fix mix node list formatting (render bond amount in PUNKs, use PrintableCoin)
- [x] Fix up icons
- [x] Fix nav icon colours
- [x] Add links to Nym's Telegram and Twitter using the icons in Figma (Top right of the page)
- [x] Move light/dark mode button should  
- [x] In mixnodes and gateways list tables, field names and the data fields need to be left aligned. The pipes between the field names need to be removed
- [x] Use colours and styles in figma for components, boxes, tables etc.
- [x] Colours on the map aren't right, its too red, dramatic, reminds of communism! :) Let's try to replicate the peach/pastel colours in Figma
- [x] Resize boxes in the node profile page to align vertically and horizontally with each other. 
- [x] Fix the pagination so the node list expands depending on the number of rows that it needs to show.   
- [x] check notes in figma for other comments and changes...

**Comment by tommyv1987** [comment]
Based upon the new designs and the tasks that have been broken down in this ticket. I'm happy to move this to done. 

The core of this work is done, but if any issues / bug arise, I will raise a separate ticket. I've already raised a few and will continue to do so.
