### ISSUE TITLE
Validators - link to Big Dipper

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#2635]
Link to:
- https://testnet-milhon-blocks.nymtech.net/validators

From:
- home page
- left nav

**Comment by tommyv1987** [comment]
This is now complete as part of the new website development for the explorer:

![image](https://user-images.githubusercontent.com/60836166/140730244-135b7ce2-7e81-4835-9232-2c2825ade18d.png)

Closing issue and moving to done.

**Comment by tommyv1987** [comment]
Cut off the bottom of the screen the url for big dipper is displayed.
