### ISSUE TITLE
Mix node detail view

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#2660]
Shows details for a mix node by identity key

Cards:
- [x] details
- [x] pledge and delegation bond details
- [x] map location
- [x] uptime stats
- [x] uptime graph
- [x] port status

**Comment by Aid19801** [comment]
https://github.com/nymtech/nym/pull/799

**Comment by tommyv1987** [comment]
As part of the ongoing explorer development, this work is now complete and pending release.
