### ISSUE TITLE
Explorer - mixnode list, add a column called "% Self"

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2664]
To show ratio of the pledge to the bond. Pledge*100/total Bond.

**Comment by tommyv1987** [comment]
New requirement:
Steps to test:
ENV: local
Browser: Brave
- Navigate to network-explorer home page
- Select mixnodes
- In the data grid view - you can see the new column and it's respective values

![image](https://user-images.githubusercontent.com/60836166/140045756-ec63decf-565a-4bc7-bf76-1aa64d50f9cf.png)
