### ISSUE TITLE
Determine times for each DKG phase

### ISSUE THREAD

**Issue by neacsu** [nymtech/nym#2719]
After https://github.com/nymtech/nym/issues/2670 is merged to QA, we should input better values for how much each DKG phase should last.

The following (guessed) values have been merged for the DKG phases with 3 signers:
```
// The time sign-up is open for dealers to join
pub const PUBLIC_KEY_SUBMISSION_TIME_SECS: u64 = 60 * 2;  // 2 minutes
pub const DEALING_EXCHANGE_TIME_SECS: u64 = 60 * 5;  // 5 minutes
pub const VERIFICATION_KEY_SUBMISSION_TIME_SECS: u64 = 60 * 5; // 5 minutes
pub const VERIFICATION_KEY_VALIDATION_TIME_SECS: u64 = 60;  // 1 minute
pub const VERIFICATION_KEY_FINALIZATION_TIME_SECS: u64 = 60; // 1 minutes
// The time an epoch lasts
pub const IN_PROGRESS_TIME_SECS: u64 = 60 * 60 * 24 * 14;  // 2 weeks
```
Except for the first and last values, which are non technical, we should do some testing in QA to see what would be some proper values under normal circumstances, and maybe for more signers too (~20)

**Comment by neacsu** [comment]
Tagging the QA team to keep this in mind when deploying to QA (@benedettadavico @tommyv1987)

**Comment by tommyv1987** [comment]
done and dusted
