### ISSUE TITLE
Shipyard Academy selfhosted forms/quizz

### ISSUE THREAD

**Issue by irelativism** [nymtech/nym#2727]
Shipyard Academy independent forms

Next version of Shipyard Academy should be hosted in a webased form hosted in main website of Nym project:
1. In order to allow contributors to complete course on their own rithym
2. Not relying on proprietary platforms like discord. And having full technological control

Cheers Irelativism.

So far from litle research I have done this are good options for this, most are copyleft license has a plus even some are AGPL

1. Yakforms (previously FramaForms), https://framagit.org/yakforms/yakforms
2. Formpress, https://gitlab.com/formpress/formpress
3. Ohmyform (Typeform replacement), https://github.com/ohmyform/ohmyform
4. LimeSurvey, https://github.com/LimeSurvey/LimeSurvey
5. NextcloudForms (kinda depends on nextcloud-core) https://github.com/nextcloud/forms
6. Formtools, https://github.com/formtools/core
7. Tripetto (extension for wordpress), https://gitlab.com/tripetto

(list ordered from best worst option from my viewpoint)

**Comment by tommyv1987** [comment]
Shipyard two has already taken place closing this ticket.

**Comment by irelativism** [comment]
@tommyv1987 this closure is obviously nonsensical given there has been more then one shipyard and the problem remains. So requesting action is corrected and issue remains open. Cheers Irelativism
