### ISSUE TITLE
Gateways - change minimum bond to 1 NYM

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2761]

**Comment by mmsinclair** [comment]
An easy fix could be to remove this check: https://github.com/nymtech/nym/blob/9684b7ffbd466123bbcbc4c1753ae45d64fa4bd5/contracts/mixnet/src/support/helpers.rs#L47-L50

And change this check to include "equal to" `pledge[0].amount <= minimum_pledge.amount`:
https://github.com/nymtech/nym/blob/9684b7ffbd466123bbcbc4c1753ae45d64fa4bd5/contracts/mixnet/src/support/helpers.rs#L65

However, this might also be a bad idea 🤷‍♂️
