### ISSUE TITLE
[Issue] There is already an open connection to this client

### ISSUE THREAD

**Issue by sven-hash** [nymtech/nym#2845]
**Describe the issue**
If the nym-client crash or stop without waiting "cleaning process", it's impossible to reconnect directly, the gateway still see an open connection
After a while (more than 12 hours) it's possible to reconnect again

**Expected behaviour**
Open a new connection with the gateway works directly

**Stack Traces**

```
 2023-01-11T16:51:42.270Z ERROR client_core::client::base_client                                          > Could not authenticate and start up the gateway connection - Gateway returned an error response - There is already an open connection to this client
Error: ClientCoreError(GatewayClientError(GatewayError("There is already an open connection to this client")))
```

**Steps to Reproduce**
Steps to reproduce the behaviour, if you're familiar with BDD syntax, please write it in this style:
- `nym-client run --id test`
- application stop abruptly
- When trying to reconnect this error appears ` Gateway returned an error response - There is already an open connection to this client`

**Screenshots**
If applicable, add screenshots to help explain your problem...

**Which area of Nym were you using?**
 - Application: [nym-client(1.1.5 and 1.1.4)]

**Additional context**
Please provide any other information

**Comment by octol** [comment]
I think @mfahampshire kept hitting this one in his work recently. Imho this one is pretty high on the list of things we should fix
