### ISSUE TITLE
Automatic refresh of allow list

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#2852]
In the network-requester service provider, there's currently a standard allow list which gets downloaded from the Nym website once, at start. 

It works, but it would be nice if the network-requester periodically downloaded the list, once every two hours. That way if we add a new service to the standard allow list, all network-requesters automatically get the updated list.

**Comment by octol** [comment]
Implemented as part of https://github.com/nymtech/nym/pull/3261
