### ISSUE TITLE
No address in /js-example chat and critical dependency issues on MacOS Catalina 10.15.6

### ISSUE THREAD

**Issue by gyrusdentatus** [nymtech/nym#288]
Chat is not working for me right now on MacOS Catalina 10.15.6, it might be because of the missing dependencies or simply because there are no gateways on the network right now ...

or

``` sockjs.js:1606 GET http://localhost:8001/sockjs-node/info?t=1594910780691 net::ERR_CONNECTION_REFUSED ```
This could also be the reason

Here is the output warning when I do ``` npm run ``` :
```

WARNING in ./node_modules/@nymproject/nym-client-wasm/nym_client_wasm.js 219:14-53
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@nymproject/nym-client-wasm/client.js
 @ ./index.js
 @ ./bootstrap.js

```
It worked for me on Debian based distro but I cannot check how it runs there today.

**Comment by jstuczyn** [comment]
Can you see what's the status of this? It could have been because of gateway being temporarily down, but it'd be nice to verify that : )

**Comment by tommyv1987** [comment]
Going to close this as it's quite outdated, please re-open if the issue persists.

**Comment by gyrusdentatus** [comment]
> Going to close this as it's quite outdated, please re-open if the issue persists.

I think that was a wise choice, because yeah. It is really oooold. Not really relevant anymore. But we'll see how all the clients work so maybe something will appear :) 

Nice job cleaning up your old issues!
