### ISSUE TITLE
CI improvements

### ISSUE THREAD

**Issue by farbanas** [nymtech/nym#2897]
- [ ] Deduplicate builds (most builds have a `push` and `pull_request` trigger and both of them run builds)
- [ ] Fix nightlies
  - [ ] Storage issues
  - [ ] Reporting success when some builds failed
- [ ] Create our prebaked Dockerfiles and run builds in them

**Comment by tommyv1987** [comment]
@octol was working on this, we need to improve this still but this can be re-prioritised in the future
