### ISSUE TITLE
nym-mixnode doesn't bind to any port (Ubuntu 20.04)

### ISSUE THREAD

**Issue by sethforprivacy** [nymtech/nym#290]
Hi there,

I've been trying to get nym-mixnode spun up on my Ubuntu 20.04 Server instance, but have been unable to get the binary (pre-compiled or self-compiled) to attempt to bind to any ports. The process says that it starts up (and binds) successfully, but `netstat -tulpn` and `nmap` reveal that the process has not bound to any port.

I tried the pre-compiled 0.7.0 binaries, as well as the quick-install script.

Please let me know if there is anything else I can provide to help run this down!

**Comment by jstuczyn** [comment]
Can you provide slightly more details? I think it might be related to your network setup - I can run it just fine on 18.04 and 20.04

**Comment by sethforprivacy** [comment]
There’s nothing special about the hosts network, and all other services I run on the host bind properly.

Just a normal home network, with a Ubiquity router/AP setup.

Host is using UFW for the firewall, already forwarded ports through the router and UFW, but the service never even binds to the port (which it should do whether or not the firewall allows access from external).

**Comment by manito-dise** [comment]
Hi sethsimmons!!!I
I have been trying to run the mixnode in Ubuntu 20.04 and I have the same problem, it does not receive any package, has someone given you an answer?  because I think we are not the only ones with this problem!

**Comment by sethforprivacy** [comment]
Sadly no fix/response yet.

Still waiting to be able to run it on my host!

**Comment by manito-dise** [comment]
at first I thought it was a bad configuration with my server, but I think we are not the only ones, greetings

**Comment by benk31** [comment]
Hi, same issue here with ubuntu "18.04.4 LTS (Bionic Beaver). Is there any update on this? Thanks in advance.

**Comment by sethforprivacy** [comment]
This is working fine in v0.9.0, tested today.
