### ISSUE TITLE
Not able to connect 

### ISSUE THREAD

**Issue by namelessperson0** [nymtech/nym#2926]
**Steps to Reproduce**
Ran the below code.
1. `./nym-socks5-client init --id quickstart --provider 74cfBD1hkozPUrhcZksrwHucq2Hkn6f2S5LBcnDSPa6L.4QsA5Epmf1fhrnKPNPs545QiLmwpLGRk4oZ7z136PD6L@EEyq16v63aotPBCepxUpCgAojrNasZ6Hk1PjpRyBAdEp `
2. `./nym-socks5-client run --id quickstart`

After I execute the above steps and set localhost:1080 in proxy of debian system settings, I am not able to view websites.

**Log**
 I only get below logs. No error. I am able to view the website names I am trying to connect in the log.
```
nym_socks5_client::socks::request                                         > read from stream socks5
nym_socks5_client::socks::client                                          > Starting proxy for mojeek.com
```

**Details?**

 - Application: nym-socks5-client - version 1.1.7
 - OS:  Debian 11

**Comment by sven-hash** [comment]
You have to run a network-requester on the provider you set

Follow the doc to start one: https://nymtech.net/docs/stable/run-nym-nodes/nodes/requester

**Comment by tommyv1987** [comment]
Closing the comment based upon the input of @sven-hash - thanks @sven-hash
