### ISSUE TITLE
[Issue] Set a custom provider in 1.1.8

### ISSUE THREAD

**Issue by sven-hash** [nymtech/nym#2944]
**Describe the issue**

The possibility to select a custom provider from the list has been removed  I've some non tech friends that were using it to test the mixnet. Pretty anoying that it disappear without notice
Is possible to have it back in the new release ?

**Expected behaviour**
Like in 1.1.7 possibility to choose a custom provider in the list

**Screenshots**
From 1.1.7
![](https://i.imgur.com/2i6s29X.png)

**Which area of Nym were you using?**
 - Application: [Nym-connect 1.1.8]

**Additional context**
Please provide any other information

**Comment by tommyv1987** [comment]
Hey @sven-hash this will be re-introduced in the next iteration (maybe the one after) of nym connect. 

Apologies for any disruption this may have caused.
