### ISSUE TITLE
[Issue] building nym-mixnode on OpenBSD fails because of newer Rust requirement

### ISSUE THREAD

**Issue by timkuijsten** [nymtech/nym#2946]
I would like to mention that since v1.1.5 building nym-mixnode on OpenBSD 7.2 (the latest stable) does no longer work because of a dependency on Rust 1.64. The version of Rust that is shipped with OpenBSD is Rust 1.63 and building the mixnode yields the following error:
```sh
error: package `clap_derive v4.1.0` cannot be built because it requires rustc 1.64.0 or newer, while the currently active rustc version is 1.63.0
```

Now OpenBSD is released once every half year and ships with the then latest Rust so I wonder if it would be possible to be a bit more relaxed about Rust versions requirements. In the current situation I have to run mixnode v1.1.4 until OpenBSD 7.3 is released in May.

**Comment by tommyv1987** [comment]
@octol what are your thoughts on this one?

**Comment by octol** [comment]
Yeah I in general I agree that it's good to be a bit conservative on relying on the latest rust compiler version. I don't think we deliberately upgrade on every new version, and in this case it's a transitive dependency that hit the version requirement. It's even the case we're depending on `clap 4.0` and not `4.1`.

**Comment by octol** [comment]
I didn't know that `rustup` didn't support OpenBSD, so that's interesting

I think we're in the process of moving towards consolidating our dependencies to the top-level `Cargo.toml`, then it will be a little easier to control which versions we are depending on

**Comment by timkuijsten** [comment]
Sounds good! Looking forward :)

**Comment by timkuijsten** [comment]
fyi, OpenBSD 7.3, probably released somewhere in April or May, will contain Rust 1.68
https://marc.info/?l=openbsd-ports&m=167968983216683&w=2
