### ISSUE TITLE
Break down functions taking a lot of arguments

### ISSUE THREAD

**Issue by jstuczyn** [nymtech/nym#295]
There are few instances with functions, mostly constructors, taking more than 7 arguments (maximum recommended by clippy). For example AcknowledgementController::new() takes 10! I think some of the arguments should be put into a `config` struct, like, in the case of AcknowledgementController data like `average_ack_delay` or `average_packet_delay`

**Comment by futurechimp** [comment]
I think this will naturally fall into place once we start refactoring for constructor injection and wiring all over the place, I'll knock it out of the next few releases but we will get to it.

**Comment by tommyv1987** [comment]
This has been re-worked somewhat, going to close the ticket unless someone pipes up :)

```
impl AcknowledgementControllerConnectors {
    pub(super) fn new(
        input_receiver: InputMessageReceiver,
        sent_notifier: SentPacketNotificationReceiver,
        ack_receiver: AcknowledgementReceiver,
        ack_action_sender: AckActionSender,
        ack_action_receiver: AckActionReceiver,
    ) -> Self {
        AcknowledgementControllerConnectors {
            input_receiver,
            sent_notifier,
            ack_receiver,
            ack_action_sender,
            ack_action_receiver,
        }
    }
}
