### ISSUE TITLE
[Issue] WASM Client  arg is undefined

### ISSUE THREAD

**Issue by sven-hash** [nymtech/nym#2955]
**Describe the issue**
Try to use WASM client on React and this error appears `[Nym WASM client] Failed to start TypeError: arg is undefined`

**Expected behaviour**
Connection to the mixnet goes trough and an nym-client address is generated

**Stack Traces**
```
[Nym WASM client] Failed to start TypeError: arg is undefined
```

**Steps to Reproduce**
Steps to reproduce the behaviour, if you're familiar with BDD syntax, please write it in this style:
Following this doc https://github.com/nymtech/nym/tree/develop/sdk/typescript/packages/sdk

- Open browser
- Go to website where WASM is
- Load page and then error appears in the console

**Which area of Nym were you using?**
 - Application: [Nym WASM]
 - Browser: [Chrome, Firefox]
 - Version: [1.1.6]

**Additional context**
Where it is used https://github.com/notrustverify/pastenym-frontend/blob/migrate/v1.1.6/src/UserInput.js#L192

**Comment by fmtabbara** [comment]
Hey :wave: 

There should also be an event called `subscribeToConnected`.  This ensures the client is initialized and ready to use.

Could you try subscribing to your other events inside of `subscribeToConnected`?

**Comment by tommyv1987** [comment]
Closing issue based upon @fmtabbara last comment and no response since.
