### ISSUE TITLE
[Issue] Existing mixnode disappear

### ISSUE THREAD

**Issue by sven-hash** [nymtech/nym#2973]
**Describe the issue**

I try to bound a new mixnode with an already used identity key. Nothing in jail

They identity key was an old one and configuration was already been used but the mixnode was unbound for a long time

**Expected behaviour**
Bound and the mixnode stays in the explorer

**Steps to Reproduce**
Steps to reproduce the behaviour, if you're familiar with BDD syntax, please write it in this style:
- bound a new mixnode with an "old" identity key
- Wait for 1 epoch changes
- Check in the explorer and it said No mixnode found

**Which area of Nym were you using?**
- Version: Nym-mixnode 1.1.9

**Additional context**

Note, the mixnode is now unbound and we create a new identity

Concerned mixnode https://explorer.nymtech.net/network-components/mixnode/772
Identity Key: B63yxdf92RdjwEeUFouxU4x5gRpWXKorT51px8EbpQvJ

**Comment by sven-hash** [comment]
Here's the bound tx https://nym.explorers.guru/transaction/E8FB574B696213E6EAA295E3E26F6CF487ADD9DA38FEB1B380212BB4639AF4B6

Note: we create a new identity since we need a new mixnode

**Comment by tommyv1987** [comment]
Hi @sven-hash  I'll try to replicate this in one of our test environments. 

What was the mixnode version you were using previously on the old bond if you can remember?

**Comment by sven-hash** [comment]
Thanks to the blockchain, it seems it was `1.1.0`

Here's the wallet address used https://nym.explorers.guru/account/n1zar3ankmyr0wgyrueve24xryfz285ehpmnm8q6

**Comment by sven-hash** [comment]
The node disappear again,  it's impossible for us to register a new mixnode
https://explorer.nymtech.net/network-components/mixnode/773 wallet address n1zar3ankmyr0wgyrueve24xryfz285ehpmnm8q6

It's a new identity but same wallet address
We are going to try with a new wallet and new identity

**Comment by sven-hash** [comment]
Here's the bounding tx https://nym.explorers.guru/transaction/0986595E02992C003C4AF2CDE160B8FFFDC4D6AA4E85E65A858E2ABAD09509BA

**Comment by sven-hash** [comment]
And once again it's gone
https://explorer.nymtech.net/network-components/mixnode/774

Id key: ESPa5xnwZ7BebSX9SGmUbeYgNtkUeJo8PtbBx7JhzEHA
Wallet: n1q00yug4qmlzkylerep68eae475kzjr2fv484xu
Tx bound: https://nym.explorers.guru/transaction/E5FBAB89FD52D9E65B8395A7F5AA0E6331DDA6BB8FF9EADE3D01884971514001

**Comment by sven-hash** [comment]
@tommyv1987 let me know if you need more informations

It's pretty difficult to know where it come from since we don't have any errors on our side

**Comment by tommyv1987** [comment]
Hi @sven-hash.

I've checked the mixnode, and it's still actively on the network, I've just checked the validator-api and the swagger endpoint for the mixnode, and the ID is currently, blacklisted.

```curl -X 'GET' \
  'https://validator.nymtech.net/api/v1/mixnodes/blacklisted' \
  -H 'accept: application/json'
  ``` 
I'm assuming because its a new node, and the network monitor may have tried to pick a route to send packets through to your node, and it may have failed.

Let me see if anything else seems strange here.

**Comment by sven-hash** [comment]
We are going to do a modification on our side to test, maybe we have some trouble to handle the packets

Will let you know

**Comment by tommyv1987** [comment]
There is an eventually that something like this happened:
```you bonded the mixnode
network monitor happened
node got score of 0 and got blacklisted
they finally started the mixnode
```
let me know what changes you make and we will look on our side here too

**Comment by sven-hash** [comment]
Sorry for getting your time wasted @DevRel but it seems that we have problem on our side
First we looked in the jail we tought it was an ordered list so just taking a look for values around 770 and didn't see it because it was  higher and then testing with docker who's not the most suitable for the mixnet
Thanks again for your help and sorry for this
