### ISSUE TITLE
NC desktop - apps section adjustments + add monero integration

### ISSUE THREAD

**Issue by MarcinSN** [nymtech/nym#2977]
About section:
Correct copyright to 2023
![Image](https://github.com/nymtech/nym/assets/31625607/b5dba40a-e881-4a76-8684-49b74f1a6090)

Apps section:

Fonts usage and size
divider in different place
Icons

+ Add monero inegration in Wallets section

![Image](https://github.com/nymtech/nym/assets/95295201/ebd418c4-0f80-4f6f-a9b3-43cb364aba89)

Figma/nymconnect page

**Comment by doums** [comment]
copyright date fixed by https://github.com/nymtech/nym/commit/431c98e591081a1d78419166de96aaa20ce1b1ff

**Comment by benedettadavico** [comment]
Only the copyright change is going to be in release/v1.1.23 (27/07/23) 
Monero will be in the future

**Comment by jonathancross** [comment]
>  Monero will be in the future

This is the last thing I found mentioning Monero in this repo.

Can you provide more insight?

Is the Monero via socks4 integration working?
