### ISSUE TITLE
NE - fix Routing Score values shown for the gateways

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#2978]
Currently we are showing 4 different values for GW routing score on the explorer: one on the GW list page and 3 on GW details page. 

What we want to show is Routing Score computed as `routingScore: ${report.most_recent}%` on the list and the details page. And the Avg. Score computed like `avgUptime: ${report.last_day || report.last_hour}%` on the details page.

**Comment by octol** [comment]
Backend changes are complete in https://github.com/nymtech/nym/pull/3053
