### ISSUE TITLE
Split wallet rewards and vested tokens withdrawal in wallet

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#2999]
Right now there is 1 button which does two things relating to vesting tokens in the wallet. Clicking the "transfer" button under the "Unlocked transferable tokens" heading on the "Balance" page does two things at once: 

1. it transfers accrued staking rewards to liquid balance (if there are some)
2. it transfers vested tokens to liquid account balance (if there are any)

This leads to weird misunderstandings for users when they see staking rewards show up under their "vesting account". It seems like splitting the display and/or transfer functionality into two numbers would help. That *might* mean having two buttons and two numbers or it could alternately mean having one button but breaking out vesting-staking rewards and token vesting numbers into (at least) separate display fields to disambiguate what's going on here. 

There is also some other button weirdness, which we can think of as either "Problem #142" or "Problem #2" depending on how one looks at it.

**Comment by tommyv1987** [comment]
Done
