### ISSUE TITLE
[Feature Request] Add the NYM client on the website

### ISSUE THREAD

**Issue by rachyandco** [nymtech/nym#3013]
**New feature.**
Integrate the nym sdk https://www.npmjs.com/package/@nymproject/sdk into the main page of nymtech.net.
On the top of the page, a box with some basic function using the mixnet is visible to the user.

The basic version could simply loop back a message from the client through the mixnet.

additionally, using tabs, the following functions could be added:
- display of some server side information
- chat between 2 clients
- interface with pastenym.ch
- group chat 

**Where does the feature fit in the Nym real estate?**
- nymtech.net landing page

**What is this solving?**

The objective is to:
- be a demonstrator of how the SDK is easily added to a website
- allow website users to easily demo the mixnet through simple applications

**Comment by tommyv1987** [comment]
Currently binaries are no longer on the nymtech.net page since the website redevelopment, closing ticket
