### ISSUE TITLE
NE - add a filter on the gateways list page to separate the gateways running the latest versions from the older non compatible ones

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#3014]
Users might accidentally go select a gateway that is running an older version from the Network Explorer to use with NC. 

To solve that we will add a dropdown with two categories to the gateways list page (as below) so unless someone explicitly clicks on the older versions they are not shown on by default

- “Latest versions” (currently 1.1.0 and above) 
- “Older versions” (currently 1.0.X)

**Comment by fmtabbara** [comment]
- Add copy buttons to gateway identity keys
