### ISSUE TITLE
Whack old sandbox explorer and replace with one pointed to current sandbox

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#3047]
https://sandbox-blocks.nymtech.net/ is currently running but I suspect it is pointed at an old version of sandbox which no longer exists. It is not urgent, but in the next month or so sandbox is going to become more important, so it would be good to have a functioning sandbox explorer.

**Comment by farbanas** [comment]
We have https://sandbox-block-explorer.dev.nymte.ch/desmos/blocks which is linked to the new sandbox. Old sandbox will be killed with the rest of the sandbox once community has been notified about that.
