### ISSUE TITLE
[Issue] Nym Connect shows "Gateway has issues"

### ISSUE THREAD

**Issue by wiiinnie** [nymtech/nym#3136]
**Describe the issue**
Using the latest 1.1.11 version of nym-connect with my own gateway and network-requester (telegram) all in the latest version. When connecting to the gateway I get the error message above. However nym-connect does what it should and I can route my telegram traffic.

**Expected behaviour**
Expecting nym-connect to not show this error message

**Stack Traces**

**Steps to Reproduce**
- Install latest nym-connect (mac)
- Use gateway: 42XCK9dMS9m5XJLzQd2dBuwimk6ndZnczhZaV5VPFkQD
- Use service-provider: 6YqjAZK3Pr1ngiBLcDkotboB5WiN6k6NPpbXvShH4pR5.9Ss6VW3Xbyi8LuxduNNwnXEv9njHCQ2PLSP1UK6tsoa5@42XCK9dMS9m5XJLzQd2dBuwimk6ndZnczhZaV5VPFkQD
- Hit "Connect"

<img width="228" alt="Screenshot 2023-03-02 at 17 22 52" src="https://user-images.githubusercontent.com/59703082/222488835-c9454570-fe0b-4790-9643-f48c5646284b.png">

<img width="603" alt="Screenshot 2023-03-02 at 17 23 48" src="https://user-images.githubusercontent.com/59703082/222489182-5de895e7-c729-4661-bb05-a4b1513501c3.png">

**Which area of Nym were you using?**
- MacOS Ventura 13.2.1

**Comment by wiiinnie** [comment]
After various restarts it seems to work without any particular reason... 

<img width="216" alt="Screenshot 2023-03-02 at 18 29 45" src="https://user-images.githubusercontent.com/59703082/222506219-910731d2-f3bc-49fb-b2d3-f81ec43fb0d5.png">

**Comment by wiiinnie** [comment]
And the issue is back again. I also happens randomly when I use not my private gateway/service provider but one randomly chosen by nym-connect. But again, traffic is routed properly with telegram despite the shown issue.

<img width="233" alt="Screenshot 2023-03-04 at 10 23 42" src="https://user-images.githubusercontent.com/59703082/222890365-4c13a370-5636-49ff-855f-d8539507b563.png">

**Comment by octol** [comment]
That message is displayed when the connection between nym-connect and the gateway is slower than expected (but still working). So as far as I can see it's working as intended?
