### ISSUE TITLE
[Issue] mixnode's suboptimal performance

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#3144]
**Describe the issue**
The user's nym mixnode has been performing suboptimal. For the past weeks the routing score has been between 50 and 90 (see pastenym links), sometimes the score significantly drops without any clear cause.

mixnode: https://explorer.nymtech.net/network-components/mixnode/739

mixnode daemon log:  https://pastenym.ch/#/BZtXkzTC
1 day score graph: https://pastenym.ch/#/7-tbKrbx
2 days score graph: https://pastenym.ch/#/JyEABih5
7 days score graph: https://pastenym.ch/#/BkJXJRvz
40 days score graph: https://pastenym.ch/#/ENMmMxHV

Operating System: OpenBSD 7.2

Possible cause(s):

#1 IPv6
Both listening_address and announce_address are set to '37.97.150.182', but I see no ipv6 activity on port 1789, 1790 or 8000 whatsoever. I am monitoring this using "tcpdump -w /var/log/network.ipv6.pcap -nn -i vio0 ip6 and (port 1789 or port 1790 or port 8000)". Neither do I see any listening sockets on IPv6 on those ports. Could be related to https://github.com/nymtech/nym/issues/1781

#2 Log messages
There are a lot of "broken pipe" warnings (and other things) in the logs but they do not correlate with the drops in routing score. Sometimes they do. Are these anything to worry about?

#3 Version
Although he is running latest release (1.1.12 version of mixnode ((nym core platform 1.1.11))), "nym-cli mixnet query mixnodes" still shows his node running 1.1.6. This 1.1.6 is the initial version he was running when he launched his node. In the config.toml he have "version = '1.1.12'" under the "[mixnode]" header, also the log shows the correct version on startup. Should he unbond and bond again my stake? But then he will lose my single delegator, right? Also the docs (https://nymtech.net/docs/nodes/mix-node-setup.html#upgrading-your-mix-node) does not tell him to rebond when upgrading.

#4 Hardware information
When quering http://37.97.150.182:8000/hardware the string 'null' is returned instead of hardware information about the system. This is caused by the lack of OpenBSD support in the sysinfo crate. Could this have any effect on the routing score?

#5 Startup message
When user restarts his node the message "You seem to have bonded your mixnode before starting it - that's highly unrecommended as in the future it might result in slashing" appears in the log. See #3 point about rebonding when upgrading, should he also rebond when restarting?

**Which area of Nym were you using?**
 -Operating System: OpenBSD 7.2

**Comment by turb1dus** [comment]
Update:

#3 solved, need to update the information that's held in the mixnet smart contract by doing "nym-cli mixnet operators mixnode settings update-config --version <VERSION_NUMBER>".

**Comment by turb1dus** [comment]
Update:

#1 I was to quick to jump to conclusion, there is IPv6 activity
[node005_ipv6_capture.txt](https://github.com/nymtech/nym/files/10907986/node005_ipv6_capture.txt)

There are some Reset in the capture for an incoming connection. Should my node be listening on IPv6?

**Comment by turb1dus** [comment]
Update:

#2 solved Max | Nym on discord explained these are nothing to worry about.
