### ISSUE TITLE
Add current `allowed.list` to this GitHub repo and add CI action to publish it after PR and acceptance

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#3150]
We want to have a governance process to handle requests to change the `allowed.list` for Network Requesters using PRs

Needs:
- GitHub Action to validate
- GitHub Action to publish live `allowed.list` after successful review and merging

**Comment by mmsinclair** [comment]
This depends on https://github.com/nymtech/nym/issues/3149 to automatically update Network Requesters periodically

**Comment by tommyv1987** [comment]
Exit policy will now be used in the future closing
