### ISSUE TITLE
Switch nym-connect to use an exclusive health check endpoint (to allow statistics usage)

### ISSUE THREAD

**Issue by octol** [nymtech/nym#3151]
Currently nym-connect does a healthcheck http get request to `https://nymtech.net/.wellknown/connect/healthcheck.json` on connecting. This same endpoint is also used by harbourmaster. If we intend to use the nym-connect connection test as a way to get usage statistics we need to move the health check to its own exclusive endpoint

**Comment by tommyv1987** [comment]
N/A as VPN takes precedence
