### ISSUE TITLE
 [Issue] wallet closes as soon as it is opened

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#3183]
**Describe the issue**
User press start, the program window appears and immediately closes

**Expected behaviour**
opened wallet for use

**Steps to Reproduce**
Click on the launch icon and won't launch

**Screenshots**
video - https://youtu.be/gzFKMWGyLhg

**Which area of Nym were you using?**
 Windows 10 Pro version 21H2

**Comment by shypkov** [comment]
I have the same problem on win11

**Comment by tommyv1987** [comment]
@shypkov @merve64 - can you please provide me information about the build, which version it's running? where the executable was sourced from, then I can investigate further.thank you
