### ISSUE TITLE
[Issue]Do not receive NYM when buying on the wallet

### ISSUE THREAD

**Issue by hieuwb** [nymtech/nym#3194]
I have bought nym on your wallet and are required for 10 minutes to send BTC through. However, because of the transaction latency, I lost over 10 minutes and I lost BTC but did not receive Nym.
Please handle me
Tx hash: 2de140c48e5955439210950758e85517645141967b03a78532b7a94c523d0317

**Comment by rachyandco** [comment]
This issue is related to https://bity.com/ the broker that is providing the buy service. 
Please contact their support

**Comment by GarettBill** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111
