### ISSUE TITLE
[helios1] Get helios client working with `reqwest` and `socks5h://...` and using the socks5 client binary

### ISSUE THREAD

**Issue by neacsu** [nymtech/nym#3197]
- [x] make it work
- [ ] adds docs so demo works

**Comment by benedettadavico** [comment]
Errors out after sending a transaction, transaction eventually goes through but then there is this error: 
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/46782255/227583986-250f3131-5918-4393-8905-265ee649bfbe.png">
