### ISSUE TITLE
[Issue] Bash completion is broken because the banner is injected without comments.

### ISSUE THREAD

**Issue by mmoya** [nymtech/nym#3212]
**Describe the issue**
Bash completion is broken because the banner is injected without comments.

- :red_circle: `nym-client`: affected
- :heavy_check_mark: `nym-gateway`: not affected
- :heavy_check_mark: `nym-mixnode`: not affected
- :red_circle: `nym-network-requester`: affected
- :red_circle: `nym-socks5-client`: affected

```
$ (nym-socks5-client completions bash | bash)
bash: line 3: _: command not found
bash: line 4: syntax error near unexpected token `|'
bash: line 4: `     | '_ \| | | | '_ \ _ \'
```

```
$ nym-socks5-client completions bash | head -10


      _ __  _   _ _ __ ___
     | '_ \| | | | '_ \ _ \
     | | | | |_| | | | | | |
     |_| |_|\__, |_| |_| |_|
            |___/

             (nym-socks5-client - version 1.1.13)

thread 'main' panicked at 'Failed to write to generated file', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/clap_complete-4.1.1/src/shells/bash.rs:21:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behaviour**
The completion script should be parseable by bash.

```
$ (nym-socks5-client completions bash | sed -E '1,9s/^/#/' | bash) && echo ok
ok
```

**Which area of Nym were you using?**
 - Application: binaries
 - OS: Archlinux
 - Version: nym binary 1.1.13

**Comment by octol** [comment]
As far as I can tell this was fixed in #3699. I tested it locally on latest `develop` and all completions appears to be parseable by bash
