### ISSUE TITLE
[Issue] Error in nyxd build documentation for v0.26.1

### ISSUE THREAD

**Issue by Cosmin2106** [nymtech/nym#3264]
On the documentation page https://nymtech.net/docs/nodes/validator-setup.html?highlight=nyxd#building-your-validator-1, we are instructed to build `nyxd` v0.26.1 using the `go build` flag `-trimpath` which takes as argument `./cmd/wasmd`. However, the folder `wasmd` was replaced with `nyxd`, so the flag call should read `-trimpath ./cmd/nyxd` instead.

**Comment by mmsinclair** [comment]
Hi @Cosmin2106 would you mind looking at the instructions in this branch (the current validator release) and trying it out: https://github.com/nymtech/nyxd/blob/release/v0.31.1/README.md

**Comment by Cosmin2106** [comment]
@mmsinclair everything seems to be alright now!
