### ISSUE TITLE
Wallet - add missing tooltips

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#3275]
In the Gateway settings area Routing score and Average score are missing tooltips.

- For `Routing score` add "Gateway's most recent score (measured in the last 15 minutes). Routing score is relative to that of the network. Each time a gateway is tested, the test packets have to go through the full path of the network (gateway + 3 nodes). If a node in the path drop packets it will affect the score of the gateway and other nodes in the test" 

- For `Average score` add "Gateway's average routing score in the last 24 hours"

![Image](https://user-images.githubusercontent.com/31625607/229857693-1d96bd4f-5dc7-4274-8317-428d61e70d38.png)

**Comment by doums** [comment]
fixed in #3262
