### ISSUE TITLE
[Feature Request] Wallet: add regex validation on certain fields

### ISSUE THREAD

**Issue by rachyandco** [nymtech/nym#3277]
Adding a regex validation feedback to improve the usability of the wallet.

Certain fields, like the  "location" field when bonding a gateway, do not check characters that have been inputted in the text field.
Using chars like | (pipe) or - (hyphen) in the free text field, will simply result in the submit button remaining grey, without meaningful feedback.

Adding a regex validation feedback to improve the usability of the wallet.

**Where does the feature fit in the Nym real estate?**
- Wallet

**What is this solving?**
This improves the feedback to the user, and avoids failing interactions that don´t produce a coherent feedback

**Comment by tommyv1987** [comment]
I amended this and fixed this a while ago.

<img width="887" alt="image" src="https://github.com/nymtech/nym/assets/60836166/7c1029dc-08f2-4092-9a70-199c69261f64">
