### ISSUE TITLE
init command does not change version number in config.toml

### ISSUE THREAD

**Issue by sergio737446** [nymtech/nym#3336]
version 1.1.15 of nym-socks5-client and nym-network-requester have some issue in changing the version number in config.toml when the config.toml already exists in its directory. 
If the file does not exist, it is created with correct version number, but if I do the init command and the file config.toml already exists (during a version update, for example), the version number appears to be 1.1.14.
I tried to put 1.1.13 in the config.toml to see what happened, and then I did the init: the version changes to 1.1.14 instead of 1.1.15.. Thus the problem presents if I issue the init command. I noted this problem with nym-socks5-client and nym-network-requester

**Comment by octol** [comment]
This is possibly the same issue as https://github.com/nymtech/nym/issues/3434

**Comment by jstuczyn** [comment]
should be fixed by https://github.com/nymtech/nym/pull/3520
