### ISSUE TITLE
cpucycles: deploy mixnode binaries with cpucycles feature enabled and record traces to file

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#3353]
- [x] use build of latest mixnode with `cpucycles` enabled
- [x] deploy to Nym run mixnodes
- [x] collect traces as files (in `~/home/nym/.nym/logs`)
- [x] notify Ania & Simon of where trace files get created and how to collect them
- [x] @raphael-walther to send Mark a list of the identity keys
- [ ] delegate more stake to mixnodes to get them into the active set

**Comment by tommyv1987** [comment]
This was complete
