### ISSUE TITLE
Docs are inaccurate

### ISSUE THREAD

**Issue by cilphex** [nymtech/nym#337]
The "[run a mixnode docs](https://nymtech.net/docs/quickstart/run-a-mixnode/)" give this example for how to initialize a mixnode:

```
nym-mixnode init --id winston-smithnode --host 167.70.75.75 --layer 1 --location YourCity
```

However, in 0.8.0, `host` and `layer` are no longer valid arguments. Further, `gateway` is a required argument and is not mentioned.

**Comment by jstuczyn** [comment]
Are you sure you're running a mixnode? Did you build the binary yourself or got it from the release page?

 `host` and `layer` are required by a mixnode and `gateway` is required by the client only : )

**Comment by futurechimp** [comment]
That command does work for me in 0.8.0: 

```
nym/target/release$ ./nym-mixnode init --id winston-smithnode --host 167.70.75.75 --layer 1 --location YourCity


      _ __  _   _ _ __ ___
     | '_ \| | | | '_ \ _ \
     | | | | |_| | | | | | |
     |_| |_|\__, |_| |_| |_|
            |___/

             (mixnode - version 0.8.0)

    
Initialising mixnode winston-smithnode...
Saved mixnet sphinx keypair
Saved configuration file to "~/.nym/mixnodes/winston-smithnode/config/config.toml"
Mixnode configuration completed.
```

**Comment by cilphex** [comment]
Whoops, I got `nym-client` and `nym-mixnode` confused, thanks.
