### ISSUE TITLE
[Issue] 1.2.2 version of wallet hangs on Windows 10-11

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#3378]
**Describe the issue**
After updating to version 1.2.2, the program hangs on startup. User has killed the process, but on subsequent launches, it still hangs.

**Screenshots**
https://imgur.com/a/5QQ4gHI

**Which area of Nym were you using?**
Windows 10, 21H2, 19044.2846
Nym Wallet v1.2.2

**Additional context**
The user using Windows 11 got the same error, but I could not attach a screenshot because he did not create a bug report.

**Comment by tommyv1987** [comment]
hi @merve64 

we're looking into the issue, in the mean time we advise user to use the previous wallet version, thank you.

**Comment by tommyv1987** [comment]
We're now on version 1.2.11 of the wallet, and it is working on all platforms; closing the ticket
