### ISSUE TITLE
[Issue] Dockerfile for validator uses nymd instead of nyxd in path

### ISSUE THREAD

**Issue by TariqEE** [nymtech/nym#3409]
**Describe the issue**
Using the docker build instructions, the process halts with the following error:
=> ERROR [stage-1 2/4] COPY --from=go_builder /go/wasmd/build/nymd /root/nymd 

Possibly related to #2039 and #2696. 

**Expected behaviour**
The build should have completed without errors. 

**Steps to Reproduce**
Following the build instructions in docker/README.md:
clone the nym repo
cd nym
PERSONAL_TOKEN=ateststring docker-compose build

**Fix**
replace nymd to nyxd in docker/validator/Dockerfile
Build then completes without errors. I am not sure if there are other places where nymd has to be replaced with nyxd (i see references to it in scripts). I have yet to get the network up and running so perhaps more replacements are necessary.

**Which area of Nym were you using?**
 - Application: setting up a local nym network
 - OS: Ubuntu 22.04.02 LTS

**Comment by TariqEE** [comment]
Following up
There are other errors complaining about ./nyxd not found when starting the network up using 

METEOR_SETTINGS=$(cat docker/block_explorer/settings.json) docker-compose up -d --scale=secondary_validator=1

and then looking at the logs with:

docker-compose logs

Replacing the following instances of nymd to nyxd removes the errors:

1. gateway/src/config/mod.rs:    #[serde(alias = "validator_nymd_urls")]
2. service-providers/network-requester/src/cli/init.rs:    #[clap(long, alias = "nymd_validators", value_delimiter = ',')]
3. docker/validator/setup.sh:    -ldflags "-X github.com/cosmos/cosmos-sdk/version.Name=nymd \
4. docker/validator/setup.sh:    -X github.com/cosmos/cosmos-sdk/version.AppName=nymd \
5. docker/validator/setup.sh:    -X github.com/CosmWasm/wasmd/app.NodeDir=.nymd \
6. docker/validator/init_and_start.sh:  if [ ! -f "/root/.nymd/config/genesis.json" ]; then
7. docker/validator/init_and_start.sh:  if [ ! -f "/root/.nymd/config/genesis.json" ]; then

**Comment by mmsinclair** [comment]
Hi there @TariqEE - are you using the `Dockerfile` from https://github.com/nymtech/nyxd/blob/release/v0.31.1/Dockerfile or https://github.com/nymtech/nym/blob/develop/docker/validator/Dockerfile ?

If you are using https://github.com/nymtech/nym/blob/develop/docker/validator/Dockerfile we might remove that to avoid confusion.

**Comment by TariqEE** [comment]
Hello @mmsinclair, 
I ran docker-compose from the root of the nym project dir (as according to the README in the nym/docker dir). Looking at that file (docker-compose.yml) it looks like it refers to https://github.com/nymtech/nym/blob/develop/docker/validator/Dockerfile for the validator portion of docker-compose.

Please let me know if there is another (more correct) way to be getting things going with docker?

Thanks for your help!

**Comment by tommyv1987** [comment]
Hi @TariqEE, sorry for the delay in responding. Are you still looking to use Docker for your tasks, if so let me know and I can be of assistance.
