### ISSUE TITLE
name-service contract: make it mainnet ready

### ISSUE THREAD

**Issue by octol** [nymtech/nym#3415]
Meta ticket to track progress into making the name service contract ready for mainnet

- [ ] Require signing for adding entries #3361 
- [ ] Add support for gateway entries? #3382 
- [ ] Experience using it on qwerty (client support etc)
- [ ] Extensive testing
- [ ] Audit?
- [ ] Suitable deposit required
- [ ] Admin ability to remove entries?

**Comment by tommyv1987** [comment]
no longer needed
