### ISSUE TITLE
[Issue] issue creating password in Nym wallet

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#3436]
**Describe the issue**
Creating a password in Nym Wallet for an account previously created using mnemonics only is currently problematic. Users are unable to change their password because there is no existing password associated with the account. This issue negatively impacts the user experience.

**Expected behaviour**
Users should be able to create a password for their Nym Wallet account even if it was originally created using mnemonics only without necessity to manually delete saved-wallet.json file. 

**Steps to Reproduce**
 1.  Open Nym Wallet.
 2. Create an account with mnemonics AND a password
 3. Sign out from the account
 4. Create a new wallet with mnemonic but WITHOUT a password
 5. Navigate to the settings menu.
 6. Locate the option to change the password.
 7. You will not see an option to create a password (only to change the existing one). 

*An example:*
- Given I was setting up a mix-node following the instructions in the docs
- And I successfully bonded my node via the the wallet
- When I went to start my mixnode
- Then I was presented with an error

**Screenshots**
https://imgbox.com/8GcipGEc
https://imgbox.com/c3qrIcul
https://imgbox.com/vzACSSfF

**Which area of Nym were you using?**
macOS and Windows 10, wallet Version 1.2.3 and earlier

**Additional context**
The manual workaround that has been suggested involves deleting the saved wallet file from the following directory: C:\Users<YOURUSER>\AppData\Local\nym-wallet\saved-wallet.json.

**Comment by mmsinclair** [comment]
@benedettadavico this should hopefully be fixed now, mind checking?

**Comment by benedettadavico** [comment]
this has been temporarily resolved, user will need to log out and follow the "forgot my password" flow to create a password
