### ISSUE TITLE
Log domain in proxy messages + logging cleanup

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#344]
Right now we get messages like this:

```
2020-09-21T12:25:43.322 INFO  proxy_helpers::proxy_runner                                                                 
> Going to write 305 bytes received from mixnet to connection 8067112332930573650. Is remote closed: false
```
It would be a lot nicer to have the domain name instead of the remote id in messages like that. I think we can also reduce the log level for a lot of those messages, so there are less of them. 

Ideally, at default log levels we would just see "X bytes request to domain.com", "X bytes received from domain.com".

**Comment by futurechimp** [comment]
If this is a speedy one, let's do it in 0.9, if not let's bump it to 0.10 - it won't fix the network for us any quicker :).

**Comment by jstuczyn** [comment]
This one seems to have already been done at some point, but those messages are only shown at `debug` level to not make them too obtrusive as there's a lot of them. I could increase that if you wanted.
