### ISSUE TITLE
🍄Website update - menu desktop&mobile - DONE

### ISSUE THREAD

**Issue by MarcinSN** [nymtech/nym#3440]
DESKTOP

- [x] Icons in drawer categories - centered (like pdf or external link)
- [x] Jumping menu after underline hover - static postion all the time
- [x] When menu is opened you don't see background under during category switch
- [x] Indication where you are - currently only on hover you see underline of category, we need to keep underline when drawer is opened
- [x] Spacing - bottom and top padding of drawer should be equal in all categories
- [x] Hover efect in subcategories - 80% of white
- [x] Delete language dropdown
- [x] When you click on Community in top menu you should be transferd to community page(this is not in a doc)
- [x] Add Staking external link Use Nym/For Staking, Staking link: https://blog.nymtech.net/staking-in-nym-introducing-mainnet-mixmining-f9bb1cbc7c36

Jaya
- [x] Add Developer portal(external) to Build category under Developers
Link: https://nymtech.net/developers/

MOBILE
- [x] We need alignment here + spacing + sub categories like it is in desktop, lenght and color of dividers and content
- [x] Fix animation when you are closing mobile menu - to right top corner - no animation better probably
- [x] Closing X with rounded corners(now we have sharp edges)
- [ ] In Build category, Spacing between Build and categories should be smaller like in Learn for example
- [ ] We are showing only menu. No background should be visible. Full black bacground and menu only

NICE TO HAVE
- [x] Add icons to social media links in menu

![Image](https://github.com/nymtech/nym/assets/95295201/5972775b-0105-4632-85ff-508a7860310f)

**Comment by gala1234** [comment]
All has been done 





https://github.com/nymtech/nym/assets/33252067/72b97c5d-1839-4982-bc80-85dd26b2b605
