### ISSUE TITLE
🍄Website update2 - Homepage desktop&mobile - ui ready (iphone scroll not)

### ISSUE THREAD

**Issue by MarcinSN** [nymtech/nym#3441]
DESKTOP

- [x] Spacing of category in latest in nym section, distance between picture and text + use body2 font size for titles
- [x] Lack of hover effect on buttons in hero and download wallet section
- [x] Roadmap - separator disappears
- [x] Footer - add mission
- [x] Footer - add Gateways and service requesters to build
- [x] Add Team to About

MOBILE

- [x] Movie from left to right no radius on corners
- [x] Mobile footer - alignment
- [x] Visible scroll for nym in media and Backers sections

JAYA

- [x] Check if roadmap subcategory is scrolling site to roadmap section

**Comment by gala1234** [comment]
Visible scroll for nym in media and Backers sections is working fine on desktops and some mobiles, but not on iPhones, I need to investigate further
