### ISSUE TITLE
🍄Website update3 - About category - Mission, Mixnet, Zk-Nyms, Token - ui ready

### ISSUE THREAD

**Issue by MarcinSN** [nymtech/nym#3445]
**Mission**

- [x] Text style - paragraph we should use H5

JAYA
- [ ] New way to show links in boxes - comment made by Jaya - design in Figma
- [x] Visit jobs proper link: https://nym.teamtailor.com/#jobs
- [x] Delete text "Nym software is..."
- [x] Delete the full stop in the subheaders pls? So “To prevent operators from selling the customer” (delete the “.”)

**Mixnet**

- [x] FAQ Spacing and text style from figma
- [x] FAQ paste proper copy from figma for this question "How does Nym Compare to VPNs?"

JAYA

- [ ] New order of sections - look figma or doc
- [ ] New design of USP section - like in mission - in doc& figma there is also new text for these sections
- [x] Update Gif with comparison - take from Pablo HQ version
- [x] Blue Section about Mixnet explorer
- [x] New text for last sections squares Token and Build - check with figma, text below - Jaya update

Token
Learn about NYM token incentives
The NYM utility token is the native token of the mixnet. Learn how to bond a node or delegate stake to start earning rewards!

Build
Integrate the mixnet or build apps on top of Nym
Find out how to integrate the mixnet into your wallet, app or blockchain to protect your users IP address and patterns of communication.

**zk-nyms**
DESKTOP

- [x] font size - Gala let’s check this one more time in titles below hero section we are using h1 instead of h2
- [x] Spacing and alignment of icons& text in boxes
- [x] Add button to docs in last section - Build with zk-nym credentials
- [x] Delete squares for icons from Privacy properties of zk-nyms include: section. For now this section will be without icons

JAYA

- [ ] Hero copy change to: "Enabling users to prove their right to access digital content, apps and services without having to reveal sensitive information."
- [ ] Change copy in Self-sovereign identity box to: “Prove aspects of your identity while retaining privacy, using Zero Knowledge Proofs of private attributes. For example, prove you are above a certain age without revealing your actual birth date.”

MOBILE

- [x] Spacing between usp boxes
- [x] alignment in grey section

**Token**
- [x] Spacing and alignment of icons& text in boxes
- [x] Check with Jaya if top TOKEN hero copy is correct
- [x] In key informations section, link should be opened in new tab
- [x] In key informations section mobile let's break the line to keep left&right padding
- [x] FAQ spacing and sytles and alignment of whole container + same in mobile
- [x] Sharp corners of Chart containers
- [x] Alignment to left: Backers, MIx-minning Team
- [x] Confirm with Jaya text to bottom squares - token and build
- [ ] Hero, video instead of illustration

**Comment by gala1234** [comment]
@MarcinSN regarding this one " font size - Gala let’s check this one more time in titles below hero section we are using h1 instead of h2" I've been using the main component, as they were linked to it, I'm going to create a parameter called `isSecondary` to fulfils these cases

this is the main component:



![Image](https://github.com/nymtech/nym/assets/33252067/7f515dc7-8a57-4946-b389-0c3598d32927)

**Comment by gala1234** [comment]
@MarcinSN same thing happens with the `transfer sections` the main component has another padding, font size, and structure...
I'm going to use some parameters, but if the parameters number keeps growing maybe worth to create a new component for this transfers with icons

this is the main component for the `transfer sections`:


![Image](https://github.com/nymtech/nym/assets/33252067/1420c97a-2d0d-44c8-b61c-a1fdf9cf8911)
