### ISSUE TITLE
🍄Website update4 - Use Nym category - NymConnect&Wallet - DONE

### ISSUE THREAD

**Issue by MarcinSN** [nymtech/nym#3446]
**NymConnect**
- [x] Proper screens of NC in hero image- screen is in figma
- [x] main download button should transfer to download section, currently it's going to google.es
- [x] Alignment in download containers
- [x] Add buttons to last sections Token and Staking
- [x] Confirm with Jaya Token and Staking text

**Wallet**
- [x] main download button should transfer to download section, currently it's going to google.es
- [x] Alignment in download containers
- [x] Add buttons to last sections Token and Staking
- [x] Update text for Token and Staking

**Comment by gala1234** [comment]
@MarcinSN we need to know where `Staking` link should drive

**Comment by gala1234** [comment]
@MarcinSN , in my opinion the wallet img doesn't look very well would be better a png with transparency, maybe you already asked it to Pablo, but just in case


![Image](https://github.com/nymtech/nym/assets/33252067/648f22d7-8113-4e09-8bd2-b50449f94380)
