### ISSUE TITLE
🍄Website update5 - Build category - Mixnodes, Gateways, Service requestors - DONE

### ISSUE THREAD

**Issue by MarcinSN** [nymtech/nym#3447]
**Mixnodes, Gateways, SR**
- [x] Mixnodes Doc link: transfer to: https://nymtech.net/docs/nodes/mix-node-setup.html
- [x] Gateways Doc link: transfer to: https://nymtech.net/docs/nodes/gateway-setup.html
- [x] Service requestors Doc link: transfer to: https://nymtech.net/docs/nodes/network-requester-setup.html
- [x] Center structure title
- [x] Add Blue section with nym explorer - CONFIRM WITH JAYA
- [x] Open nym explorer link in new tab
- [x] In Service providers and link to Dev grants -> beside check docs link
- [ ] Last section with explorer, need more bottom padding, to close to footer :)

**Comment by gala1234** [comment]
we need the `dev grands` link

UPDATED: we have it https://shipyard.nymtech.net/grants/
