### ISSUE TITLE
🍄Website update6 - Learn category - Papers - ui ready, only cms work: we papers for all these categories

### ISSUE THREAD

**Issue by MarcinSN** [nymtech/nym#3448]
Papers

- [x] Styles, text sizes - Figma styling
- [x] Dropdown after selection shouldn't be active anymore. You have to click outside dropdown to unselect

Jaya

- [x] Change categories to "papers"
- [x] add categories below papers, Privacy,Mixnet,Token economics,zk-nyms,Optimisation (design in figma)

**Comment by gala1234** [comment]
`Dropdown after selection shouldn't be active anymore. You have to click outside dropdown to unselect` It is the mui default behavior, to change it is not as clean, I'll do it on a second iteration

**Comment by gala1234** [comment]
The categories are added in the cms, I need to know which category each paper should be linked to
