### ISSUE TITLE
Load configuration from environment variables

### ISSUE THREAD

**Issue by snek** [nymtech/nym#345]
Right now the nym-mixnode command loads the configuration from the config.toml and can be overridden using arguments passed to the command.

This makes the configuration less ideal on platforms like Docker and Kubernetes where it's customary to load configuration through environment variables. 

Maybe an idea to move away from a toml file and use a `.env` file for development and use environment variables in production (if `.env` file is not present or override it's contents with the value from the environment)?

**Comment by yuliyantsvetkov** [comment]
This is not true. Only the one that does not know how can load config file from ConfigMap can say that. 

Its pretty easy in k8s, and also in Docker. FYI https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/

You can dynamically create ConfigMaps with tools like Helm, and re-use them. Not a big deal.

**Comment by tommyv1987** [comment]
Ticket no longer applicable, an example of using a config map is as follows (this is an outdated picture here)

<img width="1017" alt="image" src="https://github.com/nymtech/nym/assets/60836166/a925d98d-df70-4cf4-af6a-ec4acbc0b525">
