### ISSUE TITLE
Integrate init into the run command or get rid of it completely

### ISSUE THREAD

**Issue by snek** [nymtech/nym#346]
Would it not be possible to run the init underwater when nym-mixnode is run instead of having to run the init command?

It makes deployment much more complex for Docker & Kubernetes having to run a separate command because ideally a Docker container should only ever run 1 command.

So checking to see if pem files are available and if all configuration is set, otherwise run init first (or just output how the command should be run properly).

**Comment by futurechimp** [comment]
Hi @snek at the moment `init` tells the node what host it's running on (its IPv4 or IPv6 address) and also it lets the user give it an id (useful for seeing in a human-readable way what different node configurations exist if there are more than one). 

It also generates cryptographic keypairs for each node instance. 

Simplifying node running is an interesting idea. @jstuczyn let's have a chat in here about whether we could remove the `init` command. Concretely I guess we'd need to:

- remove `init`
- make the parameters to `run` take the `host`, `location`, and `id` as optional parameters
- automatically detect the IP address of the host. We could do this by hitting an external service to retrieve the public IP of the node (and in fact it'd be more accurate than having people try and figure it out themselves given the complexity of doing it correctly on some hosting services). We could also set the node location from this. Values returned would then be automatically written to the configuration file. There would still be the option to set them manually.
- generate keys if they weren't there (on first run)
- use a default `id` like "nym-mixnode" unless the user set it explicitly

There may be problems with this that I haven't thought through, let's try and figure that out together so we don't code ourselves into a corner.

@snek is that sort of what you're after?

**Comment by snek** [comment]
@futurechimp Yeah that should simplify things considerably. 

The only problem I can see right now is with Kubernetes where hitting an external service to get the ip will actually return the host ip and not the service ip which should probably be used. However, this is a very specific case and using an external service if an ip is not configured would solve the problem for large portion of the mixnodes I think.

**Comment by tommyv1987** [comment]
this has been simplified, and the process revolves around nym-nodes now. closing this ticket as it's a legacy now.
