### ISSUE TITLE
[Issue]The ports listed in the firewall config to build a network requester might need edits

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#3468]
**Describe the issue**
the ports listed in the firewall config to build a network requester might need edits:

https://nymtech.net/docs/nodes/network-requester-setup.html#configure-your-firewall

`sudo ufw allow 1789,22,9000/tcp`

why does it require the others beside 9000? Network requester only need connection to gateway, not to mixnodes right?

**Expected behaviour**
this is what should be needed based on requester port preference: https://nymtech.net/docs/nodes/network-requester-setup.html#requester-port-reference

**Steps to Reproduce**
1. go to the docs: https://nymtech.net/docs/nodes/network-requester-setup.html#configure-your-firewall
2. view how to open your requester’s p2p port: `sudo ufw allow 1789,22,9000/tcp`

**Screenshots**
https://imgur.com/rz8IthV

**Comment by mfahampshire** [comment]
@merve64 there is already a PR in for this. Closing.
