### ISSUE TITLE
[Issue] Wallet: Race condition on opening Bonding view

### ISSUE THREAD

**Issue by nadimkobeissi** [nymtech/nym#3490]
## Steps to reproduce

1. Open Nym Wallet, log in, etc.
2. Click on "Bonding" in the left sidebar
3. About half the time, the bonded Nym mixnodes won't show, and I have to navigate back to Balance and again to Bonding. This is likely a race condition of some sort.

## Expected behavior

Bonded Nym mixnodes should show every time.

**Comment by tommyv1987** [comment]
This has been addressed already, and has been prioritised to be fixed. Closing this ticket. In favour of existing issue.

**Comment by nadimkobeissi** [comment]
@tommyv1987 Thanks! Sorry for the duplicate issue.

**Comment by jessgess** [comment]
Issue is solved in wallet v1.2.4
