### ISSUE TITLE
[Feature Request] Nym Wallet: Total delegations field needs clarification

### ISSUE THREAD

**Issue by katerina510** [nymtech/nym#3492]
**Is your feature request related to a problem? Please describe.**

On the Delegation tab, there are fields **Total delegations** and **New rewards**. According to the tooltip, Total delegations are "the total amount you have delegated to node(s)". Total delegations do not change until you delegate more, despite the fact that they should increase every hour because of auto-compounding of rewards. This is misleading.

When you click **Delegate** button and add more tokens, at the start of the new epoch all **New rewards** move to **Total delegations**.  This is also misleading, because looks like the rewards have just been delegated instead of being auto-compounded all the time. 

Community members don't understand why total delegations do not grow in the wallet and, on the other hand, the rewards grow. A lot of questions about it in the chats.

**What can be done**

The real total delegations should be **Total delegations** + **New rewards**. It would reflect the fact that rewards are auto-compounded.

**Where does the feature fit in the Nym real estate?**
- Application / UI 

**What is this solving?**

Making the app more user-friendly and reducing the confusion

**Comment by jessgess** [comment]
Hi there, this issue should have been solved in the previous release. Please have a look and let us know your feedback if any!
