### ISSUE TITLE
Error installing nyms5-android

### ISSUE THREAD

**Issue by AsteroidusTv** [nymtech/nym#3500]
**Describe the issue**
I downloaded Nym connect mobile [here](https://github.com/nymtech/nym/releases/tag/nyms5-android-v1.0)  but during the installation I have this message "App not installed as package appears to be invalid"

**Expected behaviour**
I was expecting the installation to succeed.

**Steps to Reproduce**
Download Nym-Connect android from github and try to install it

**Screenshots**
![Screenshot_2023-06-03-10-30-14-07_3d73e98b1ad3bd2575f7a56513d89a0c.jpg](https://github.com/nymtech/nym/assets/113026499/a7d01c0f-81ea-457b-87cd-e6bec1097d00)

**Which area of Nym were you using?**
 - UI: [Android Nym-connect]
 - Application: [Android Nym-connect]
 - OS:[Realme Ui Android 13]
 - Version: [v1.0]

**Comment by rachyandco** [comment]
this is noticed by several people in telegram

the previous version https://nymtech.net/nyms5-arm64-v8a-debug.apk does not have this issue

**Comment by sven-hash** [comment]
Not working on Android 13, OS IodéOS 4.0

**Comment by dannycanaan** [comment]
I have the same issue when trying to install v1.0 on Android version 12L, CPU type aarch64

the previous version nyms5-arm64-v8a-debug.apk works

**Comment by rachyandco** [comment]
working on Android 10
