### ISSUE TITLE
[Issue] version mismatch between the compiled and published release 

### ISSUE THREAD

**Issue by rachyandco** [nymtech/nym#3533]
After version 1.1.6 of the Nym Binaries, there is a version mismatch between the compiled release and what is published on GitHub.
The latest GitHub release 1.1.20 contains binaries compiled 1.1.21.

If you run a script looking for the version higher than the one installed, it doesn't work at all without introduce this mismatch.  Users are confused by having to put a different version on the wallet than the one they're downloading from GitHub same for config.toml file.

Would it be possible to release again the same compiled version so that it matches the version on GitHub again, like versions 1.1.6 and earlier?

(Pasted on the request of Nym French community member)

**Comment by mmsinclair** [comment]
Each binary has its own version. We will soon be moving from semver release branch names to weeks of the year to avoid confusion.
