### ISSUE TITLE
🍄Website TEAM FEEDBACK

### ISSUE THREAD

**Issue by MarcinSN** [nymtech/nym#3549]
- [ ]-lack of 2023 in roadmap

![Image](https://github.com/nymtech/nym/assets/95295201/031da5f5-6ab8-4299-848f-6fbd4c5ac5b4)

**TEAM**

- [ ]-Correct Alexis title: Chief Operating Officer

![Image](https://github.com/nymtech/nym/assets/95295201/17b336fd-e632-44a3-8c92-adeeafe3fe8d)

- [ ]-Correct Alexis linkedin link: https://www.linkedin.com/in/alexis-roussel-01993143/

- [ ]-After newsletter, let's change this text to: Confirm your email address to complete subscription - smaller text could be 12px

![Image](https://github.com/nymtech/nym/assets/95295201/785b7fb2-2243-45ff-9cae-c6eba5b4bfc4)

**Comment by tommyv1987** [comment]
No longer needed.
