### ISSUE TITLE
SDK: build package for NodeJS

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#3558]

**Comment by etimofeeva** [comment]
Hello, do you maybe need help for sdk tasks? I am a huge fan of project and would be happy to help in any way: documentation or open source

**Comment by mmsinclair** [comment]
Hi there @murluki - we are going to make a NodeJS compatible package, would you be up for trying it out when it is ready? Or possibly creating an example app with it, or even giving us some feedback on the documentation?

**Comment by etimofeeva** [comment]
> Hi there @murluki - we are going to make a NodeJS compatible package, would you be up for trying it out when it is ready? Or possibly creating an example app with it, or even giving us some feedback on the documentation?


Hi @mmsinclair, sure, I am currently developing apps/ trying out things using existing sdk so would be excited to do it!
