### ISSUE TITLE
SDK Examples: create a NodeJS mixnet client example

### ISSUE THREAD

**Issue by mmsinclair** [nymtech/nym#3563]
Create a directory in https://github.com/nymtech/nym/tree/develop/sdk/typescript/examples/mix-fetch called `node-js` and then add:

- Express example
- ESM example

 Also add this browser example to docs to display here (https://sdk.nymtech.net/playground/mixfetch):

- - browser example for fetching coingecko NYM entry

**Comment by sebastinez** [comment]
This has been added with commit 06a96fa
