### ISSUE TITLE
[Issue] Error when starting nym-mixnode without root perms

### ISSUE THREAD

**Issue by craftdome** [nymtech/nym#3579]
**Describe the issue**
Error when starting nym-mixnode without root perms.

**Expected behaviour**
Starting in normal mode.

**Stack Traces**
Command: RUST_BACKTRACE=1 ./nym-mixnode run --id <your id>
Output:
```
nym_mixnode::node > Starting nym mixnode
 2023-06-20T11:03:27.229Z ERROR nym_mixnode::node > failed to grab initial network mixnodes - nym api request failed - There was an issue with the REST request - error sending request for url (https://validator.nymtech.net/api//v1/mixnodes): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1919: (unable to get local issuer certificate)
 Please try to startup again in few minutes
```

**Steps to Reproduce**
./nym-mixnode run --id mixnode

**Screenshots**
`wget https://validator.nymtech.net/api//v1/mixnodes`
- no problems

![изображение](https://github.com/nymtech/nym/assets/21179689/f27d4a21-bf82-4a87-aa95-6083cd0f3818)

`wget https://gnu.org/`
- no problems

![изображение](https://github.com/nymtech/nym/assets/21179689/1c96459d-91d9-45db-acfd-8ad10e951619)

**Which area of Nym were you using?**
 - Application: Mixnode
 - OS: Debian 11 amd64
 - Version: 1.1.22 https://github.com/nymtech/nym/releases/download/nym-binaries-v1.1.22/nym-mixnode

**Additional context**

Clear debian 11, with apt update && apt upgrade.

The launch is unsuccessful only when launched from a regular user.
Create command: `useradd -m -G adm,cdrom,sudo -s /bin/bash user`

Everything was fine here: https://github.com/nymtech/nym/releases/download/nym-binaries-v1.1.20/nym-mixnode

Good works with root user.

**Comment by sven-hash** [comment]
You have to change the path in the config.toml because it try to load the pem from /root

**Comment by craftdome** [comment]
> You have to change the path in the config.toml because it try to load the pem from /root

This is not true

![изображение](https://github.com/nymtech/nym/assets/21179689/546038e4-5f2f-416d-8c33-1074a8e5eb91)

**Comment by sven-hash** [comment]
Yes, you're right I didn't read well your problem

It was about the certs, please ignore my comment

**Comment by mmsinclair** [comment]
Hi @Tyz3 the error reported is `unable to get local issuer certificate` - would you mind checking if updating your Root CA OS package makes any difference?

**Comment by tommyv1987** [comment]
No response from user closing ticket, responding to the ticket will enable us to investigate further.
