### ISSUE TITLE
Commercial - Collect fiat payment (via Stripe) and convert it to NYM and then credentials for access to NC

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#3583]
- [ ] generate keypair in the browser - this can be a Cosmos keypair ed25519 (https://cosmos.github.io/cosmjs/latest/crypto/classes/Ed25519.html#makeKeypair) or a plain x25519 keypair (https://www.npmjs.com/package/x25519-key-pair)
- [ ] use a QR code to transfer the keypair from the browser to a mobile app
- [ ] encode keypair in a Universal URI to opens the desktop app to transfer the key (nothing must leave the user's computer i.e. URL is in the user's browser and opens the app on the user's computer, no API/pastebin is required)

https://developer.apple.com/documentation/xcode/supporting-universal-links-in-your-app
https://learn.microsoft.com/en-us/windows/uwp/launch-resume/web-to-app-linking

QR codes:
https://github.com/zxing/zxing
https://developer.mozilla.org/en-US/docs/Web/API/Barcode_Detection_API

Also, an option is to convert the ed25519 signing key into an x25519 encryption key, using something like this: https://github.com/nazar-pc/ed25519-to-x25519.wasm (we should write Rust code that does that same thing)

**Comment by neacsu** [comment]
Pushed to a WIP branch for handling external URL application start: https://github.com/nymtech/nym/tree/feature/payments_wip
Created a nym payment repo in gitlab, named `nym-connect-stripe-payments`
