### ISSUE TITLE
[Issue]  BETA NymConnect (mobile) " App not installed"

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#3592]
**Describe the issue**

BETA NymConnect (mobile)
User tried to install on  these 2 devices:
Tablet Samsung Galaxy Tab A (2016) Android 8.1.0
Phone Samsung  Galaxy A10s Android  11
Both with debug on and with "app from other source different than Google play store" enabled
More, the tablet was reset to the condition of "new device" using the specific directions
On both devices he had "App not installed" when clicking on the apk file (I tried nyms5-arch64-release and  nyms5-arm64-v8a-debug.apk too) almost at the end of the installation

He tried latest release https://github.com/nymtech/nym/releases  but the result was the same 

**Expected behaviour**
Connection without error

**Screenshots**
n/a

**Which area of Nym were you using?**
Tablet Samsung Galaxy Tab A (2016) Android 8.1.0
Phone Samsung  Galaxy A10s Android  11

**Comment by doums** [comment]
- `Tablet Samsung Galaxy Tab A (2016) Android 8.1.0` we do not (officially) support tablets for now
- `Phone Samsung Galaxy A10s Android 11` is arm64 and install should just work

Sadly I have no clue why it's not, and there are no useful info here to help :/

**edit** just checked again on emulator with android 11, app just run fine

**Comment by sergio737446** [comment]
Hello, I am the user who is trying with tablet and samsung a10s. Since doums spoke about emulator, I can try to do the same (windows 11 and bluestack may be good?)

**Comment by doums** [comment]
Hi, running the app on the emu yourself will not really help with the issue.

**Comment by tommyv1987** [comment]
This is no longer needed as focus has shifted to the VPN
