### ISSUE TITLE
Speedy mixnet - Setup list of network-requesters and make NymConnect S select from them

### ISSUE THREAD

**Issue by octol** [nymtech/nym#3607]
Similar to https://nymtech.net/.wellknown/connect/service-providers.json we need to setup a list of network-requester with the "medium" toggle enabled. And make nym-connect select from these.

**Comment by jessgess** [comment]
@octol Can't we just have the existing network requesters to support both modes? Doesn't seem feasible to add yet another set of network componets.

**Comment by octol** [comment]
> @octol Can't we just have the existing network requesters to support both modes? Doesn't seem feasible to add yet another set of network componets.

Currently there is a pretty deep assumption about a single mode of operation (Poisson rate, delays etc) throughout client-core. Also, it would require the requesting client to inform the network-requester about how it should respond, which would require breaking backwards compatibility on a number of request types
