### ISSUE TITLE
WEBSITE V2

### ISSUE THREAD

**Issue by MarcinSN** [nymtech/nym#3611]
Mission

- [ ] New way to show links in boxes - comment made by Jaya - design in Figma(jobs, run node and community)

Mixnet

- [ ] New order of sections - look figma or doc
- [ ] New design of USP section - like in mission - in doc& figma there is also new text for these sections

**Comment by roughprada** [comment]
Moved to GL:
- Mission screen: https://gitlab.nymte.ch/nym/nym-websites/-/issues/24
- Mixnet screen: https://gitlab.nymte.ch/nym/nym-websites/-/issues/25
