### ISSUE TITLE
Add instruction to use Matrix's Element client using NymConnect

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#3621]
NymConnect now supports Matrix chat protocol. Currently there is no UI in Matrix's Element client to set a socks5 proxy. So in order to use Element via NymConnect users have to start it from the commandline with ```element-desktop  --proxy-server=socks5://127.0.0.1:1080```

**Comment by serinko** [comment]
Done:

https://nymtech.net/developers/tutorials/matrix.html
