### ISSUE TITLE
Client running out of SURBs

### ISSUE THREAD

**Issue by octol** [nymtech/nym#3627]
Getting reports from users that the client is running out of SURBs

> What can we do when this happen on the nym-client service provider side ? 
> We send 100 SURB in each sendMessage 
> `2023-06-28T20:04:48.978Z WARN nym_client_core::client::replies::reply_controller > failed to request additional surbs... - Not enough reply SURBs to send the message. We have 0 available and require at least 1.`

**Comment by octol** [comment]
Something to try is to increase threshold when more surbs will be requested. Default is 10.
```
[debug.reply_surbs]
minimum_reply_surb_storage_threshold = 20
```

**Comment by sven-hash** [comment]
New "error"
`nostr-nym-nym-client-1  |  2023-07-08T13:48:38.972Z WARN  nym_client_core::client::replies::reply_controller                            > received reply request for AnonymousSenderTag([134, 154, 44, 170, 54, 93, 170, 28, 149, 134, 209, 120, 81, 30, 13, 171]) but we don't have any surbs stored for that recipient!`

**Comment by mfahampshire** [comment]
A small note to chip in: +1 on increasing the threshold; even when sending relatively small responses to and fro I see requests for more SURBs in my logs.

**Comment by mfahampshire** [comment]
Up SURBs for standalone clients + sdks.

**Comment by mfahampshire** [comment]
@jstuczyn raised the point that this might not be the number of SURBs, but instead using SURBs to request more SURBs off a client that has disconnected, thus never receiving more but depleting your supply whilst requesting them.

**Comment by mfahampshire** [comment]
Although in theory this should stop this from happening? https://github.com/nymtech/nym/blob/6d2d8ce1495f0208f6701e619d4afe0a905a3e8d/common/client-core/src/config/mod.rs#L599C58-L599C58
