### ISSUE TITLE
Introduce service providers to network topology

### ISSUE THREAD

**Issue by jstuczyn** [nymtech/nym#363]
It should be possible to optionally publicly announce service provider in the network. It would presumably specify its [client] address, perhaps what it offers and the interface used. So say for our socks5 provider it would specify address of client its using to interface with the mix network, that it's offering socks5 access to crypto wallets and that you must follow socks5 API.

**Comment by tommyv1987** [comment]
I believe this would be harbourmaster, but as Mark indentified:

```
the habour master's functionality needs to be moved entirely to the Nym API, it is part of work for Directory Services v3 that takes into account the new network structure that has exit nodes (with internet routing)
```
So will close this ticket in lieu of the work that needs to be done here
