### ISSUE TITLE
[Issue] Nym wallet throws error when switching to sandbox

### ISSUE THREAD

**Issue by pwnfoo** [nymtech/nym#3631]
**Describe the issue**
Nym wallet throws an error when switching to sandbox

**Expected behaviour**
Wallet is supposed to switch to sandbox

**Stack Traces**

```
Tendermint RPC request failed - HTTP error Caused by: error trying to connect: dns error: 
No such host is known. (os error 11001) 
Location: C:\Users\nymtech\.cargo\registry\src\index.crates.io-6f17d22bba15001f\flex-error-0.4.4\src\tracer_impl\eyre.rs:10:9
```

**Screenshots**
![image](https://github.com/nymtech/nym/assets/9546091/2ebe83af-375e-4315-99a3-5dc2990b1433)

**Which area of Nym were you using?**
 - Application: Wallet
 - OS: Windows 11
 - Version: nym-wallet 1.2.4

**Comment by mmsinclair** [comment]
Thanks for the report @pwnfoo - we are rebuilding the sandbox environment currently and the DNS is not pointing at the correct environment. Hopefully we can fix that up this week. Will let you know when it is fixed.

**Comment by tommyv1987** [comment]
I'm going to close this ticket, as everything should be up and running within the next day or two.
