### ISSUE TITLE
[Feature Request] nym-wallet | Remove or rename "Accounts"

### ISSUE THREAD

**Issue by silent-nox** [nymtech/nym#3643]
**Is your feature request related to a problem? Please describe.**

- As a Nym-wallet user,
- I want to be able to:
	- remove.. 
	- rename..
	- .. existing, already created "accounts" from my nym wallet
- So that I can keep my accounts organized and avoid any misidentifications, misusage of the wrong one.

**Is your request a feature not related to an existing problem? A new feature.**
For example. 
- Given I am using the nym wallet
- When I open a previously created wallet
- Then I want to have the possibility to rename or remove "Accounts"

**Where does the feature fit in the Nym real estate?**
- Nym-wallet

**What is this solving?**
It will provide basic possibilities of removing and renaming "accounts" in the locally created wallet.
It will remove the pain for users if they've done a mistake, to create a brand new wallet from scratch with all seeds.

**Is this an update to packages or libraries?**
If so, please list them. If not, please ignore this section.

**Describe alternatives you've considered**
Provide the local path/files where the wallet information are stored to be able to edit them manually without the GUI.

Others:
- The first time we create a wallet, the first account is called "Account 1" and cannot be renamed.

**Comment by tommyv1987** [comment]
The latest wallet versions have the ability to rename accounts name. closing the tickets as the task is complete
