### ISSUE TITLE
[Issue] NymConnect could not connect

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#3682]
**Describe the issue**

NymConnect has been giving this error:
https://paste.pics/OTCK3

when user tries to manually select service provider, he doesn't get the input field to do so:
https://paste.pics/OTCK8

the log window is empty, and after opening it it is uncloseable, and the connect button stops working (User can highlight text such as "YOU ARE NOT PROTECTED", and he can also open the burger menu top left, but the connect button is not clickable with the logs window open)
and also: once minimized, the NymConnect window cannot be brought back into view from the tray, only via alt-tabbing. 
https://paste.pics/OTCKE

**Screenshots**
https://paste.pics/OTCK3
https://paste.pics/OTCK8
https://paste.pics/OTCKE

**Which area of Nym were you using?**
Windows 11 and NC version 1.1.14

**Comment by tommyv1987** [comment]
Closing this as NC has no inbound development.
