### ISSUE TITLE
Update Cosmos chain registry info

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#3714]
The Cosmos chain registry still has us listed as running v0.26.1 of `nyxd`, it needs an update.

Also, the `stakingCurrency` needs to be set, because without it keplr breaks.

- [ ] update nyxd version
- [ ] add stakingCurrency

**Comment by mmsinclair** [comment]
See Osmosis setup: https://github.com/cosmos/chain-registry/blob/master/osmosis/chain.json#L28-L37

**Comment by mmsinclair** [comment]
This issue will fix https://github.com/nymtech/nym/issues/3715

**Comment by pwnfoo** [comment]
Chain registry PR [here](https://github.com/cosmos/chain-registry/pull/2861).
