### ISSUE TITLE
Add Nyx to Cosmos Kit list of chains

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#3715]
At the moment, the Nyx chain doesn't show up automatically to the "add chain" of CosmosKit (see https://docs.cosmoskit.com/). It would be good to investigate why and get us in there.

**Comment by mmsinclair** [comment]
After some investigation, I've found that `nyx` is in the chain registry - it doesn't show in the Cosmos Kit docs because that hasn't been rebuilt and redeployed since the `chain-registry` package was updated, so it doesn't contain the latest details.

**Comment by mmsinclair** [comment]
The next steps are to watch this issue and see if Cosmology update their docs site, otherwise will need to get in touch with Dan and ask him to publish new docs (after we update the staking currency details in the chain registry)

**Comment by mmsinclair** [comment]
Fixed by https://github.com/nymtech/nym/issues/3714
