### ISSUE TITLE
[Feature Request] Save settings after closing

### ISSUE THREAD

**Issue by brut069** [nymtech/nym#3734]
**Is your feature request related to a problem? Please describe.**

No, but more of an improvement of the product, to make it more versatile according to user expectations

**Is your request a feature not related to an existing problem? A new feature.**

Yes, a new feature. In the case the user will execute his provider himself (--open proxy or not) it would be interesting to memorize the state of the NYM CONNECT configuration.
This memorization will also make it possible to remember a gateway in particular.

The addition of this function can perhaps be implemented using a status button which, once activated, will memorize the parameters if it is activated when closing the nym connect.

**Where does the feature fit in the Nym real estate?**
- Application / Desktop / Nym Connect

**Comment by tommyv1987** [comment]
Our work on Nym Connect has been postponed in favour of developing the nym vpn product, i'm closing this ticket it accordance to what's mentioned
