### ISSUE TITLE
[Issue] some functions disappeared in wallet

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#3780]
**Describe the issue**
Some functions disappeared in wallet. 

1. The option to transfer the unlocked tokens has disappeared (the mixnet explorer shows the claimable NYM (unlocked and staking rewards). 
2. The 'delegate stake' button in the wallet is not working

**Screenshots**
https://paste.pics/P3RMP

**Which area of Nym were you using?**
 -Nym wallet 1.2.6 MacOS

**Comment by tommyv1987** [comment]
This wallet version is heavily outdated, this cannot be reproduced, closing ticket.
