### ISSUE TITLE
[Issue] Nym SDK cannot be imported

### ISSUE THREAD

**Issue by Huntsekkern** [nymtech/nym#3787]
**Describe the issue**
Nym SDK cannot be used in existing TS projects with their own config files, even after trying many workarounds, and taking inspiration from Nym mini-example config file.

**Expected behaviour**
That the Nym SDK can be imported the same way as dozens of established (and less famous) packages.

**Stack Traces**
Those are months old traces, which are not exhaustive (different errors appeared as I tried tweaking the config files), and not necessarily from the current state of the old branch (linked below).
```
ERROR in /root/walletconnect-utils-nym/node_modules/@nymproject/sdk/index.js 418:16
       Module parse failed: Unexpected token (418:16)
       You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
       |     const client = wrap(worker);
       |     // set any options
       >     if (options?.autoConvertStringMimeTypes) {
       |         await client.setTextMimeTypes(options.autoConvertStringMimeTypes);
       |     }
        @ ./dist/cjs/nym-ws.js 8:14-40
        @ ./dist/cjs/index.js
       ERROR: "build:umd" exited with 2.
```

**Steps to Reproduce**
Try to build/run a project importing Nym SDK. The project in question was [my integration of WalletConnect](https://github.com/Huntsekkern/walletconnect-utils-nym/tree/old-nym-sdk+nym-client). Look at the old branch, where the SDK is still an import, and I don't give guarantees about the working state of the branch as I had tried many many solutions to try to fix the configuration issue. The new branch works but just runs Nym clients.
The issues clearly stemmed from Nym SDK as identical code which just removed the dependency to Nym SDK was working perfectly fine.

**Which area of Nym were you using?**
 - Application: SDK
 - OS: Different Linodes (unix)

**Additional context**
I reported this issue internally several times months ago. Harry now asked that I make an official issue about it. I haven't retested it recently.

**Comment by mmsinclair** [comment]
hey @Huntsekkern we are hopefully going to release some new versions of the SDK this week, and it would be good if you could try one of the flavours with your integration

the most important choice will be dependent on two things:
- how you bundle it
- the CSP you are using

because that will decide if you need the "full-fat version" that has inlined and pre-bundled workers and WASM
