### ISSUE TITLE
[Issue] Fix package.json - copy-storage-placeholders

### ISSUE THREAD

**Issue by tommyv1987** [nymtech/nym#3792]
In the root package.json we have these calls to copy the placeholders.

This breaks the windows builds each week, so we have removed the lines from the package.json:

<img width="825" alt="image" src="https://github.com/nymtech/nym/assets/60836166/f6137011-36fe-4f50-a359-e487cdf5cf9e">

This week we will merge the changes into develop so this ticket can be the base to fix the issue.

**Comment by mmsinclair** [comment]
Removed this, so no fix needed
