### ISSUE TITLE
[Issue] Bonding a gateway doesn't work in the latest versions 

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#3803]
**Describe the issue**
Bonding a gateway doesn't work anymore in the latest versions 1.2.7 (mac)

**Expected behaviour**

Expected the bonding to work as with earlier versions

**Steps to Reproduce**
Unbond your gateway and try to bond again

**Screenshots**
https://imgur.com/a/7pLpRnk

**Which area of Nym were you using?**
MacOS 13.2.1 
Nym Wallet 1.2.7

**Additional context**
It works with 1.2.6 so a downgrade is currently a workaround

**Comment by tommyv1987** [comment]
currently investigating this now.

**Comment by jstuczyn** [comment]
Fixed in https://github.com/nymtech/nym/pull/3805

**Comment by merve64** [comment]
Thank you!
