### ISSUE TITLE
Explorer is showing the wrong Routing Score value in the list for gateways

### ISSUE THREAD

**Issue by octol** [nymtech/nym#3831]
It appears the explorer is showing the wrong value for Routing Score. According to the tooltip info as well as consistency with mixnodes it should use the most recent value, not last 24h.

![Image](https://github.com/nymtech/nym/assets/1894054/87a62183-ebac-4ae0-824b-46a2176cec38)

![Image](https://github.com/nymtech/nym/assets/1894054/7cbf57bf-fb6e-4e99-b76d-e367ab37cb02)

**Comment by tommyv1987** [comment]
i'm going to close this in favour of when we do the latest explorer update in the near future, we can always re-open this ticket.
