### ISSUE TITLE
NC - multiple backend socks5 clients are started if you click quickly

### ISSUE THREAD

**Issue by octol** [nymtech/nym#3832]
Especially in medium mode, where the init step takes a little longer will it pings gateways to select one with low latency, you can click connect twice and end up with two socks5 listeners running in the background. One will naturally fail and report to the front end that it's disconnected, and the UI state will end up out of sync (shows disconnected) with the backend socks5 listener running.

This is of course extra problematic on metered connections.

**Comment by tommyv1987** [comment]
Closing in lieu of VPN dev
