### ISSUE TITLE
Prepare the logo, banner and app screenshots for the Google Play application

### ISSUE THREAD

**Issue by marcdbz** [nymtech/nym#3853]
For Google Play, we need the following:

- App icon: Your app icon must be a PNG or JPEG, up to 1 MB, 512 px by 512 px, and meet our design specifications and metadata policy
- Feature icon: Your feature graphic must be a PNG or JPEG, up to 15 MB, and 1,024 px by 500 px
Phone screenshots: Upload 2-8 phone screenshots. Screenshots must be PNG or JPEG, up to 8 MB each, 16:9 or 9:16 aspect ratio, with each side between 320 px and 3,840 px - more a topic for @marcin
- 7" tablet screenshots: Upload up to eight 7-inch tablet screenshots. Screenshots must be PNG or JPEG, up to 8 MB each, 16:9 or 9:16 aspect ratio, with each side between 320 px and 3,840 px
- 10" Upload up to eight 10-inch tablet screenshots. Screenshots must be PNG or JPEG, up to 8 MB each, 16:9 or 9:16 aspect ratio, with each side between 1,080 px and 7,680 px

**Comment by MarcinSN** [comment]
Done
