### ISSUE TITLE
[DOCS] Wrong link inside docs

### ISSUE THREAD

**Issue by gabrielclcardoso** [nymtech/nym#3867]
Is your issue either: 
- [ x ] a fix to existing documentation (e.g. fixing a broken link or incorrect command) 

Please briefly describe your issue:

There's a link in the docs that leads you to a non existing page, It appears on the VPS setup and automation section and it's regarding the port reference table.

docs link: https://nymtech.net/operators/nodes/maintenance.html#vps-setup-and-automation
non existant link: https://nymtech.net/docs/nodes/gateway-setup.html#ports
![image](https://github.com/nymtech/nym/assets/69059969/292b7454-73a8-45a3-bb62-6a5c827f6203)
It's the link located at the bottom of the scream on the text `port reference table`
@serinko @mfahampshire

**Comment by rachyandco** [comment]
On the same page, let's also fix:

- https://nymtech.net/operators/nodes/maintenance.html#updating-node-information-via-the-cli

there is a 404 -> https://nymtech.net/docs/tools/nym-cli.md#upgrade-a-mix-node

- https://nymtech.net/operators/nodes/maintenance.html#setup

this link is working but is not well formatted: https://www.nginx.com/resources/glossary/nginx/#:~:text=NGINX%20is%20open%20source%20software,%2C%20media%20streaming%2C%20and%20more.&text=In%20addition%20to%20its%20HTTP,%2C%20TCP%2C%20and%20UDP%20servers.

Link should simply be: https://www.nginx.com/resources/glossary/nginx/

**Comment by serinko** [comment]
I believe this was fixed already [here](https://github.com/nymtech/nym/pull/3863/commits/48140647b76fa352b8d111e6909221ec9074bba3) and will be implemented with the next release.
