### ISSUE TITLE
Pull the network-monitor routes out of the validator

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#395]
At the moment we've been using the network monitor to find out what nodes are functional, and send the info the directory servers (in 0.9.x, the validators). But there is a different way to think about it. Is it really useful to check on one distributed system using the network monitor, and then shoot the results of what it finds out at one node of a different distributed system (the validators), but then not put the result in the blockchain? 

Something feels wrong about this.

The network monitor could in fact be its own standalone piece of functionality which checks on whether packets make it through the system, writes the result to a database (we're using SQLite in the validator right now), and then presents the info via both REST API and an HTML interface. Anyone might run it to make their staking decisions, or provide a guide as to the honesty of validators. 

We should consider taking the mixmining section out of the validator /directory code and just building it into the network-monitor as database + REST API built in Rocket.

**Comment by jstuczyn** [comment]
While I like the idea and agree with it, I think a prerequisite to this would be to remove hardcoded "good" nodes from the network monitor in favour of choosing couple of nodes with highest reputation.

**Comment by futurechimp** [comment]
I think that's also a good one, but it's a separate issue. I don't see any dependencies between them, both are good (and could be implemented independently of each other).

**Comment by tommyv1987** [comment]
this has been done in the new network monitor v2, closing this ticket as that will be deployed shortly.
