### ISSUE TITLE
ALL DOCS: Make a unified node naming convention

### ISSUE THREAD

**Issue by serinko** [nymtech/nym#4041]
## Desc

As docs evolve, we change approach. Result is arbitrary naming of nym nodes. We can see anything like:
- Exit gateway
- exit gateway
- Exit Gateway
- mixnode
- mix-node
- mix node
- SOCKS5 client
- `nym-socks5-client`
- `network-requester` or `nym-network-requester`

ETC.. You get the idea. 

## TODO

- [x] Make a clear rule / convention (and exceptions)
- [x] Make a PR to implement it

**Comment by mfahampshire** [comment]
If we refer to the binary its 'mixnode' (all one word) otherwise its 'mix node'

**Comment by mfahampshire** [comment]
imo if we refer to the binary itself we put it in `backticks` otherwise plaintext

**Comment by mfahampshire** [comment]
Re: capitalisation... imo we just pick one. I prefer uppercase ('Exit Gateway') overall

**Comment by serinko** [comment]
If I make an example:

One of the important changes is that **Network Requester** and **Gateway** are combined together into a node called **Exit Gateway**. From operational perspective this will be easy as it will all just run under the hood of the `nym-node` binary.

Something like that?

**Comment by mfahampshire** [comment]
Perfect

**Comment by mfahampshire** [comment]
Do note we use British English spelling instead of American as well - so 'decentralisation' instead of 'decentralization' for instance
