### ISSUE TITLE
[Issue] The 3-month profit margin in the Nym wallet doesn't update despite changes in the explorer.

### ISSUE THREAD

**Issue by merve64** [nymtech/nym#4050]
**Describe the issue**
The profit margin for a 3-month duration remains unaltered despite modification attempts. The coins are linked to the consumer, and when endeavoring to revise and save the percentages, the third month's figure remains constant. It is noteworthy that there have been amendments in the explorer, which are observable at the following location: 

https://nym.explorers.guru/transaction/DE525E5C5732402453AED5EE32B68911005AC745C93668E180F17AB5615A2F11

**Expected behaviour**
To ensure your profit margin in the Nym wallet is correctly updated, make adjustments once a month and it will reflect the appropriate changes.

**Screenshots**
n/a

**Which area of Nym were you using?**
n/a

Additional info:

Link to explorer: https://mixnet.explorers.guru/mixnode/4aAvMXQoGKdtZXwbQ6GjuohFAmKYTJ2pmEEnXTaXjuTF
Identity Key: 4aAvMXQoGKdtZXwbQ6GjuohFAmKYTJ2pmEEnXTaXjuTF

**Comment by gieadiguna** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.certinstaller/com.android.certinstaller.CertInstallerMain}: java.lang.IllegalArgumentException: Unknown MIME type: application/octet-stream
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3771)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3938)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
Caused by: java.lang.IllegalArgumentException: Unknown MIME type: application/octet-stream
	at com.android.certinstaller.CertInstallerMain.startInstallActivity(CertInstallerMain.java:207)
	at com.android.certinstaller.CertInstallerMain.onCreate(CertInstallerMain.java:119)
	at android.app.Activity.performCreate(Activity.java:8163)
	at android.app.Activity.performCreate(Activity.java:8130)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1330)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3744)
	... 12 more


I cannot install this apk,

**Comment by vikusss** [comment]
It turns out that adjustments can be made only once a month, for one era?

**Comment by jessgess** [comment]
That's correct. PM can be changed once a month. This is to protect the delegators. 

But @merve64 are you saying this user attempted to change the PM, 3 months in a row using the wallet but the change did not get applied? Or the changes were applied but the wallet does not show the latest figure?

**Comment by vikusss** [comment]
Yes, I’ve been trying to change the commission for 4 months, the changes
were not saved!

пн, 6 нояб. 2023 г. в 19:58, Jess ***@***.***>:

**Comment by jessgess** [comment]
@vikusss Can you please let us know what versions of the wallet and node binaries you're running and on what platforms?

**Comment by vikusss** [comment]
I always downloaded the latest version of the wallet, works on Linux Ubuntu
04.22. The version of the mix of the V2023.3-Kinder

чт, 9 нояб. 2023 г. в 19:01, Jess ***@***.***>:

**Comment by brut069** [comment]
hello, same for me, NymWallet 1.2.10. After "Save changes" and accpet the transcation fees, nothing is happening.

**Comment by vikusss** [comment]
The era of 11.11 has passed again. and nothing has changed((

пн, 13 нояб. 2023 г. в 03:34, Sé₿astien R. ***@***.***>:

**Comment by benedettadavico** [comment]
Hi so the original issue raised referenced this transaction: https://mixnet.explorers.guru/mixnode/4aAvMXQoGKdtZXwbQ6GjuohFAmKYTJ2pmEEnXTaXjuTF which refers to the following page in the wallet: 
<img width="1220" alt="image" src="https://github.com/nymtech/nym/assets/46782255/0b7388ef-4be6-4cad-a8ec-044cba912338">

Whereas a transaction to change the parameters would look like: https://nym.explorers.guru/transaction/8451DF9E42F644F860EB357F22E3807533604A75D2790C8A2A2A0DB89A61F0FF 

![image](https://github.com/nymtech/nym/assets/46782255/76802cdd-0bec-4006-a752-7184e41fc451)
Please make sure that the text beneath the input field has the updated value, and then at the end of the interval it will be updated

**Comment by vikusss** [comment]
You write me basic steps. This is all clear, this is exactly what I do, but nothing changes! Here are screenshots sequentially from the wallet!


вт, 14 нояб. 2023 г. в 22:51, benedetta davico ***@***.***>:

**Comment by vikusss** [comment]
Because of this bug, because I can’t reduce the commission, I lost a lot of
delegations! there were over 700,000 nym! so please kindly compensate for
the losses somehow! thanks in advance!

ср, 15 нояб. 2023 г. в 08:59, Виктория Тагирова ***@***.***>:

**Comment by vikusss** [comment]
![Nym Wallet 15 11 2023 8_53_40](https://github.com/nymtech/nym/assets/73056636/dcc9b5cf-34d2-474c-b0d3-c94d87f93fc6)
![Nym Wallet 15 11 2023 8_54_20](https://github.com/nymtech/nym/assets/73056636/de37de3d-7d8d-4a45-a0e0-db45925f6008)
![Nym Wallet 15 11 2023 8_54_50](https://github.com/nymtech/nym/assets/73056636/1ca891ae-c404-4c58-8e03-3ba07c463e8c)
![Nym Wallet 15 11 2023 8_55_02](https://github.com/nymtech/nym/assets/73056636/788ffceb-ac25-432c-b540-304dba6ff6ea)
![Nym Wallet 15 11 2023 8_55_22](https://github.com/nymtech/nym/assets/73056636/c1974c63-58c8-4fc1-80e3-e6d2b59a6b22)

**Comment by vikusss** [comment]
and as you can see, there are no signs that there will be changes in the next interval! This is a bug, please fix it and give me some coins for finding the bug for you))) Because of this bug, because I can’t reduce the commission, I lost a lot of delegations! there were over 700,000 nym! so please kindly compensate for the losses somehow! thanks in advance!

**Comment by benedettadavico** [comment]
Hi again, so as you can see the last time you changed the PM was on the 21/7/23. Please send a screenshot of the logs for when you are saving/confirming the changes. You can find the logs by clicking on the settings icon > clicking advanced > and then opening logs. The screenshot below shows what you should be seeing. 

<img width="1421" alt="image" src="https://github.com/nymtech/nym/assets/46782255/75e1f083-41de-4676-8289-2b5e2bfa6e92">

<img width="1079" alt="image" src="https://github.com/nymtech/nym/assets/46782255/7e220878-bdf4-4b1d-89a3-64b006088780">

**Comment by tommyv1987** [comment]
To highlight what @benedettadavico said, we tried this in multiple environments and on the mainnet to prove it was working as expected, Here is a video using the same wallet version and OS system

https://github.com/nymtech/nym/assets/60836166/65489d75-a5f7-4e55-83ab-c081030c34d8

Here is a successful transaction of the event on chain:
https://nym.explorers.guru/transaction/A08E1880D8A3E80B20CF5AF29674BBF1A2C513B92A1D79A70C604C35FCE6E918

**Comment by tommyv1987** [comment]
In addition to this and the non-reproduction of your issue, we have added support to update mixnode cost parameters via the cli:
https://github.com/nymtech/nym/pull/4148/files

Here you will be able to run the following command, for example:

`./nym-cli mixnet operators mixnode settings update-cost-parameters --profit-margin-percent 7 --mnemonic <your-menmonic>`

You can read more information on the cli from here: https://nymtech.net/docs/tools/nym-cli.html 

Remember, the cli will allow you to process multiple txs of the same event, but it will burn into your nym balance. Please only do this once a month; the binary to include these changes will be available in the next release.

**Comment by vikusss** [comment]
I just found a fault, changed 2 to 1 percent, everything worked, but it won’t let me change to 0 percent! How to set 0 percent Profit Margin?

**Comment by tommyv1987** [comment]
You cannot set your profit margin to 0%, nor can you set it to 100%; it's bound by our contract.

1% is the lowest you can set.

**Comment by gieadiguna** [comment]
Okay thanks for your information

Pada Rab, 15 Nov 2023 18.10, benedetta davico ***@***.***>
menulis:
