### ISSUE TITLE
[Issue] Close wallet button in menu shows twice

### ISSUE THREAD

**Issue by rachyandco** [nymtech/nym#4072]
**Describe the issue**
In the linux version, the close button in the menu shows twice, under the File section and the Window section

**Expected behaviour**
The close button should only appear once

**Steps to Reproduce**
- Open Wallet
- check the menu

**Screenshots**

see video record

https://github.com/nymtech/nym/assets/2358699/fb8cb386-6842-4e93-8ccc-f990853a0fdf

**Which area of Nym were you using?**
 - Application: Wallet
 - OS: Ubuntu 20.04
 - Version: Wallet 1.2.9

**Comment by tommyv1987** [comment]
@jessgess  - this should be a relatively easy one to sort, what do you think?

**Comment by jessgess** [comment]
@fmtabbara can you have a look please? Would be good to include it to tomorrow’s release if possible

**Comment by fmtabbara** [comment]
We use the `os_defaults` method on the `Menu` struct to produce the default menu and submenu items.
Reference - https://docs.rs/tauri/latest/tauri/struct.Menu.html
The menu items appear to be correct according to this.

I'll close this for now.
