### ISSUE TITLE
Temporary dependency override

### ISSUE THREAD

**Issue by jstuczyn** [nymtech/nym#41]
Once tendermint/iavl resolves PR (https://github.com/tendermint/iavl/pull/149), we need to remove/update the dep constraint on that dependency. It was introduced due to removal of libs/colors in Tendermint.

**Comment by marbar3778** [comment]
Thank you for your patience, we will be cutting a release on the Iavl store and tendermint today, that will resolve this issue.

**Comment by marbar3778** [comment]
We merged the PR and will cut a release tomorrow morning on iavl, sorry for the delay.
