### ISSUE TITLE
add nym testnet chain to Keplr

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#4140]

**Comment by yanok87** [comment]
https://github.com/chainapsis/keplr-chain-registry/pull/291#issuecomment-1827088567

**Comment by jessgess** [comment]
@yanok87 would you mind resubmitting the PR removing `"coinGeckoId": "nyx"` from the code? NYX as currency does not exist on CoinGecko obviously which is causing the problem

**Comment by tommyv1987** [comment]
@yanok87 is there any update on this?
