### ISSUE TITLE
[Feature Request] NymWallet warning Profit Margin

### ISSUE THREAD

**Issue by brut069** [nymtech/nym#4163]
Where does the feature fit in the Nym real estate?
- Application NYM WALLET

What is this solving?

It could be useful for the operator experience to add a message when user set profit margin to 0% or 100%
It would reduce github 
issues
Because rigth now when we sent 0 or 100% the operator is not aware if it has been process or if there was an error

Like : https://github.com/nymtech/nym/issues/4050

For exemple :
"You cannot set your profit margin to 0%, or 100%.
It's bound by our contract."

**Comment by tommyv1987** [comment]
hi @brut069 this is now a ticket on one of our other boards, we will look to action this when it's within scope, thank you for raising.
