### ISSUE TITLE
[Issue] Nym Connect AppImage fails to start due to old Tauri bug

### ISSUE THREAD

**Issue by Erudition** [nymtech/nym#4199]
**Describe the issue**
The appimage fails to start, with the below message.

**Expected behaviour**
The app starts.

**Stack Traces**
```
~/AppImages$ ./run-appimage.sh nym-connect_1.1.21_amd64.AppImage 
Starting up...
Failed to read user data /home/myusernamehere/.local/share/nym-connect/user-data.toml
Fallback to default
thread 'main' panicked at '`APPDIR` or `APPIMAGE` environment variable found but this application was not detected as an AppImage; this might be a security issue.', /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-utils-1.4.0/src/lib.rs:205:11
```

**Steps to Reproduce**
On Guix I have to use AppImage's `--extract-and-run` flag. Running an appimage this way works, except for old versions of Tauri that still had bug https://github.com/tauri-apps/tauri/issues/7736

**Additional context**
Upgrade to any Tauri later than https://github.com/tauri-apps/tauri/commit/c68fbfcb2d7a5b81e04c90edbb8fc43d1a895ab1 and the issue should be resolved.

**Comment by tommyv1987** [comment]
Development for the time being has postponed for nym-connect in lieu of developing the VPN product. Closing for now. And thank you for notifying a work around
