### ISSUE TITLE
Socks5 (possibly also native) client should stagger sending data

### ISSUE THREAD

**Issue by jstuczyn** [nymtech/nym#425]
This issue first appeared on accident when I was trying to run a 'speedtest' on a socks5 client. It is especially noticeable during an upload test. Basically the browser generates a huge payload that it going to be sent through the mix network. However, from the browser point of view, it appears as it was sent immediately (as it was fully read from the client socket within split of the second) hence there is a huge spike in upload speed at the beginning. By itself it's not an issue. However, now client has loads of data in its sending queue that it has to go through before new data can be even sent. So even when the speedtest is finished, the client is still going through the 'upload' data giving the impression of the client being broken and unresponsive. Only after a minute or so actual new requests can be sent.

To resolve this, there must be some mechanism to stagger sending request data. Perhaps using buffered channel (or maybe even with 0 buffer?) as opposed to unbounded channels we use now? Alternatively the queue could be made semi-random, i.e. rather than being FIFO, there could be some probability of taking element out of order?

**Comment by octol** [comment]
This was fixed as part of a series of PRs that went into 1.1.1
