### ISSUE TITLE
nym-vpn app icon

### ISSUE THREAD

**Issue by AsteroidusTv** [nymtech/nym#4276]
**Describe the issue**
The NymVpn application icon is that of tauri by default

**Expected behaviour**
Whether the icon is that of nym or nymvpn

**Steps to Reproduce**
Download the 37c3 nymvpn release.
Install the .deb package.
Go to apps menu.

**Screenshots**
![image](https://github.com/nymtech/nym/assets/113026499/6e769354-54db-45e5-81ef-0c12acbf319e)

**Which area of Nym were you using?**
 - Application: Nymvpn
 - OS: Ubuntu 23.10
 - Version: 37c3 demo (For ubuntu 22.04 LTS)

**Comment by tommyv1987** [comment]
The VPN is still WIP and we're aware of this, thank you for raising. This has already been fixed in later version, not the demo version for CCC.
