### ISSUE TITLE
Crank up the default bandwidth settings.

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#429]
At the moment we have a lot of node capacity and our settings use almost no bandwidth. Let's crank the settings up so we provide a nicer experience for users.

I think these setttngs strike a nice balance for the moment: 

```
average_packet_delay = 50
average_ack_delay = 50
loop_cover_traffic_average_delay = 200
message_sending_average_delay = 20
```

That's 20 packets per second (not much) sent reasonably quickly.

**Comment by jstuczyn** [comment]
> At the moment we have a lot of node capacity 

I disagree with this because of the gateway situation. Our capacity hasn't really increased much in a while.
