### ISSUE TITLE
testnet - fix the faucet and link it to the explorer on the Testnet section

### ISSUE THREAD

**Issue by jessgess** [nymtech/nym#4317]
https://github.com/nymtech/nym/tree/develop/testnet-faucet redeploy with some rate limiting or CAPTCHA in place

**Comment by jessgess** [comment]
Once fixed add a link to the faucet to the Testnet view of the Explorer

**Comment by huximaxi** [comment]
rename testnet tokes back to TNYM or similar

**Comment by tommyv1987** [comment]
closing - https://faucet.nymtech.net/
