### ISSUE TITLE
[Issue] mixnode behind NAT no longer supported (missing announce-host / announce_address)

### ISSUE THREAD

**Issue by timkuijsten** [nymtech/nym#4349]
Up until 1.1.20 the --announce-host parameter was supported so that mixnodes could function behind a NAT. Since I stopped renting extra ipv4 addresses this week I moved my mixnode (1.1.34) to ipv6. I've only mixed about 8600 packets in 30 hours and get low routing scores (Guru even shows my node is [inactive](https://mixnet.explorers.guru/mixnode/FS3uvkS7UkAcDJxXRf1ptpvx7jZT55SEeCNv5eiuKuQV)) so I'm trying to move back to ipv4 behind NAT, but for that the --anounce-host came in handy.

The [troubleshooting](https://nymtech.net/operators/nodes/troubleshooting.html#missing-announce-host-flag) page still shows --announce-host as an option but it was removed in 9a68702d4d1391f69cef91c7fdabdfbc48c9259a (#3498).

Was the removal of this functionality intentional?
If so, are there any plans to support ipv6 and/or NAT in the future?

/somewhat related: https://github.com/nymtech/nym/issues/1781

**Comment by timkuijsten** [comment]
Background: I have nym-mixnode on dedicated hardware behind a 500/500mbit fiber optic line. I used to rent extra ipv4 addresses but because of the additional costs I stopped doing that. So currently I only have a /48 ip6 subnet + 1 ip4 address that I have to share with more devices.

**Comment by octol** [comment]
`nym-gateway` moved in the other direction, adding a `--public-ips` in addition to `--listening-address`. Now that mixnode and gateway is planned to merge into one binary, maybe this functionality will automatically return? @jstuczyn maybe knows this one better

**Comment by jstuczyn** [comment]
I might be misunderstanding something here, but the `announce-host` has been completely useless in quite a while. It was an artifact from the time when nodes were annoucning themselves to the directory server. Currently, for your "custom" announce host you just provide your desired address during bonding.

**Comment by timkuijsten** [comment]
> Currently, for your "custom" announce host you just provide your desired address during bonding.

Aah, that seems to do the trick. The last time I was behind NAT it was around 1.0.x and back then the option was needed. Since then I thought the ip in the config must be equal to the one published on the chain, but apparently that is no longer the case. Tnx!
