### ISSUE TITLE
Investigate why --clients-host and --mix-host are distinct for gateways

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#435]
This one seems a bit strange to me. Have I documented this incorrectly (e.g. does one need a port and the other not?)? Or can we simply merge these flags into `--host` and simplify things?

**Comment by jstuczyn** [comment]
I'm not entirely sure. It came from the initial "we need to know the host information" to correctly bind listener. Then gateway got second listener (the websocket) so the easiest way to do it was the new flag. However, it also gives the extra benefit of being able to bind to different interfaces (this is a theoretical example: you might want to run private gateway on your subnet - receive mix packets from mix network (bind `mix-host` to your public ip), but only allow client-websocket connections from your local network (bind `clients-host` to local address). Also it makes it easier to customise ports.
