### ISSUE TITLE
Log `wasted_space` is missing a conversion from fraction to percentage

### ISSUE THREAD

**Issue by numbleroot** [nymtech/nym#4358]
When logging (at `trace` level) how much space is wasted due to padding packets to full Sphinx packets, could it be that the variable is missing a conversion from fraction to percentage?

As far as I can tell, you're calculating `wasted_space` as the fraction of `space_left` bytes out of the total number of bytes required to send the message as well as pad it to full Sphinx packet length: https://github.com/nymtech/nym/blob/836e237116a0eadbf346fe29637d008d0624eaff/common/nymsphinx/src/message.rs#L242

However, you then log it as a percentage in the following line: https://github.com/nymtech/nym/blob/836e237116a0eadbf346fe29637d008d0624eaff/common/nymsphinx/src/message.rs#L243

This leads to fractions (e.g., `0.16452`) instead of percentages (e.g., `16.452`) being printed as the wasted space. Let me know if I got something wrong here.

**Comment by octol** [comment]
Thanks, yes I think you are right, the log appears to be inconsistent with the value

**Comment by numbleroot** [comment]
Thanks for fixing it so quickly in #4359!
