### ISSUE TITLE
Gateway with embedded network requester crashes with "Tried to insert duplicate pending ack"

### ISSUE THREAD

**Issue by numbleroot** [nymtech/nym#4406]
**Describe the issue**

On [`nym-binaries-v2023.5-rolo`](https://github.com/nymtech/nym/tree/nym-binaries-v2023.5-rolo), when running a gateway with embedded network requester (initialized by adding flags `--with-network-requester --open-proxy true`) with at least 4 endpoints constantly sending HTTP requests towards this embedded network requester, the gateway crashes eventually with the following panic:
```rust
thread 'tokio-runtime-worker' panicked at common/client-core/src/client/real_messages_control/acknowledgement_control/action_controller.rs:130:17:
Tried to insert duplicate pending ack
```

I've seen this panic crash a gateway on at least 5 individual attempts at running my endpoints-to-embedded-network-requester setup. It can take quite a while to occur, but typically happens eventually.

**Expected behaviour**

The gateway should not panic. Clearly, duplicate ACKs are a problem. Thus, my expectation is not that this situation would not cause a panic, but that the situation is ensured not to occur in the first place.

**Stack traces**

```rust
thread 'tokio-runtime-worker' panicked at common/client-core/src/client/real_messages_control/acknowledgement_control/action_controller.rs:130:17:
Tried to insert duplicate pending ack
```

**Steps to reproduce**

Initialize and run a Nym `nym-binaries-v2023.5-rolo` gateway with embedded network requester configured to act as an open proxy. Have 4 or more HTTP clients hooked up to their own independent `nym-socks5-client`s send constant HTTP requests (e.g., by iterating through a list of URLs) to this embedded network requester through Nym. I've set up all involved Nym endpoints to be registered with this one gateway (i.e., the embedded network requester and all `nym-socks5-client`s use this one gateway as their gateway, no other gateway involved). Wait for the panic to occur eventually. As a side note, I'm typically seeing gateway logs indicating circa 200 - 600 concurrently ongoing proxies at the gateway when this error occurs.

**Screenshots**

n/a

**Which area of Nym were you using?**

- Application: `nym-gateway` (with embedded `network-requester`), `nym-socks5-client`
- OS: Ubuntu 22.04
- Version: [`nym-binaries-v2023.5-rolo`](https://github.com/nymtech/nym/tree/nym-binaries-v2023.5-rolo)

**Additional context**

Given this panic indicates duplicate acknowledgments and they seem to be identified by their `FragmentIdentifier`, one possible explanation might be that we are seeing a collision for the randomly generated `set_id` (`i32`) here. If my understanding of the inner `nymsphinx/chunking` workings is correct, the search space offers `2^31` possible values. This means that the minimum number of tries for seeing a collision with at least `50%` chance is circa `55,000` (at least `25%` chance => circa `35,000` tries, at least `10%` chance => circa `21,000` tries). As far as I understand this, this is only relevant for items in the `pending_acks_data` field of the `ActionController`. Whether I in fact hold enough unacknowledged items in this hash map to make this a possible trigger of the panic, I can't say, as I have no insight into the size of the `pending_acks_data` hash map. I currently have no other ideas for how this panic could be triggered, I'm only offering these collision thoughts for consideration. Other causes are of course very possible.

**Comment by octol** [comment]
Is this issue still present? At least it shouldn't panic since https://github.com/nymtech/nym/pull/4248. Although it's a bit of a mystery why this even happens in the first place ...

**Comment by tommyv1987** [comment]
Closing the ticket based upon @octol comments

**Comment by numbleroot** [comment]
Does downgrading the `panic` to an `error` log not only kick the problem down the road? What if subsequently the entry with id `frag_id` is requested from `self.pending_acks_data` in order to update or remove it, and now multiple items with identifier `frag_id` exist?

Given the small range `[1, 2147483647]` from which `set_id`s are randomly chosen, would it not make sense to increase `set_id` from `i32` (with excluded edge cases) to `i64` (with excluded edge cases)? This way, at least the probability of generating a `set_id` collision is much reduced.

**Comment by octol** [comment]
> Does downgrading the `panic` to an `error` log not only kick the problem down the road? What if subsequently the entry with id `frag_id` is requested from `self.pending_acks_data` in order to update or remove it, and now multiple items with identifier `frag_id` exist?
> 
> Given the small range `[1, 2147483647]` from which `set_id`s are randomly chosen, would it not make sense to increase `set_id` from `i32` (with excluded edge cases) to `i64` (with excluded edge cases)? This way, at least the probability of generating a `set_id` collision is much reduced.

Yep that's correct. Well at least things like this shouldn't take the whole gateway down now, which is critical, but yeah there is a small small % of packets that are corrupted by this. 

And also yes I agree it would be good to increase the id to 64-bit, the challenge is doing that gradually without breaking things on mainnet. So it's a little more than just changing the type
