### ISSUE TITLE
lost my phrase

### ISSUE THREAD

**Issue by bulkian** [nymtech/nym#4481]
Hello,
I lost my phrase, and can connect only with my passeword.
I know i can  find my phrase with my password on  last  version on the wallet, but  i have on old version installed.
I am scared  to update the  wallet and not being  able then  to connect with my password.
Is there any  other  way to  get my phrase  back?
Thank  you

**Comment by tommyv1987** [comment]
hi @bulkian 

i've added a walkthrough read me on using a tool to recover your mnemonic, i wish you the best in recoverying your password, please find the relevant PR above.

thanks,
tommy
