### ISSUE TITLE
Add a section in the documentation in relation to gateway blacklisting [DOCS]

### ISSUE THREAD

**Issue by JohnSmith-PrivacyRebels** [nymtech/nym#4502]
Is your issue either: 
- [ ] a fix to existing documentation (e.g. fixing a broken link or incorrect command) 
- [X] an enhancement (e.g. adding a description for an undocumented feature)

Please briefly describe your issue:

- This has been discussed within the community for a while, so a hot issue. I think we should have a separate section in the documentation in relation to gateway blacklisting. Two things would be good to have - to list the reason why a gateway may be blacklisted and how to get out of the blacklist. Also, it would be great to include a link to Swagger API https://validator.nymtech.net/api/swagger/index.html so people can easily check themselves whether their gateway has been blacklisted or not.

**Comment by tommyv1987** [comment]
Hi @JohnSmith-PrivacyRebels,

Thank you for raising this important topic, which has indeed sparked discussion within our community. We recognise the need for clarity around the process of gateway blacklisting, including the reasons a gateway might be blacklisted and the steps for removal from the blacklist.

To address this, we're committed to updating our documentation with a dedicated section on gateway blacklisting. This will encompass a detailed explanation of blacklisting criteria in the near future.

We are working on enhancing our network monitor in the development roadmap. This update will significantly improve the monitor's ability to assess network quality.

As small overview here:

Currently, if a route's performance score falls below a certain threshold within 24 hours, it may be deemed underperforming and potentially face blacklisting. For example, the network monitor tests routes like this:

```
network_monitor::monitor > Test routes: [
Route 15112304117153033856: [G] ABC => [M1] MIXNODE1 => [M2] MIXNODE2 => [M3] MIXNODE3
```

```
A successful test will report:
✔️ 15112304117153033856 succeeded
```
And a failed test shows:

```
network_monitor::monitor > ❌️ 887267562741906773 failed (23/1000 received)
[G] GW1 => [M1] M1 => [M2] M2 => [M3] M3,
```

These failures can affect gateways and mixnodes, leading to potential blacklisting. Tests occur multiple times per hour. Despite this, the monitor aims to "auto-heal" by attempting to remove gateways and mixnodes from the blacklist.

All in all, we appreciate your patience and involvement in improving our ecosystem. Your suggestion directly contributes to our efforts in making our platform more accessible and transparent.
