### ISSUE TITLE
[DOCS] Broken link to "Operator Guides book" l

### ISSUE THREAD

**Issue by flipchan** [nymtech/nym#4632]
Is your issue either: 
- [x] a fix to existing documentation (e.g. fixing a broken link or incorrect command) 

Please briefly describe your issue:
https://nymtech.net/docs/nodes/mixnode.html contains a broken link for the "Operator Guides book" link:

![Screenshot_2024-06-08_19-34-26](https://github.com/nymtech/nym/assets/12517945/d5cffe68-6352-4407-9132-62b5949f1570)

Pressing it leads to a 404 page:  

![Screenshot_2024-06-08_19-34-50](https://github.com/nymtech/nym/assets/12517945/57c82aec-4ea0-4d1a-a60a-058171c1d473)

**Comment by serinko** [comment]
Thank you for flagging this out. The problem is bigger than a breoken link, I see the docs are divided according to deprecated categories and don't mention `nym-node`. I will talk with @mfahampshire  and we will make a PR addressing this issue asap.
