### ISSUE TITLE
Socks5 client does not quit elegantly

### ISSUE THREAD

**Issue by rachyandco** [nymtech/nym#480]
Socks5 client does not quit elegantly 

version: 0.9.2 (linux binaries)

pressing Ctrl+C generates the following log:

```
^CReceived SIGINT - the client will terminate now (threads are not yet nicely stopped, if you see stack traces that's alright).
thread 'tokio-runtime-worker' panicked at 'the buffer request failed!: TrySendError { kind: Disconnected }', clients/socks5/src/socks/mixnet_responses.rs:20:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

**Comment by jstuczyn** [comment]
Yes, right now none of the binaries are guaranteed to stop gracefully, it even says so in your message : )
> ^CReceived SIGINT - the client will terminate now (threads are not yet nicely stopped, **if you see stack traces that's alright**).

This will get fixed once we deal with https://github.com/nymtech/nym/issues/73

**Comment by tommyv1987** [comment]
Socks-5 and the rest of the nym-binaries close more elegantly as the SIGINT work has been introduced in v1.0.2 binaries. Closing ticket.
