### ISSUE TITLE
when nym-mixnode errors, it should return rc != 0

### ISSUE THREAD

**Issue by ghost** [nymtech/nym#496]
When `nym-mixnode` quits with an error, it doesn't return 0.

```
 2021-01-11T22:32:53.022 ERROR nym_mixnode::node > failed to register with the validator - ValidatorError("mixnet is already at capacity")
```

This makes `nym-mixnode.service` think everything is good so it backs off and not retrying:

```
$ sudo systemctl status nym-mixnode
● nym-mixnode.service - Nym Mixnode (0.9.2)
     Loaded: loaded (/etc/systemd/system/nym-mixnode.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Mon 2021-01-11 22:34:15 UTC; 2min 8s ago
    Process: 6693 ExecStart=/home/nym/nym-mixnode run --id seventh-horizon (code=exited, status=0/SUCCESS)
   Main PID: 6693 (code=exited, status=0/SUCCESS)

Jan 11 22:34:15 nsa.gov nym-mixnode[6693]: Starting mixnode seventh-horizon...
Jan 11 22:34:15 nsa.gov nym-mixnode[6693]: Public identity key: [redacted]
Jan 11 22:34:15 nsa.gov nym-mixnode[6693]: Public sphinx key: [redacted]
Jan 11 22:34:15 nsa.gov nym-mixnode[6693]: Directory server [presence]: http://testnet-validator1.nymtech.net:8081
Jan 11 22:34:15 nsa.gov nym-mixnode[6693]: Directory server [metrics]: http://testnet-metrics.nymtech.net:8080
Jan 11 22:34:15 nsa.gov nym-mixnode[6693]: Listening for incoming packets on 104.74.140.223:1789
Jan 11 22:34:15 nsa.gov nym-mixnode[6693]: Announcing the following socket address: 104.74.140.223:1789
Jan 11 22:34:15 nsa.gov nym-mixnode[6693]:  2021-01-11T22:34:15.784 INFO  nym_mixnode::node > Starting nym mixnode
Jan 11 22:34:15 nsa.gov nym-mixnode[6693]:  2021-01-11T22:34:15.954 ERROR nym_mixnode::node > failed to register with the valida>
Jan 11 22:34:15 nsa.gov systemd[1]: nym-mixnode.service: Succeeded.
```

Workaround: changing `Restart=on-failure` to `Restart=always`. (with proper StartLimitInterval & StartLimitBurst of course)

**Comment by ststefa** [comment]
I'd think that this is intentional in this particular case ("mixnet already at capacity"). I would argue that this can rightly be considered _not_ a mistake, but it boils down to a matter of taste.

At least the current behaviour allows to differentiate between a proper error condition and a "mixnet full" condition. If you want your node to retry (although everything works well except the mixnet is full) then you can still use a timer for that maybe like so:

```bash
$ cat /etc/systemd/system/nym-mixnode.timer
[Timer]
Unit = nym-mixnode
OnUnitInactiveSec = 1h

[Install]
WantedBy = timer.target
```

At least that's how I implemented a regular retry.

**Comment by ghost** [comment]
I understand that this boils down to a matter of a taste.
But then I think error is an error and can render process monitoring useless / lead people (or SW) into missing their nym-mixnode uptime, then making them figure out what's wrong... probably finding this issue on the github (that's what I would do).

Not everyone is going to create an additional .timer (not even mentioning how many dislike systemd...) nor everyone is expected to start debugging a systemd service when it is up & running / green.
Neither this is a traditional behavior. It looks more of an anti-pattern to me. Please correct me if I'm wrong though.

I prefer KISS principle here, i.e. if the service is not doing what it is expected to, try restarting it few times and then mark it as Dead in case if all restart attempts have been exhausted. This will bring admin's attention for looking into what's going on / reading the logs / or trigger alerting (process monitoring) system, which is usually expected.

And if you prefer going with the .timer or "that's how it's supposed to work" / create own monitoring, then this should be mentioned in the nym-mixnode service setup documentation.

**Comment by ststefa** [comment]
Before anything else, I should probably emphasize that I am not a member of the nym team. I am just an early community member.

I totally agree with you that this is confusing behaviour. Fortunately (and whatever might have been the reason for it) this case should now be obsolete. Limiting the mixnet capacity was introduced as a quick hack to counter attacks that occured in early experiments. It is now being replaced with some proper mechanisms to protect mixnet health. Of course this is all on ongoing journey and I'm pretty sure this was not the last oddity we see on the way.

**Comment by tommyv1987** [comment]
hi @arno01 - i'm going to close this issue as it's somewhat outdated now and this no longer applies to our current set up with mainnet. 

thank you for raising the issue initially and apologies it didn't get looked at when it was raised, if you have any other queries don't hesitate to re-open the issue.
