### ISSUE TITLE
[Build] [Issue] GOPATH problems

### ISSUE THREAD

**Issue by zwillikon** [nymtech/nym#5042]
I'm trying to build [this PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nym-vpnd ) from ArchLinux but against git master sources.

Until [a few years ago](https://wiki.archlinux.org/index.php?title=Go_package_guidelines&oldid=609650#Old_Go_projects_(for_Go_%3C1.11)) it was necessary to set fake $GOROOT and $GOPATH in every Go PKGBUILD. Now I've seemed to hit that issue again:
```
libwg.go:19:2: cannot find package "github.com/nymtech/nym-vpn-client/wireguard/libwg/container" in any of:
	/usr/lib/go/src/github.com/nymtech/nym-vpn-client/wireguard/libwg/container (from $GOROOT)
	./src/github.com/nymtech/nym-vpn-client/wireguard/libwg/container (from $GOPATH)
libwg_default.go:24:2: cannot find package "github.com/nymtech/nym-vpn-client/wireguard/libwg/logging" in any of:
	/usr/lib/go/src/github.com/nymtech/nym-vpn-client/wireguard/libwg/logging (from $GOROOT)
	./src/github.com/nymtech/nym-vpn-client/wireguard/libwg/logging (from $GOPATH)
libwg_default.go:20:2: cannot find package "golang.zx2c4.com/wireguard/conn" in any of:
	/usr/lib/go/src/golang.zx2c4.com/wireguard/conn (from $GOROOT)
	./src/golang.zx2c4.com/wireguard/conn (from $GOPATH)
libwg.go:20:2: cannot find package "golang.zx2c4.com/wireguard/device" in any of:
	/usr/lib/go/src/golang.zx2c4.com/wireguard/device (from $GOROOT)
	./src/golang.zx2c4.com/wireguard/device (from $GOPATH)
libwg_default.go:22:2: cannot find package "golang.zx2c4.com/wireguard/tun" in any of:
	/usr/lib/go/src/golang.zx2c4.com/wireguard/tun (from $GOROOT)
	./src/golang.zx2c4.com/wireguard/tun (from $GOPATH)
```

Since I'm building from scratch I can't yet have any installed package under
_/usr/lib/go/src/github.com/nymtech/nym-vpn-client/wireguard/libwg/container (from $GOROOT)_

**Comment by doums** [comment]
Hi, once the next stable version `1.0.0` is released our AUR packages will be updated accordingly.
For now, you can install current stable version via these aur pkgs `nym-vpnd-bin nym-vpn-app-bin` or `nym-vpnd nym-vpn-app`
