### ISSUE TITLE
'--directory' not expected error starting local mixnet

### ISSUE THREAD

**Issue by jpds** [nymtech/nym#520]
I wanted to try running my own mixnet per the instructions at: https://nymtech.net/docs/mixnet/running-localnet/ and compiled this project. However upon running the `start_local_network.sh` script, I get the following error for the `mixnode init` parts:

```
error: Found argument '--directory' which wasn't expected, or isn't valid in this context
```

**Comment by tommyv1987** [comment]
Hi @jpds 

Apologies for the slow response. This has since been deprecated. 

Going to close the ticket.
