### ISSUE TITLE
 WARN  nym_mixnode::node::listener > Failed to accept incoming connection - Os { code: 24, kind: Other, message: "Too many open files"

### ISSUE THREAD

**Issue by alecapt86** [nymtech/nym#523]
**error that loads the server**
![2021-03-11_08-28-48](https://user-images.githubusercontent.com/41871283/110741033-08fbb500-8245-11eb-94ba-f452e89eab69.png)
**the number of open files on a normal server**
![2021-03-11_08-39-21](https://user-images.githubusercontent.com/41871283/110741225-609a2080-8245-11eb-9201-94cf0daa74c9.png)

**Comment by jstuczyn** [comment]
Hi!
This indeed looks like a `ulimit` problem. Are you by any chance running the node using `systemd`? Try following the instructions in our documentation: https://nymtech.net/docs/run-nym-nodes/mixnodes/#set-the-ulimit and see if that helps

**Comment by alecapt86** [comment]
Yes. the node works well on one server. on the second no. Such a mistake. How do you think I should rebuild the server?

**Comment by tommyv1987** [comment]
At the time of posting this, multiple iterations of the mixnode binaries have been built and optimised, especially, now nym is running in mainnet. We apologise for this ticket going stale. But we're going to close it.
