### ISSUE TITLE
 I reinstalled the server. How can I start a node with the old settings

### ISSUE THREAD

**Issue by alecapt86** [nymtech/nym#529]
![2021-03-16_12-41-03](https://user-images.githubusercontent.com/41871283/111298053-68036480-865f-11eb-8dcb-a14052917039.png)
![2021-03-16_12-36-07](https://user-images.githubusercontent.com/41871283/111298057-689bfb00-865f-11eb-8cfd-601d642df241.png)

**Comment by tommyv1987** [comment]
Going to close the ticket as it would've become out of sync with the latest code for binaries. In this instance, if would've been making a backup of the .nym directory in whatever your home path would've been and reiniting the mixnode binary.
