### ISSUE TITLE
Native client upgrade command is broken

### ISSUE THREAD

**Issue by sgeisler** [nymtech/nym#582]
The `nym-client upgrade --id <id>` command does not seem to upgrade the gateway in the config to one which is actually available in the new network (`0.9.2` -> `0.10.0`). This leads to "invalid topology" errors when starting the upgraded client. Changing it manually is not possible since there exists a shared key between client and gateway (`gateway_shared.pem`) which has to be regenerated when changing the gateway.

**Comment by jstuczyn** [comment]
The `upgrade` command shouldn't really upgrade/change the gateway, it's the gateway operator's responsibility to ensure they are up to date. 
It seems that your options would be to either wait until your current gateway becomes part of the most recent topology or create a new client and optionally copy your old keys over.

**Comment by sgeisler** [comment]
You are right, I mainly wanted to a void that the address changes and that's only possible with the same GW anyway :( so I guess I'm out of luck. In later versions I guess there would be slashing to incentivize actually updating? Since your address depends on the GW it might also be wise to have long unbound-timeouts to disincentivize sudden service discontinuation. But maybe that won't be as much of a problem anymore once service providers can announce their presence in a canonical way.

> and optionally copy your old keys over

That's exactly what doesn't work. The shared key with the GW seems to be bound to the identity key (which makes sense).
