### ISSUE TITLE
Bonding hostname vs. ip-address does not show up on NYM explorer

### ISSUE THREAD

**Issue by pkrasam** [nymtech/nym#593]
When bonding a `mixnode` I used a hostname e.g. `nym-mixnode.abc.com:1789` instead of `ip-address:1789`

But the explorer is not picking up my mixnode

[NYM Explorer](https://testnet-finney-explorer.nymtech.net/nym/node-list/)

**Comment by jstuczyn** [comment]
Is there any particular error you encountered when trying to bond a mixnode with a hostname? There should be nothing preventing you from doing that. As a matter of fact I can see few mixnodes bonded like this already.
