### ISSUE TITLE
On node startup (`init`, `run`, `upgrade`) check if it's using the most recent version

### ISSUE THREAD

**Issue by jstuczyn** [nymtech/nym#615]
This is something we potentially might want to do - i.e. on on node startup hit GitHub API to grab all the tags and check if our version is the most recent one. 

Upon further thinking, maybe we should not be hitting github API after all as we might hit some rate limit if hundreds of nodes hit the same endpoint in quick succession. @futurechimp how about having something like https://nymtech.net/latest_release_version that would return a string with semver of the lastest version?

**Comment by ShubhamPalriwala** [comment]
Hey @jstuczyn, So basically whenever an `npm script ` is run, we are looking to compare their cloned version to our version on Github right?

**Comment by jstuczyn** [comment]
Pardon, what `npm script` do you have in mind? 

This is basically a loose idea I had that whenever people do anything new with their nodes (such as `./nym-mixnode run --id foo`) they would get an information whenever an update is available. I would imagine it could be achieved by querying some GitHub API to figure out if a tag with version number higher than the version of their node exists

**Comment by ShubhamPalriwala** [comment]
We can setup husky to run a pre-script everytime a command is executed and it can compare the versions

**Comment by iranzo** [comment]
You acan check the releases at https://github.com/nymtech/nym/releases  and parse them for latest version

**Comment by liam0215** [comment]
Is anyone working on this?

**Comment by tommyv1987** [comment]
NymVisor will soon update all gateways and nym-mixnodes, so closing this ticket.
