### ISSUE TITLE
update to v0.10.1, it show ERROR message "failed to receive reply to our echo packet within 1.5s"

### ISSUE THREAD

**Issue by not2007** [nymtech/nym#620]
May 27 13:35:33 VM-0-15-ubuntu nym-mixnode[16346]:  2021-05-27T05:35:33.052Z INFO  nym_mixnode::node::metrics                > Since startup mixed 129 packets!
May 27 13:35:58 VM-0-15-ubuntu nym-mixnode[16346]:  2021-05-27T05:35:58.683Z ERROR mixnode_common::rtt_measurement::sender   > failed to receive reply to our echo packet within 1.5s. Stopping the test
May 27 13:36:08 VM-0-15-ubuntu nym-mixnode[16346]:  2021-05-27T05:36:08.703Z ERROR mixnode_common::rtt_measurement::sender   > failed to receive reply to our echo packet within 1.5s. Stopping the test
May 27 13:36:33 VM-0-15-ubuntu nym-mixnode[16346]:  2021-05-27T05:36:33.054Z INFO  nym_mixnode::node::metrics                > Since startup mixed 132 packets!
May 27 13:37:33 VM-0-15-ubuntu nym-mixnode[16346]:  2021-05-27T05:37:33.056Z INFO  nym_mixnode::node::metrics                > Since startup mixed 134 packets!
May 27 13:38:09 VM-0-15-ubuntu nym-mixnode[16346]:  2021-05-27T05:38:09.723Z ERROR mixnode_common::rtt_measurement::sender   > failed to receive reply to our echo packet within 1.5s. Stopping the test
May 27 13:38:09 VM-0-15-ubuntu nym-mixnode[16346]:  2021-05-27T05:38:09.736Z ERROR mixnode_common::rtt_measurement::sender   > failed to receive reply to our echo packet within 1.5s. Stopping the test

**Comment by jstuczyn** [comment]
The default logging was slightly oversensitive. It has been tuned down in https://github.com/nymtech/nym/pull/618
