### ISSUE TITLE
UX feature request: add current balance on wallet pages

### ISSUE THREAD

**Issue by GreyPK** [nymtech/nym#710]
UX feature request: add current balance on wallet pages: 
1) delegateStake https://testnet-milhon-wallet.nymtech.net/delegateStake
2) send https://testnet-milhon-wallet.nymtech.net/send
3) bond https://testnet-milhon-wallet.nymtech.net/bond
Now you can see balance only on page https://testnet-milhon-wallet.nymtech.net/balanceCheck

**Comment by fmtabbara** [comment]
linked to #779
