### ISSUE TITLE
Clean shutdown for all processes

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#73]
Catch signal interrupts to cleanly shut down client, provider, validators and mixnodes.

**Comment by jstuczyn** [comment]
Looks like tokio might be of a big use here!
https://docs.rs/tokio/0.2.9/tokio/signal/index.html

**Comment by tommyv1987** [comment]
Closing issue, archiving for future planning session — the issues / tasks have moved to a new project board, so we can evaluate shortly.

**Comment by ststefa** [comment]
I'd suggest that you pick that up at some point. The unclean shutdown also leads to funny process returncodes which are not nice for operation. It seems that several NYM processes suffer from this. At least I have that same behaviour with the nym-client.
