### ISSUE TITLE
Upgrade `prost` to 0.8

### ISSUE THREAD

**Issue by neacsu** [nymtech/nym#768]
In order to fix the nightly build, we need to upgrade `prost` to 0.8
That can only be done once our dependencies also upgrade to 0.8, (`tendermint-rs` especially), which are blocked by https://github.com/tokio-rs/prost/issues/502
Creating this as an issue so that we can track the development of the issue.

**Comment by futurechimp** [comment]
There is an issue for this in tendermint-rs at https://github.com/informalsystems/tendermint-rs/issues/966
