### ISSUE TITLE
Update Run Nym Nodes Documentation

### ISSUE THREAD

**Issue by DeclareHigh** [nymtech/nym#773]
Update https://nymtech.net/docs/run-nym-nodes/ to include a note indicating that new nodes won't be accepted similar to the statement in https://medium.com/nymtech/nym-v0-11-0-and-testnet-milhon-6ed9c800f889:

"How to get involved in Testnet Milhon?
At the time of writing this post, the Nym network has grown to over 9000 nodes — many thanks to Nym’s amazing community of supporters! This is, however, far more nodes than the network requires right now, given the amount of traffic that is going through it. So (at least for now), running a node in Milhon will only be open to those who have run a node in Finney and new nodes won’t be accepted to the network.
If you are not running a node already, and want to take part in Milhon, you have until Tuesday the 20th to start one, and then migrate that to Milhon."

**Comment by mfahampshire** [comment]
Note is present in https://nymtech.net/docs/run-nym-nodes/mixnodes/#running-a-mixnode-for-the-first-time & https://nymtech.net/docs/run-nym-nodes/incentives/ regarding this, closing.
