### ISSUE TITLE
Error when init Nym client for Nym requester

### ISSUE THREAD

**Issue by Ch1ffr3punk** [nymtech/nym#800]
Hi,

I just installed Nym according to the docs at your site and when running the client for the Nym requester I receive the following error:

./nym-client init --id requester-client --gateway 4kjgWmFU1tcGAZYRZR57yFuVAexjLbJ5M7jvo3X5Hkcf

      _ __  _   _ _ __ ___
     | '_ \| | | | '_ \ _ \
     | | | | |_| | | | | | |
     |_| |_|\__, |_| |_| |_|
            |___/

             (client - version 0.11.0)

Initialising client...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ValidatorAPIError { source: ReqwestClientError { source: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("testnet-milhon-validator1.nymtech.net")), port: Some(8080), path: "//v1/gateways", query: None, fragment: None }, source: hyper::Error(IncompleteMessage) } } }', clients/native/src/commands/init.rs:103:65
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

**Comment by tommyv1987** [comment]
Hi @sac001 

Have you tried again since you reported this issue? If not I will take a look to see if I can reproduce it today.

Thanks

**Comment by Ch1ffr3punk** [comment]
Thanks for your reply. No, I have not.

Regards
Stefan

**Comment by tommyv1987** [comment]
Hi @sac001, I was away last week, I apologise this has cropped up on my list of things to action this week. I will update in due course. 

Thanks for being patient.

**Comment by Ch1ffr3punk** [comment]
@tommyv1987 No problem, I can wait.

Regards
Stefan

**Comment by tommyv1987** [comment]
Hi @sac001  I apologize for the slow response: 
Just to confirm
- You had checkout the correct version of the binaries to build and run the requester
- I know it's of preference but did you try to use any other gateways listed on the nym-network explorer?

Did you ensure that there was no whitespace when inputting the gateway? 
I was able to successfully configure my profile for this gateway.
![image](https://user-images.githubusercontent.com/60836166/143218310-174927cb-327e-4388-a0ec-759a361873ad.png)

**Comment by Ch1ffr3punk** [comment]
@tommyv1987

Thanks for the tip, now it is working. Not sure what I did wrong.

Regards
Stefan
