### ISSUE TITLE
[Issue] React Example project does not compile when using @nymproject/nym-client-wasm v0.9.0-1

### ISSUE THREAD

**Issue by ghost** [nymtech/nym#878]
**Describe the issue**
When I use the @nymproject/nym-client-wasm on version 0.9.0-1 and I try to start the react-example project, I get a compiling error

**Expected behaviour**
It should compile properly and start the dev-server

**Steps to Reproduce**
- Given I was trying the webassembly client with the react-example project
- And I installed the npm package : @nymproject/nym-client-wasm v0.9.0-1
- When I started the dev-server
- Then I got a compiling error

**Screenshots**
<img width="1109" alt="Screenshot 2021-11-04 at 14 18 39" src="https://user-images.githubusercontent.com/47139070/140320290-6942576b-ef4e-47da-b268-398c29a991ad.png">

**Which area of Nym were you using?**
 - Application:  WebAssembly client
 - OS: MacOs BigSur
 - Browser: Brave, Firefox
 - Version: nym binary(0.11.0)

**Comment by elliehachemjob** [comment]
I tested it out in codesandbox it seems to be working fine 

https://codesandbox.io/s/vigilant-forest-c0uff

could you try building using Yarn?

**Comment by ghost** [comment]
Hey @elliehachemjob, thanks for your answer.

I forked your sandbox to load wasm pkg in this one : https://codesandbox.io/s/sweet-meitner-0ee55

The error seems to be quiet similar to what I get locally

**Comment by tommyv1987** [comment]
Hi @SeraphinBoccacci 

Thank you for raising this issue, we will need to upgrade our wasm package to be aligned with our current release.

This is on our agenda to fix and has been moved into with our teams queues.

**Comment by tommyv1987** [comment]
Closing this issue. The Wasm client has been updated, and the code is in develop. There is a task to clean up the example, which will happen shortly.
