### ISSUE TITLE
Pasting mnemonic doesn't work on MacOS

### ISSUE THREAD

**Issue by diezd** [nymtech/nym#908]
**Describe the issue**
I downloaded the wallet and created an account, which generated my mnemonic, that I could copy and store somewhere safe, but when I tried to copy it back into the login screen, it was getting blocked. If that is a feature for security reasons, that is fine, you just need to make users aware of that. If not, then it is easier to just copy in the mnemonic rather than make typos.

**Expected behaviour**
I expected to copy/paste from my password manager.

**Stack Traces**
If there are stack traces or logs, please provide them here...

**Steps to Reproduce**
Steps to reproduce the behaviour, if you're familiar with BDD syntax, please write it in this style:
- Given I was doing X
- And I installed Y
- When I actioned Y
- Then I expect Z

*An example:*
- Given I was setting up a mix-node following the instructions in the docs
- And I successfully bonded my node via the the wallet
- When I went to start my mixnode
- Then I was presented with an error

**Screenshots**
If applicable, add screenshots to help explain your problem...

**Which area of Nym were you using?**
Nym Wallet for MacOS x64 dmg

**Additional context**
Please provide any other information

**Comment by tommyv1987** [comment]
Hi @diezd, this issue has been fixed. We're working on a few other components before making another release.

Here is the [commit](https://github.com/nymtech/nym/commit/e5051f98c5729b4e585f96d3233a939543593603)

This will go out shortly, thank you.
