### ISSUE TITLE
[Issue]"create account" button does not work on Ubuntu 20.04.03 LTS

### ISSUE THREAD

**Issue by CyberAtlantide** [nymtech/nym#916]
**Describe the issue**
A clear and concise description of what the issue is...

I can't  create a new Account because the link on the App doesn't work!

I started the app with this command line :
./nym-wallet_linux_0.1.0_amd64.AppImage

**Expected behaviour**
A clear and concise description of what you expected to happen...

I was expecting to create a new wallet account.

**Stack Traces**
If there are stack traces or logs, please provide them here...
No

**Which area of Nym were you using?**
 - Application: nym-wallet_linux_0.1.0_amd64.AppImage
 - OS: Ubuntu 20.04.3 LTS
 
**Additional context**
Please provide any other information

**Comment by gyrusdentatus** [comment]
https://t.me/nymchan_help_chat/41527 

We have discussed this in the [nym help chat](https://t.me/nymchan_help_chat/41527)

This is the button which is not working for @CyberAtlantide 
![telegram-cloud-photo-size-4-5829998203003582154-y](https://user-images.githubusercontent.com/33793809/143076684-2f002358-e429-4491-bba1-74fd58661786.jpg)

**Comment by tommyv1987** [comment]
@CyberAtlantide  - thank you for raising this issue.

I will have a look into the issue to see if it's reproducible for myself.

**Comment by tommyv1987** [comment]
@CyberAtlantide - I have the same profile as you here. And I was able to successfully select the create button, the app image was downloaded from the github release page.

Can you try in similar fashion like this video?

Thank you.

https://user-images.githubusercontent.com/60836166/143211528-08b664ed-43a0-4ad0-ad8e-1a64ce4faea4.mov

**Comment by gyrusdentatus** [comment]
@tommyv1987 this could possibly be caused by some dependencies missing on his system. See my PR for nym-wallet docs https://github.com/nymtech/docs/pull/84

Have you tried this on a mint/vanilla Ubuntu?

**Comment by CyberAtlantide** [comment]
> https://t.me/nymchan_help_chat/41527
> 
> We have discussed this in the [nym help chat](https://t.me/nymchan_help_chat/41527)
> 
> This is the button which is not working for @CyberAtlantide ![telegram-cloud-photo-size-4-5829998203003582154-y](https://user-images.githubusercontent.com/33793809/143076684-2f002358-e429-4491-bba1-74fd58661786.jpg)

Yes, this is not working for me!

**Comment by CyberAtlantide** [comment]
> 



> @tommyv1987 this could possibly be caused by some dependencies missing on his system. See my PR for nym-wallet docs [nymtech/docs#84](https://github.com/nymtech/docs/pull/84)
> 
> Have you tried this on a mint/vanilla Ubuntu?

**Comment by CyberAtlantide** [comment]
> @CyberAtlantide - I have the same profile as you here. And I was able to successfully select the create button, the app image was downloaded from the github release page.
> 
> Can you try in similar fashion like this video?
> 
> Thank you.
> 
>  ubuntu_wallet.mov

Yes I have tried that and still not working!
