### ISSUE TITLE
Mixnodes - claim tokens scenario does not work with telegram bot

### ISSUE THREAD

**Issue by ivanproskuryakov** [nymtech/nym#938]
**Describe the issue**

Claiming tokens in telegram fails with the message, the message:

> @cryptoneverdie, the signature on your message did not verify correctly - are you sure you signed the correct message? (You're supposed to sign "@your-telegram-user your-punk-wallet-address")

**Expected behavior**
According to the documentation claim, claim token operation should add tokens to the wallet - which does not happen.

**Stack Traces**
If there are stack traces or logs, please provide them here...

**Steps to Reproduce**
- ./nym-mixnode init --id winston-smithnode --host $(curl ifconfig.me)
- ./nym-mixnode sign --id winston-smithnode --text "@IvanProskuryakov punk1xxxxxxxxxxxxxxxx"

Outputs
```
(mixnode - version 0.11.0)
    
Signing the text "@IvanProskuryakov punk1xxxxxxxxxxxxxxxx" using your mixnode's Ed25519 identity key...

Signature is: aGUcxPSTBGuZKJ9ysJsucYUrod76ci7swUHpkqV7qHRSWPVgnMU5g6TSyBMueMJzM4kd7t2nhUAfY1dm8EKFwAs

You can claim your mixnode in Telegram by talking to our bot. To do so:

* go to the 'https://t.me/nympunkbot' channel
* copy the following line of text, and paste it into the channel

/transfer punk1xxxxxxxxxxxxxxxx yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
```

The screenshot of the command sent to the bot in telegram.
<img width="1054" alt="Screenshot 2021-12-03 at 17 30 03" src="https://user-images.githubusercontent.com/3517364/144619333-38c31a26-384c-4a96-b7d0-39758e9c1d7a.png">

**Comment by tommyv1987** [comment]
Hi @ivanproskuryakov, 

Thank you for taking the time to lodge this.

However, unfortunately at the moment we're not issuing out any new `PUNK` tokens to join the MILHON test network - please refer to [docs](https://nymtech.net/docs/current/run-nym-nodes/mixnodes).

Do keep an eye out on the latest updates in the telegram channel.

**Comment by ivanproskuryakov** [comment]
@tommyv1987 will the same operation of issuing test tokens work on Finney testnet?

**Comment by tommyv1987** [comment]
@ivanproskuryakov - Finney was our first test-net, this then migrated across to the Milhon test-net. Finney was deprecated and Milhon essentially took it's place.  Therefore, no tokens exist for Finney I'm afraid.
