### ISSUE TITLE
NYM wallet setup trouble[Issue]

### ISSUE THREAD

**Issue by Iamfittz** [nymtech/nym#958]
**Describe the issue**
Have issue on setup wallet, describes on screenshot

**Which area of Nym were you using?**
 - Application: [ Wallet]
 - OS: [ Windows 7]
 - Version:  nym-wallet_windows_0.1.0_x64.msi

![image_2021-12-14_10-48-11](https://user-images.githubusercontent.com/71097194/145967789-c8223a25-9fc6-4aef-8114-4defb0866dc3.png)

**Comment by tommyv1987** [comment]
Hi @Iamfittz,

Unfortunately, the wallet was not built or tested against Windows  7. Windows 7 support was also discontinued in Jan 2020, we recommend you try, if possible, to use a later version of Windows (10). It doesn't fit in our compatibility matrix, either.

I'm going to close this ticket.
