### ISSUE TITLE
[Issue] NYM wallet doesn't work after login

### ISSUE THREAD

**Issue by danny-pham** [nymtech/nym#995]
**Describe the issue**
Can not use NYM WALLET after login

**Stack Traces**
There was an issue with a tendermint RPC request - serde parse error Caused by: expected value at line 1 column 1 Location: C:\Users\Alex\.cargo\registry\src\github.com-1ecc6299db9ec823\flex-error-0.4.4\src\tracer_impl\eyre.rs:10:9

**Steps to Reproduce**
Login

**Screenshots**
If applicable, add screenshots to help explain your problem...

**Which area of Nym were you using?**

 - OS: Win 10
 - Version: nym-wallet_0.12.0_windows_x64.msi

**Comment by tommyv1987** [comment]
Hey @danny-pham 

Some users including yourself have reported a similar issue in wallet usage. 

What is needed... 

The wallet must be able to connect to:

`sandbox-validator.nymtech.net:443`
and
`sandbox-validator.nymtech.net:1317`

You can  check whether you have connectivity problems for port 443,  by navigating to `https://sandbox-validator.nymtech.net `in a browser (as TLS runs on port 443)

But you can't test port 1317 in the browser. You'd need to use something like telnet...

```
telnet sandbox-validator.nymtech.net 1317
Trying 139.162.246.41...
Connected to sandbox-validator.nymtech.net.
Escape character is '^]'.
```
That's a successful connection :point_up: 

But if you see nothing happening, it means that port is blocked. This is not a wallet problem, you will need to fix your networking before anything wallet-related will work. These issues to happen when users are running strange VPNs etc.

I'm going to close the ticket as this is an end user networking related issue.
